////

|metadata|
{
    "name": "formula-values-from-an-excel-file",
    "controlName": [],
    "tags": [],
    "guid": "{7B333D78-B68D-4178-B489-9321884F2976}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Formula Values from an Excel File

The Infragistics Excel Engine™ now has the ability to retrieve the actual calculated values from Formulas that exist on an Excel® Worksheet. Previously, when attempting to programmatically access a Cell value of an Excel Cell that is composed of an Excel Formula, you would get the actual literal string that represents the Excel Formula. With this new feature, whether you are accessing Formulas created by the Excel Library’s object model or existing Formulas that were created through Microsoft® Excel, you now get the actual evaluated value of the formula.

== *Related Topics*

link:excelengine-getting-the-value-of-a-formula-from-an-excel-file.html[Getting the Value of a Formula from an Excel File]

link:wingrid-getting-excel-formula-values-into-wingrid.html[Getting Excel Formula Values into WinGrid]