////
|metadata|
{
    "name": "getting-started-where-files-are-placed-on-your-file-system-during-installation",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{954281B4-BF65-48B0-950D-113FED711CDA}",
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Where Files are Placed on your File System During Installation

This topic explains where files and folders that are included in the Installer are placed on your file system.

== Win Presets

`C:\Users\Public\Documents\Infragistics\20{ProductVersion}\Presets\CLR4x\Win`

This folder contains all the in-box presets provided by Infragistics for all Infragistics Windows Forms controls and components. You can use a preset to apply a range of formatting and behavior options across the elements of your interface and applications. Presets are saved in an XML format.

There are three different types of presets:

* Look -- Contains information for the visual styling of the control or component

* Behavior -- Contains information on how the control or component will behave

* Look and Behavior -- Contains information on the visual styling of the control or component and the behavior of the control or component


== Win Styles

During installation you will be given the option to install 'Just Me' or 'All Users'. Depending on your selection, the Templates, Palettes and Styles folders will be placed in different areas.

=== 'Just Me' option selected

`C:\Users\[USERID]\Documents\Infragistics\20{ProductVersion}\Windows Forms\AppStylist for Windows Forms\Palettes`

`C:\Users\[USERID]\Documents\Infragistics\20{ProductVersion}\Windows Forms\AppStylist for Windows Forms\Styles`

`C:\Users\[USERID]\Documents\Infragistics\20{ProductVersion}\Windows Forms\AppStylist for Windows Forms\Templates`

=== 'All Users' option selected

`C:\Users\Public\Documents\Infragistics\20{ProductVersion}\Windows Forms\AppStylist for Windows Forms\Palettes`

`C:\Users\Public\Documents\Infragistics\20{ProductVersion}\Windows Forms\AppStylist for Windows Forms\Styles`

`C:\Users\Public\Documents\Infragistics\20{ProductVersion}\Windows Forms\AppStylist for Windows Forms\Templates`

These folders contain all the styles available within Windows Forms. Styles are used by the Application Styling Framework (ASF) when styling your application.

== Global Assembly Cache

`C:\Windows\Microsoft.NET\assembly\GAC_MSIL\`

For more information, see link:win-deploying-your-application.html[Deploying Your Application].


== Version Utility

`C:\Program Files\Common Files\Infragistics\Infragistics {ProductVersion}\Version Utility`

This folder contains all the Version Utility files required for upgrading projects.

== Main Infragistics Installation Folder

`{InstallPath}`

This folder and its sub-folders contain the Windows Forms assemblies that are used at design-time as well as the assemblies that are used at runtime. Other files include files that are depended on by certain controls (e.g. the Dictionary files used by  `WinSpellChecker`).