////

|metadata|
{
    "name": "ig-spe-create-a-textdocument",
    "controlName": [],
    "tags": [],
    "guid": "fe206df9-c3a6-418d-99ff-ea3bc7dbd0b9",  
    "buildFlags": [],
    "createdOn": "2013-06-13T18:57:35.1038553Z"
}
|metadata|
////

= Create a TextDocument

== Topic Overview

=== Purpose

This topic introduces the TextDocument and explains how to set a language on the TextDocument.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:ig-spe-syntax-parsing-engine-overview.html[Syntax Parsing Engine Overview]
|This topic provides an overview of the Syntax Parsing Engine.

| link:ig-spe-grammar-overview.html[Grammar Overview]
|This topic provides an overview of the Syntax Parsing Engine’s Grammar.

| link:ig-spe-create-custom-language.html[Create Custom Language]
|This topic explains the process of creating a custom language.

|====

== TextDocument Introduction

=== Overview

The link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents.textdocument.html[TextDocument] is a class in the link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents_namespace.html[Infragistics.Documents] namespace which provides all the functionality for parsing and modifying a document. To set custom languages use the link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents.textdocument~language.html[Language] property of the `TextDocument` class.

For example, here is how to set a C# language to the `TextDocument`:

*In C#:*

[source,csharp]
----
var document = new TextDocument();
document.Language = CSharpLanguage.Instance;
----

To load content in the document you can use the link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents.textdocument~initializetext.html[InitializeText] method or one of the link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents.textdocument~load.html[Load] methods. As changes are made to the document, almost all tokens are reused so that the lexical analyzer only needs to analyze the parts of the document which have changed.

== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:ig-spe-create-custom-language.html[Create Custom Language]
|This topic explains the process of creating a custom language.

| link:ig-spe-customize-error-messages.html[Customize Error Messages]
|This topic explains how to customize the error messages produced by the Syntax Parsing Engine.

| link:ig-spe-working-with-the-syntax-tree.html[Working With the Syntax Tree]
|The topics in this group explain in detail how to work with the Syntax Tree.

| link:ig-spe-textdocument-overview.html[TextDocument Overview]
|This topic contains links to conceptual information and code snippets related to the TextDocument class.

| link:ig-spe-textdocumentsnapshot-overview.html[TextDocumentSnapshot Overview]
|This topic provides an overview of the TextDocumentSnapshot object’s properties and methods.

| link:ig-spe-textdocumentsnapshotscanner-overview.html[TextDocumentSnapshotScanner Overview]
|This topic provides an overview of the TextDocumentSnapshotScanner object’s properties and methods.

|====