////

|metadata|
{
    "name": "infragistics-math-vectors",
    "controlName": ["Infragistics Math Library"],
    "tags": ["Application Blocks","Calculations"],
    "guid": "55f92af7-bc4b-4e08-b0e5-cb69b66ba8f0",  
    "buildFlags": [],
    "createdOn": "2011-08-01T14:11:57.769981Z"
}
|metadata|
////

= Vectors

The Infragistics Math Library™ provides functionality for working with vectors.

== About Vectors

Vectors are one-dimensional data classes for storing collections of objects. link:{ApiPlatform}math{ApiVersion}~infragistics.math.vector.html[Vector] can be a link:http://en.wikipedia.org/wiki/Row_vector[Row Vector] or a link:http://en.wikipedia.org/wiki/Column_vector[Column Vector].

== Using Vectors

Infragistics Math Library supports the following vector classes:

* link:{ApiPlatform}math{ApiVersion}~infragistics.math.vector.html[Vector] – stores a collection of real numbers
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.booleanvector.html[BooleanVector] – stores a collection of boolean values
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.complexvector.html[ComplexVector] – stores a collection of complex numbers

These classes are all derived from the link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrixbase.html[MatrixBase] class. They differ in the data types they store.

The following topics will guide you how to use vectors in the Infragistics Math Library:

* link:infragistics-math-creating-vectors.html[Creating Vectors]
* link:infragistics-math-working-with-vectors.html[Working With Vectors]

== Related Topics

link:infragistics-math-complex-numbers.html[Complex Numbers]

link:infragistics-math-matrices.html[Matrices]

link:infragistics-math-mathematical-functions.html[Mathematical Functions]