////

|metadata|
{
    "name": "infragistics-math-matrices",
    "controlName": ["Infragistics Math Library"],
    "tags": ["Application Blocks","Calculations"],
    "guid": "f61fd87b-e8f6-4894-959d-77dde491ea17",  
    "buildFlags": [],
    "createdOn": "2011-08-01T14:11:12.5924637Z"
}
|metadata|
////

= Matrices

The Infragistics Math Library™ provides functionality for working with matrices.

== About Matrices

Matrices are multi-dimensional data classes for storing collections of objects. For more conceptual information refer to the link:http://en.wikipedia.org/wiki/Matrix_(mathematics)[Matrix] website.

== Using Vectors

Infragistics Math Library supports the following matrix classes:

* link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrix.html[Matrix] – stores a collection of real numbers
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.booleanmatrix.html[BooleanMatrix] – stores a collection of boolean values
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.complexmatrix.html[ComplexMatrix]– stores a collection of complex numbers

These classes are all derived from the link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrixbase.html[MatrixBase] class. They differ in the data types they store.

The following topics will guide you how to use matrices in the Infragistics Math Library:

* link:infragistics-math-creating-matrices.html[Creating Matrices]
* link:infragistics-math-working-with-matrices.html[Working With Matrices]

== Related Topics

link:infragistics-math-complex-numbers.html[Complex Numbers]

link:infragistics-math-vectors.html[Vectors]

link:infragistics-math-mathematical-functions.html[Mathematical Functions]