////

|metadata|
{
    "name": "introduction-getting-support",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{5FA9BB45-07E4-4EE2-9A7A-2AD6AEB89596}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Getting Support

If you own a copy of Infragistics Professional, you are entitled to certain benefits regarding support services offered by Infragistics.

== Creating a Member Profile

Visit the "My Infragistics" area of link:http://www.infragistics.com/[Infragistics' Web site], and create a link:https://www.infragistics.com/my-account/edit-profile[Member Profile]. It is important that your most current information is entered into your Member Profile, this will ensure that our Support Service Department can deliver support correspondence and subscription upgrades to you.

== Registering your Product Key

After creating a Member Profile, register your Product Key to your MemberID by visiting the link:https://www.infragistics.com/my-account/register-product[Product Registration] page. This will provide you with superior technical support services quickly and conveniently. Your MemberID is connected to your personal profile. Your registration identifies you as the active developer entitled to use and request support for the Infragistics product you have registered.

== Getting MemberID Information

You can always visit your link:https://www.infragistics.com/my-account/register-product[Registration Records] and review your purchases, issued subscription upgrade keys and registered keys online, 24 hours a day, 7 days a week. After logging in with your MemberID, you'll be able to view vital information including product keys and subscription service and status.

== Getting Help

A wealth of valuable information is available at our link:http://devcenter.infragistics.com/Default.aspx[DevCenter]. DevCenter is a customer community location for self-service support information, technical articles, reference applications and much more. For more information on what help is available, hover your mouse over the "Support" menu item in the left pane of DevCenter.

Important link:http://www.infragistics.com/support/support-policies[Support Policies] and phone support contact information is also available on DevCenter.

*Note:* You must have valid priority support to access phone support.

Each Infragistics product registered user can submit requests for technical support via the Web site. To log an incident or start any support issue, please log on to DevCenter to link:http://www.infragistics.com/support/support-policies[Submit a Support Issue] and enter your MemberID. For your convenience, you can also attach a sample project if applicable.

== Product Life Cycle

Infragistics Product Life Cycle information is available link:http://www.infragistics.com/support/product-lifecycle[online] and provides the following information:

* name and version of the Infragistics tools
* product maintenance (bug fix) period
* product support period
* product status

For issues related to your account, product ownership, or registration, please e-mail link:mailto:Registrations@Infragistics.com[Registrations@Infragistics.com]. Include your name and product key (if known) so that we may better assist you. You can also call (609) 448-2000 9 a.m. to 5 p.m., Monday to Friday, EST US.