////

|metadata|
{
    "name": "introduction-using-version-free-assemblies",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "58c92456-d7d7-48d2-b9f2-65428cccf887",  
    "buildFlags": [],
    "createdOn": "2010-06-02T17:29:55.7452483Z"
}
|metadata|
////

= Using Version Free Assemblies

Version-free assemblies are available to you in a zipped format (within ‘Version-Free’ folder) along with the product install at location: {InstallPath}

.Note
[NOTE]
====
When using the version-free assemblies, you must perform a complete regression test on your application and also review the breaking changes section of our Help, starting from the volume release that you previously had before upgrading.
====

To use these version-free assemblies, you should manually do the following:

1. Take a backup of the assemblies that you already have in the Bin ({InstallPath}\CLR4.0\Bin) folder.

2. Unzip the ‘WinForms_{ProductVersionFull}_VersionFree.zip’ folder available at the location {InstallPath}\Version-Free.

3. Copy the version-free assemblies from the extracted folder into the Bin folder.

4. Add the version-free assemblies located in the Bin folder to the Global Assembly Cache (GAC). You can add assemblies to the GAC by using the link:http://msdn.microsoft.com/en-us/library/ex0ss12c.aspx[Gacutil.exe]. Starting with the .NET Framework 4, the default location for the global assembly cache is %windir%\Microsoft.NET\assembly.

5. Create a toolbox tab in Visual Studio and add the controls in the version-free assemblies located in the Bin folder.

== *Related Topic*

link:introduction-about-version-free-assemblies.html[About Version-Free Assemblies]