= About Infragistics Trial Version

We are confident in our controls, and we want you to be, too.

You may use this trial version to evaluate and become comfortable and confident with our tools suite for up to thirty days. While using the trial, a watermark will render at run-time notifying the user that the application was developed with a trial version of the toolset. If you need support, we’ll provide it through the thirty-day trial period.

After thirty days, your trial period will end, along with product support for the trial. If you purchase Infragistics, we’ll send you a key to unlock the product and remove the trial watermark. If you have already installed the trial version of the assemblies, simply run the installer file from the appropriate directory (e.g., C:\Program Files\Infragistics\20{ProductVersion}) and insert your key when prompted by the installation wizard. Anything that you’ve previously built with the trial assemblies will now reference fully unlocked assemblies, removing the trial watermark.