////

|metadata|
{
    "name": "introduction-running-the-toolbox-utility",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{CA8691D2-EAAF-45D6-A699-39A68534B670}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Running the Toolbox Utility

The easiest way to add all of the controls available in the Infragistics Professional toolkit to your Visual Studio .NET toolbox is to run the Create Visual Studio Toolbox Tab utility.

*To run the Toolbox Utility:*

[start=1]
. Close all running instances of Microsoft® Visual Studio®.
[start=2]
. From the Windows Start menu, navigate to the utility as follows:

____
Start > All Programs > Infragistics >20{ProductVersion} > Windows Forms > Utilities > Create Visual Studio Toolbox Tab for Windows Forms CLR4.0 20{ProductVersion}
____

[start=3]
. The utility installs the Infragistics controls and components in the Visual Studio toolbox.

Keep in mind that the installation of the controls and components is dependent on the Infragistics Professional product that is installed. For example, if you install only the Infragistics Windows Forms product, the utility installs only the Infragistics Windows Forms controls and components. If you install both Infragistics Windows Forms and Infragistics ASP.NET products, the utility installs the controls and components for both products.

If the utility installed the controls and components for both Windows Forms and ASP.NET products, in Visual Studio, you can choose to show the tabs for both products by right-clicking anywhere in the toolbox, and selecting "Show All Tabs".

== Related Topics

link:introduction-using-the-choose-toolbox-items-dialog-box.html[Using the Choose Toolbox Items Dialog Box]

link:introduction-dragging-assemblies-from-the-bin-folder.html[Dragging Assemblies from the Bin Folder]