////

|metadata|
{
    "name": "styling-guide-application-styling-the-graphic-designers-perspective",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{2936ED0C-C22B-4779-996E-3B6E0F3AC878}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Application Styling: The Graphic Designers Perspective

Application Styling gives application developers the time they need to develop and it gives graphic designers the tools they need to design. Let's take a look at Application Styling from the graphic designer's perspective. We'll first see how Application Styling benefits the graphic designer and then how it affects the graphic designer, whether Application Styling is being used or not.

== Providing the Necessary Tools

One of the main advantages of Application Styling for the graphic designer is familiarity. Graphic designers no longer need to trudge along in the unfamiliar Visual Studio Integrated Developer's Environment (IDE). Application Styling gives the graphic designer AppStylist for Windows Forms, a unique tool that was designed with the graphic designer in mind. AppStylist empowers the graphic designer to create vibrant style libraries that can be loaded into any Visual Studio project with only one line of code. For now, let's place the application developer aside and see how the graphic designer performs without the help of Application Styling.

== Unfamiliar Territory

Kate works as a graphic designer in her company. She's very talented and has come through for the company on many occasions helping to design graphic user interfaces. However, she feels held back by the inability to collaborate effectively with the application developers. First off, Kate's company uses source control. Considering that developers are higher priority than graphic designers, Kate doesn't have the access to the code that she needs. Her superiors expect results, but she can't deliver results when she needs to. Secondly, when she does have access to the Visual Studio project, she is always hunting through property windows in order to find the property that will give her the visual effect she's looking for. Kate is used to working with graphic intensive software such as Adobe® and Macromedia® products. The Visual Studio IDE is unfamiliar territory to Kate. Lastly, in changing some of these properties, Kate unknowingly introduced a bug into the application. Now the developers are even more protective of their code than they were before.

The last thing anyone wants is to leave their comfort zone. Not meeting deadlines, using unfamiliar user interfaces, tension with developers; Kate really has her hands full. However, Application Styling takes all of these cases into account and offers alternatives that both Kate and the application developers will benefit from. Let's see what happens now when Kate's company employs the Application Styling Framework™ (ASF) with the help of AppStylist.

== The Stress Level Falls

Since the previous software release, Kate is not on good terms with the developers. Her superiors realize that there must be a better way for her and the application developers to collaborate. Soon after, Kate receives a new software package, AppStylist. After the quick installation, she fires up the software. Kate is greeted by a Start page that explains how to get started step-by-step. Soon enough, Kate is flying through the intuitive user interface with the help of unique ToolTips that dynamically guide her through what used to be a tedious search in the properties window of Visual Studio. Before long, she realizes that she styled the entire WinGrid and never even touched any code. All of her changes are displayed directly in front of her on several different canvases designed for specific components. Finally, she saves her work as an Infragistics Style Library (.isl) file and hands it over to one of the application developers.

It is quite apparent that AppStylist has solved each one of Kate's problems. She was able to work at her own pace while avoiding the risky environment of the Visual Studio IDE. Because AppStylist was designed with the graphic designer in mind, Kate was able to easily navigate through the user interface which resembles other graphic design software. Kate isn't the only employee who received benefits from Application Styling; application developers benefit from Application Styling just as much. Let's take a look at Application Styling from link:styling-guide-application-styling-the-developers-perspective.html[The Developer's Perspective].