////

|metadata|
{
    "name": "styling-guide-introducing-application-styling-for-windows-forms",
    "controlName": [],
    "tags": [],
    "guid": "{B7217058-3834-4805-8990-AEC2F4C2212A}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Introducing Application Styling for Windows Forms

Application Styling is a ground-breaking concept in Windows Forms development that allows developers and graphic designers to collaborate more efficiently. The developer creates the application, while at the same time graphic designers create styles that can be used in that application. When finished, the graphic designer hands off the style library to the developer who then loads it into the application with only one line of code. Developing world-class applications with a stylish look and feel to go along with it has never been easier. Whether you're a one-person shop or an enterprise-level business, everyone can reap the benefits of Infragistics'® Application Styling.

Application Styling brings two unique perspectives to application development. Both application developer and graphic designer are affected by Application Styling. Click the links below to get a glimpse of these unique perspectives and learn more about Application Styling.

* link:styling-guide-application-styling-the-developers-perspective.html[Application Styling: The Developer's Perspective]
* link:styling-guide-application-styling-the-graphic-designers-perspective.html[Application Styling: The Graphic Designer's Perspective]
* link:styling-guide-sample-style-libraries.html[Sample Style Libraries]