////

|metadata|
{
    "name": "styling-guide-styling-your-application",
    "controlName": [],
    "tags": ["Styling","Templating"],
    "guid": "{0F42F3F5-20E5-43AC-AA01-9E76E9184097}",  
    "buildFlags": [],
    "createdOn": "2006-11-04T00:00:00Z"
}
|metadata|
////

= Styling Your Application

Application Styling gives the graphic designer the privilege of working with Infragistics' very own AppStylist®. AppStylist is a breakthrough application that assists both the application developer by freeing them up to do more coding and the graphic designer by leveraging their individual skills. This specific section of the help will guide the graphic designer through every aspect of the AppStylist experience by helping them create and maintain Style Libraries, understand the AppStylist user interface, and use the different controls of the UI to make stylish themes for their applications. Click the links below to learn more about AppStylist.

* link:styling-guide-introducing-application-styling-for-windows-forms.html[Introducing Application Styling for Windows Forms]
* link:styling-guide-getting-started.html[Getting Started]
* link:styling-guide-getting-to-know-infragistics-appstylist-for-windows-forms.html[Getting to Know AppStylist for Windows Forms]
* link:styling-guide-walkthroughs.html[Walkthroughs]
* link:styling-guide-known-issues-and-limitations.html[Known Issues and Limitations]