////

|metadata|
{
    "name": "styling-guide-application-styling-the-developers-perspective",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{8EEED3DE-C0B1-450D-A716-04DED8E3C54F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Application Styling: The Developers Perspective

Application Styling gives the application developer the time they need to develop and it gives the graphic designer the tools they need to design. Let's take a look at application styling from the application developer's perspective. We'll first see how Application Styling benefits the developer, then, we'll see how it affects him, whether Application Styling is being used or not.

== Defining the Line

One of the main advantages of Application Styling for the developer is time. Now that Application Styling has defined the line between developing an application and styling an application, the developer can spend more time doing what he knows best: developing. Application Styling doesn't start off with the developer, however. Technically, it doesn't start off with the graphic designer either. Both the developer and graphic designer perform their jobs at the same time, separately. That's the beauty of Application Styling. For the time being, let's place the graphic designer aside and see how the application developer performs his daily routine without the aid of Application Styling.

== Bland and Unfinished

Mike, an application developer, works hard everyday to develop a bug-free user interface for his company's upcoming software release. After several grueling weeks of coding and debugging, he puts the finishing touches on his UI. However, although the UI is functioning properly, it still looks somewhat bland and unfinished. Mike's superior now demands that he work the next couple of days to give the application a polished look. Try as he might, Mike just can't get the right combination of colors and styles to give the application that finishing touch.

We all feel the pain for Mike, and several of us know exactly what he's going through. However, Application Styling gives Mike and his company a better way. Let's see what happens when Mike's company employs the Application Styling Framework™ (ASF) with the help of AppStylist for Windows Forms.

== Help Arrives Just in Time

Mike is extremely tired and the stress from the last couple of weeks has really affected him. He knows that the previous product release could have been better, he just didn't have the necessary skill set. However, Mike's superiors have decided to take a new approach to development. Using Infragistics' own ASF, Mike's superiors gave the chore of styling the UI to a graphic designer using AppStylist. Mike doesn't know much about Application Styling, and doesn't have to. He begins doing what he does best, developing the new software. After he finishes developing, Mike remembers the last software release and cringes at the realization that it is now time to begin styling. Suddenly, Mike receives an Infragistics Style Library (.isl) file from Kate, the graphic designer.

____
"What am I supposed to do with this?" Mike asks.
____

____
Kate replies, "Just add this one line of code to the Main method and you're ready to go."
____

____
"That's it?" says Mike, astonished. "One line of code and the entire application is styled?"
____

____
Kate smiles and says, "Just one line."
____

What Mike didn't know is that Kate was styling the application while he was developing the application. With this new collaboration, Mike was freed up at the end of the software development cycle to tweak the UI some more. He also found several bugs that were missed the first time around. What really impressed Mike is that the UI looked so fresh and new and Kate didn't even touch his code. How was Kate able to accomplish all this? Let's take a look at Application Styling from link:styling-guide-application-styling-the-graphic-designers-perspective.html[The Graphic Designer's Perspective].