////

|metadata|
{
    "name": "styling-guide-sample-style-libraries",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{BDA3C202-BE4D-423D-BCDE-77891FB0B37C}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Sample Style Libraries

AppStylist for Windows Forms ships with ten custom Style Libraries. Each of these Style Libraries was designed by Infragistics' Visual Design team. These Style Libraries were created to demonstrate the full styling capabilities of AppStylist in various scenarios.

To use the sample Style Libraries, open a new Style Library from the File menu and navigate to the {InstallPathXP} {ProductVersion}\Windows Forms\AppStylist for Windows Forms\Styles folder on Windows XP, or {InstallPathVista} {ProductVersion}\Windows Forms\AppStylist for Windows Forms\Styles folder on Windows Vista where these Style Libraries are stored.

.Note
[NOTE]
====
If you choose to modify one of these Style Libraries, save the .isl file with a new name. If you do not, your modified Style Library will be removed if you uninstall the product.
====