////

|metadata|
{
    "name": "styling-guide-application-styling-framework-asf",
    "controlName": [],
    "tags": [],
    "guid": "{E29067E9-77F9-4A8C-9B2F-9DACFF781AA9}",  
    "buildFlags": [],
    "createdOn": "2006-11-04T00:00:00Z"
}
|metadata|
////

= Application Styling Framework (ASF)

We designed the Application Styling Framework™ (ASF) to make styling your applications as simple as possible. Using the ASF, you can create one style (known as StyleSets) and apply it to any of your applications. Create a StyleSet with AppStylist® and then apply that StyleSet to your application using the custom APIs found in the Infragistics.Win.AppStyling namespace. That's not all, you can style inbox controls with the InboxControlStyler component or even run a runtime version of AppStylist in your own application.

* link:styling-guide-asf-overview.html[ASF Overview] -- The ASF Overview will teach you the basics of the ASF and how the different components interact.
* link:styling-guide-setting-up-your-application-for-styling.html[Setting Up Your Application for Styling] -- The application developer needs to know, for example, how to load Style Libraries and change StyleSets at runtime. This is where you can find that information.
* link:styling-guide-styling-your-application.html[Styling Your Application] -- AppStylist is a unique stand-alone application that graphic designers can use to create StyleSets. This section of the help will teach you all you need to know about creating Style Libraries, StyleSets, Resources, and much more.