////

|metadata|
{
    "name": "styling-guide-using-resources-with-stylesets",
    "controlName": [],
    "tags": [],
    "guid": "{88A31E8F-463B-4B39-90D3-BE2C08399631}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Using Resources with StyleSets

The Application Styling Framework™ supports a unique styling tool called Resources. A Resource is a collection of appearance properties that can be applied to any state. If you are familiar with the Infragistics product, you may recognize Resources as Appearance objects. This connection between appearance objects and resources is a prime example of the Presentation Layer Framework™ and Application Styling Framework working together to increase your productivity.

You can add a new Resource through the Resources tab in the Style Explorer and then apply it to a state of a UI Role. You can also style a state of a UI Role and create a Resource from that state. This flexibility ensures maximum effectiveness and decreases the amount of time you need to create StyleSets.

The following topics will help you create, manage, and apply resources in your StyleSets.

* link:styling-guide-applying-a-resource-to-a-state.html[Applying a Resource to a State]
* link:styling-guide-converting-a-state-into-a-resource.html[Converting a State into a Resource]
* link:styling-guide-importing-and-exporting-resources.html[Importing and Exporting Resources]