////

|metadata|
{
    "name": "styling-guide-setting-up-your-application-for-styling",
    "controlName": [],
    "tags": [],
    "guid": "{78CD49D0-9782-4773-B2A9-A558C98A7678}",  
    "buildFlags": [],
    "createdOn": "2006-11-04T00:00:00Z"
}
|metadata|
////

= Setting Up Your Application for Styling

Application Styling isn't just for the graphic designer. The application developer is just as much a part of Application Styling. The topics in this section will help you, the application developer, perform tasks such as Loading Style Libraries at design time and run time, setting StyleSets for specific components, automatically updating a StyleSet when it's changed, and much more. Click the links below to find out more about these tasks.

* link:styling-guide-loading-a-stylelibrary.html[Loading a Style Library]
* link:styling-guide-changing-stylesets-at-run-time.html[Changing StyleSets at Run Time]
* link:styling-guide-styling-your-application-at-run-time.html[Styling Your Application at Run Time]
* link:styling-guide-create-a-user-control-to-apply-stylesets-at-runtime.html[Create a User Control to apply StyleSets at runtime]