////

|metadata|
{
    "name": "undo-redo-framework",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "3961de75-bd40-45b1-a3c7-e8fcda072341",  
    "buildFlags": [],
    "createdOn": "2012-09-06T12:08:35.3110125Z"
}
|metadata|
////

= Infragistics Undo Redo Framework

=== Introduction

The Infragistics Undo/Redo Framework™ provides support for undo\redo functionality available in most applications.

The framework maintains operations history, executes undo\redo operations, and may group several operations into one single history item. Commands are provided to invoke an undo/redo operation from within your UI.

=== Topics

Detailed information regarding Infragistics Undo/Redo Framework is covered in the following topics:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:undo-redo-framework-methods-and-properties-reference-by-class.html[Undo/Redo Framework Methods and Properties Reference by Class]
|This section contains reference information about the key classes methods and properties in the Infragistics Undo\Redo Framework™.

| link:undo-redo-framework-methods-and-properties-reference-by-task.html[Undo/Redo Framework Methods and Properties Reference by Task]
|This section contains reference information about the key methods and properties in the Infragistics Undo\Redo Framework™ that you may find useful for implementing specific undo\redo functionality.

|====