////

|metadata|
{
    "name": "waw-infragistics-document-engine",
    "controlName": [],
    "tags": [],
    "guid": "{4CE11818-F18D-4EE2-8D24-E711D5B11B38}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Infragistics Document Engine

The Infragistics Document Engine is the purveyor of fine, business reports in both Portable Document Format (PDF) and XML Paper Specification (XPS) file formats. Use the complete Document Object Model (DOM) to handle any report scenario imaginable. The Infragistics Document Engine includes support for report information, preferences, and security. There is also an extensive Graphics object to add color and personality to your reports.

Click the links below to access important information about the Infragistics Document Engine.

== link:documentengine-welcome-to-infragistics-document-engine.html[Welcome to Infragistics Document Engine]

This topic gives you a very high-level overview of the Infragistics Document Engine. You'll be introduced to the numerous report elements that come together to build a professional report, as well as report graphics that add life and color to your report.

== link:documentengine-getting-started-with-infragistics-document-engine.html[Getting Started with Infragistics Document Engine]

Once you have a basic understanding of the Infragistics Document Engine, this topic will help you start using the code library. This topic is a quick walkthrough of the objects you need to create in order to produce a full report.

== link:documentengine-writing-reports.html[Writing Reports]

This section is the meat of the Infragistics Document Engine help. You will be shown the details of each report and graphic element. These topics are in the form of conceptual walkthroughs, as most elements are quite hefty and contain many features!

== link:documentengine-deploying-infragistics-document-engine.html[Deploying Infragistics Document Engine]

If your application uses the Infragistics Document Engine, refer to this topic for a list of the Infragistics product assemblies that you need to redistribute as part of your application.

== link:documentengine-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the Infragistics Excel Engine. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.