////

|metadata|
{
    "name": "waw-infragistics-excel-engine",
    "controlName": [],
    "tags": [],
    "guid": "{03100E03-8DD8-45F3-BCB9-B2AD03138FBB}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Infragistics Excel Engine

The Infragistics Excel Engine is capable of creating entire Microsoft® Excel® Workbooks, including Worksheets. Use this object model to load Excel workbooks, modify them, and then save them again.

Click the links below to access important information about the Infragistics Excel Engine.

== link:excelengine-understanding-the-infragistics-excel-engine.html[Understanding the Infragistics Excel Engine]

In this section you'll find any information that will help you to better understand the functionalities of the Infragistics Excel Engine, as well as why you would want to use it as part of building your applications.

== link:excelengine-using-the-infragistics-excel-engine.html[Using the Infragistics Excel Engine]

This section contains detailed, step-by-step procedures that guide you through common scenarios that you may need to perform when using the Infragistics Excel Engine.

== link:excelengine-deploying-the-infragistics-excel-engine.html[Deploying the Infragistics Excel Engine]

If your application uses the Infragistics Excel Engine, refer to this topic for a list of the Infragistics product assemblies that you need to redistribute as part of your application.

== link:excelengine-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the Infragistics Excel Engine. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.