////

|metadata|
{
    "name": "waw-chart",
    "controlName": ["WinChart"],
    "tags": ["Charting","Getting Started","How Do I"],
    "guid": "{97EE3E00-5335-464D-9B98-FA1C872D4E38}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinChart

If you're looking for an area that houses all of the overview/task-based information related to the WinChart™ control, you've come to the right place. This section contains valuable information about WinChart, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinChart control.

== link:chart-understanding-chart.html[Understanding Chart]

In this section you'll find any information that will help you to better understand the functionalities of the WinChart control, as well as why you would want to use it to as part of building your applications.

== link:chart-chart-types.html[Chart Types]

This key section contains a comprehensive listing of all the 2D and 3D chart types, along with a brief overview of the chart type, information on the type of data that is required to generate the chart type, and a list of properties specific to the chart type.

== link:chart-getting-started-with-chart.html[Getting Started with Chart]

In order to get you up and running as quickly as possible with the WinChart control, we've provided you with information on how to get started using the control (e.g., adding WinChart to your form).

== link:chart-using-chart.html[Using Chart]

This section contains information on the key features and functionalities provided by the WinChart control.

== link:chart-deploying-winchart.html[Deploying WinChart]

If your application uses the WinChart control, refer to this topic for a list of the Infragistics product assemblies that you need to redistribute as part of your application.

== link:chart-winchart-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinChart control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.