////

|metadata|
{
    "name": "whats-new-wingrid-asynchronous-exporting-for-exporters",
    "controlName": [],
    "tags": ["Exporting","Grids"],
    "guid": "ece861fa-70aa-4b37-83c2-e84ba862dd1c",  
    "buildFlags": [],
    "createdOn": "2011-08-31T19:00:43.5013281Z"
}
|metadata|
////

= WinGrid Asynchronous Exporting for Exporters

Starting with 2011 Volume 2 of Infragistics Windows Forms, users can interact with the User Interface (UI) of the application while the export process is executing. This capability, supported by all WinGrid™ export components (WinGridDocumentExporter™, WinGridExcelExporter™, and WinGridWordWriter™) is achieved through exporting the grid asynchronously.

Support for asynchronous exporting means you can keep your application responsive during the export and provide even more productivity to the user.

== Related Topics

* link:wingriddocumentexporter-export-wingrid-asynchronously.html[Export WinGrid Asynchronously] (WinGridDocumentExporter)
* link:wingridexcelexporter-export-wingrid-asynchronously.html[Export WinGrid Asynchronously] (WinGridExcelExporter)
* link:wingridwordwriter-export-wingrid-asynchronously.html[Export WinGrid Asynchronously] (WinGridWordWriter)