////

|metadata|
{
    "name": "whats-new-infragistics-math-library",
    "controlName": [],
    "tags": ["API","Getting Started"],
    "guid": "f91436b8-c4cd-41f9-887a-7c41728c3cdd",  
    "buildFlags": [],
    "createdOn": "2011-10-03T18:09:26.5699206Z"
}
|metadata|
////

= Infragistics Math Library

Starting with 2011 Volume 2 of Infragistics Windows Forms, the Infragistics Math Library provides you with a unified set of core functions that allow you to perform a large range of mathematical operations that are fast, accurate and memory efficient. In addition, the library allows you to:

* Build your own math-driven applications without having to translate your data structures across multiple formats
* Employ numerical methods
* Build compartmental models
* Perform Monte Carlo simulations
* Solve regression problems

For more information please refer to the link:infragistics-math-infragistics-math-library.html[Infragistics Math Library] topic.

== Related Topics

* link:infragistics-math-infragistics-math-library.html[Infragistics Math Library]
* link:infragistics-math-complex-numbers.html[Complex Numbers]
* link:infragistics-math-mathematical-functions.html[Mathematical Functions]
* link:infragistics-math-api-overview.html[API Overview]