////

|metadata|
{
    "name": "whats-new-wineditors-windows-message-support-for-wineditor-controls",
    "controlName": [],
    "tags": [],
    "guid": "eefd4abd-fdf8-4616-850c-3b66eeb340d9",  
    "buildFlags": [],
    "createdOn": "2010-09-16T20:15:15.4961264Z"
}
|metadata|
////

= Windows Message Support for WinEditor Controls

Starting with this release, the Infragistics WinEditor™ controls provide support for a subset of Native Windows Messages that typically apply to Microsoft editor controls such as the TextBox or RichTextBox controls. With this new capability, the WinEditor controls are more compatible for use in applications where Native Windows Messages are used to communicate and interact with external applications and the editor controls. Some examples include, but are not limited to keyboard accessibility applications, screen reader applications, voice recognition software, etc. For more information on the supported messages, please see the link:wineditors-windows-message-support.html[Windows Message Support] topic.

Related Topic:

link:wineditors-editor-controls-classification.html[Editor Controls Classification]