////

|metadata|
{
    "name": "whats-new-autosuggestfiltermode-for-wincombo-and-wincomboeditor",
    "controlName": [],
    "tags": [],
    "guid": "{0CB8D06D-A152-495D-BA6A-C3BDE404F00F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= AutoSuggestFilterMode for WinCombo and WinComboEditor

The WinCombo™ and WinComboEditor™ control’s link:{ApiPlatform}win{ApiVersion}~infragistics.win.autocompletemode.html[AutoCompleteMode] allows you to enable a suggested list of values as your end users type in the control’s text box . New in 2010 Volume 1, the link:{ApiPlatform}win{ApiVersion}~infragistics.win.autosuggestfiltermode.html[AutoSuggestFilterMode] property has been added to WinCombo and WinComboEditor for the purpose of specifying, whether a ‘StartsWith’ or ‘Contains’ condition should be applied to the text that your end users type into the control’s editor. You can also use the new link:{ApiPlatform}win{ApiVersion}~infragistics.win.valuelist~formatfiltereditems.html[FormatFilteredItems] property to highlight end-user typed text that matches within the suggested list of values. This property is set to True by default.

== Related Topics

* link:wincombo-filter-options-to-filter-suggested-values-of-a-column.html[Filter Options to Filter Suggested Values of a Column]
* link:wincomboeditor-filter-options-to-filter-suggested-values.html[Filter Options to Filter Suggested Values]