////

|metadata|
{
    "name": "whats-new-in-2010-volume-3",
    "controlName": [],
    "tags": [],
    "guid": "06ebece7-7167-48fd-9e53-63c870e9f1c3",  
    "buildFlags": [],
    "createdOn": "2010-09-10T14:36:27.6799751Z"
}
|metadata|
////

= What's New in 2010 Volume 3

The Infragistics Windows Forms 2010 Volume 3 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Click the links to see a list of the new features being offered.

* link:whats-new-wintoolbarsmanager-office-2010-ribbon.html[WinToolbarsManager Office 2010 Ribbon]
* link:whats-new-wintoolbarsmanager-wintoolbarsmanager-office-2010-style-application-menu.html[WinToolbarsManager Office 2010 Style Application Menu]
* link:whats-new-application-styling-new-office-2010-look-and-feel.html[New Office 2010 Look and Feel]
* link:whats-new-wineditors-windows-message-support-for-wineditor-controls.html[Windows Message Support for WinEditor Controls]

