////

|metadata|
{
    "name": "whats-new-resizing-drop-downs-in-drop-down-controls",
    "controlName": [],
    "tags": [],
    "guid": "410a1a89-87b3-44d9-b4f7-57bb9e29b0c5",  
    "buildFlags": [],
    "createdOn": "2010-06-02T16:05:23.7670357Z"
}
|metadata|
////

= Resizing Drop-Downs in Drop-Down Controls

We have added support to resize the drop-down in our drop-down controls like WinComboEditor™, WinCombo™, WinDropDown™ and WinPopupControlContainer™. The drop-downs can now be resized using a handle, which can be positioned at the bottom of the drop-down either vertically or diagonally. The resized height and width of the drop-down will be stored for that run of the application. This handle supports the usual Infragistics AppStyling, and styling using the appearance properties.

== *Related Topics*

link:wincomboeditor-resize-drop-down-in-wincomboeditor.html[Resize Drop-Down in WinComboEditor]

link:wincombo-resize-drop-down-in-wincombo.html[Resize Drop-Down in WinCombo]

link:windropdown-resize-drop-down-in-windropdown.html[Resize Drop-Down in WinDropDown]

link:winpopupcontrolcontainer-resize-drop-down-in-winpopupcontrolcontainer.html[Resize Drop-Down in WinPopupControlContainer]