////

|metadata|
{
    "name": "win-whats-new-in-2007-volume-2",
    "controlName": [],
    "tags": [],
    "guid": "{1BD3772E-B017-4A37-BD10-DC5299655365}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2007 Volume 2

The Infragistics Windows Forms 2007 Volume 2 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Below is a list of the controls and components that we either added or enhanced for the 2007 Volume 2 release. Click the links to see a list of the features being offered.

* link:win-application-styling-whats-new-20072.html[Application Styling]
* link:win-excel-enhancements-whats-new-20072.html[Excel Enhancements]
* link:win-infragistics-document-engine-whats-new-20072.html[Infragistics Document Engine]
* link:win-windesktopalert-whats-new-20072.html[WinDesktopAlert]
* link:win-wingauge-whats-new-20072.html[WinGauge]
* link:win-wingridbaglayoutpanel-whats-new-20072.html[WinGridBagLayoutPanel]
* link:win-wingriddocumentexporter-whats-new-20072.html[WinGridDocumentExporter]