////

|metadata|
{
    "name": "win-whats-new-new-wincontrolcontainereditor-component",
    "controlName": [],
    "tags": [],
    "guid": "{F7A61EBB-CACE-4614-84BB-E2D4D29EC711}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T11:27:40Z"
}
|metadata|
////

= New WinControlContainerEditor Component

The new WinControlContainerEditor™ component provides an easy way to embed a custom user control within any Infragistics Windows Forms controls that support embeddable editors. Previously, it was challenging to embed a control that does not implement the  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.iprovidesembeddableeditor.html[IProvidesEmbeddableEditor]"]  interface within a control like WinGrid™, WinTree™ or WinSchedule™. But now with the new WinControlContainerEditor component, you can plug in any control more easily without worrying about the complex logic and plumbing that is associated with implementing the complex IProvidesEmbeddableEditor interface.

== Related Topics

* link:wincontrolcontainereditor-about-wincontrolcontainereditor.html[About WinControlContainerEditor]