////

|metadata|
{
    "name": "win-whats-new-wingridexcelexporter-exporting-formulas-to-excel",
    "controlName": [],
    "tags": [],
    "guid": "{6B98870C-2021-49C6-AFBA-B7F24B2A7CC7}",  
    "buildFlags": [],
    "createdOn": "2008-11-09T14:40:32Z"
}
|metadata|
////

= WinGridExcelExporter Exporting Formulas to Excel

WinGridExcelExporter™ now has the ability to export WinCalcManager™ Formulas to Excel as Excel Functions. Previously, when using WinGridExcelExporter to export WinGrid Data to Excel, any WinCalcManager calculated cells would be exported as the actual evaluated value. The calculated WinGrid columns would end up as actual values in the Excel file where modifications to Excel Worksheet cells would not cause a recalculation of the values. By exporting the WinCalcManager Formulas as Excel Functions, your end user can now make changes to the Worksheet cells and cause the values to recalculate.

WinGridExcelExporter also comes complete with  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.excelexport{ApiVersion}~infragistics.win.ultrawingrid.excelexport.ultragridexcelexporter~formulaexporting_ev.html[FormulaExporting]"]  and  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.excelexport{ApiVersion}~infragistics.win.ultrawingrid.excelexport.ultragridexcelexporter~formulaexported_ev.html[FormulaExported]"]  events which allow you to cancel certain Formulas from being exported as well as modifying or altering Formulas after they are exported. You also have a  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.excelexport{ApiVersion}~infragistics.win.ultrawingrid.excelexport.ultragridexcelexporter~formulaexporterror_ev.html[FormulaExportError]"]  event which can be used to trap and handle any errors that may occur whenever exporting Formulas to Excel.

This new feature can also be turned off by simply setting the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.excelexport{ApiVersion}~infragistics.win.ultrawingrid.excelexport.ultragridexcelexporter~exportformulas.html[ExportFormulas]"]  WinGridExcelExporter property to false.

== *Related Topics*

link:wingridexcelexporter-exporting-formulas-to-excel.html[Exporting Formulas to Excel]