////

|metadata|
{
    "name": "win-you-can-now-freeze-rows-and-columns-in-excel-worksheets-whats-new-20072",
    "controlName": [],
    "tags": [],
    "guid": "{8BB88054-181B-4C5E-A998-B555165AFCC6}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= You Can Now Freeze Rows and Columns in Excel Worksheets

A very useful feature of Microsoft® Excel® is freezing and unfreezing panes, allowing end users to always see a title row or main column. You can now freeze rows and columns by setting the  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.displayoptions~panesarefrozen.html[PanesAreFrozen]"]  property to True off the  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.displayoptions.html[DisplayOptions]"]  object and then identifying which rows or columns are frozen by setting the  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.frozenpanesettings~frozenrows.html[FrozenRows]"]  or  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.frozenpanesettings~frozencolumns.html[FrozenColumns]"]  properties off the  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.frozenpanesettings.html[FrozenPaneSettings]"]  object.

== Related Topic

link:excelengine-freeze-rows-and-columns.html[Freeze Rows and Columns]