////

|metadata|
{
    "name": "win-whats-new-calcmanager-excel-style-functions",
    "controlName": [],
    "tags": [],
    "guid": "{4835CC2D-7EED-4DDD-9681-E187BC12DD28}",  
    "buildFlags": [],
    "createdOn": "2008-11-09T14:24:21Z"
}
|metadata|
////

= CalcManager Excel - Style Functions

In this release, you can get a whole bunch of new Microsoft® Excel®-Style functions supported by the WinCalcManager™ component. With the addition of these new functions, you can gain some pretty intense calculation formulas that are readily available through the WinCalcManager, thereby saving a good amount of time from having to perform these calculations all by yourself.

Part of the Infragistics Excel object library initiative is to have direct integration of the CalcManager formulas from WinGrid to Excel. Implementing this feature is easy as having a populated WinGrid™ along with some additional calculated columns using WinCalcManager to provide the formulas and then exporting the WinGrid with WinGridExcelExporter™. The exported Excel file will contain the WinGrid data along with real Excel functions that represent the calculated WinGrid columns.

== *Related Topics*

link:wincalcmanager-date-and-time-functions.html[Date and Time Functions]

link:wincalcmanager-financial-functions.html[Financial Functions]

link:wincalcmanager-information-functions.html[Information Functions]

link:wincalcmanager-math-functions.html[Math Functions]

link:wincalcmanager-engineering-functions.html[Engineering Functions]

link:wincalcmanager-lookup-and-reference-functions.html[Lookup and Reference Functions]