////

|metadata|
{
    "name": "win-final-release-of-clr-1-x-version-of-infragistics-whats-new-20071",
    "controlName": [],
    "tags": [],
    "guid": "{39FAFE62-97EF-4858-9595-5708B30EBC44}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Final Release of CLR 1.x Version of Infragistics Professional

In the 2007 Volume 1 release, Infragistics has released new features for the Infragistics Professional product for both the CLR 1.x and CLR 2.0 versions. The 2007 Volume 1 release will be the final release that our Infragistics Professional product will be compiled against .NET Frameworks 1.0 and 1.1. Developer Support will continue to be available for the CLR 1.x version of the product, and product maintenance will be available for a full year following the release of CLR 1.x compiled bits.

Going forward, Infragistics will continue to release new features and products for Infragistics Professional, compiled natively for Microsoft® Visual Studio® 2005, .NET Framework 2.0. This will allow us to streamline our development cycles across our R&D, Quality Assurance, Developer Support, and Technical Communications teams to provide new products and features to leverage the latest technology to the fullest degree possible.