////

|metadata|
{
    "name": "win-upgrading-your-windows-forms-projects",
    "controlName": [],
    "tags": [],
    "guid": "{B75B3FA7-2086-4E52-8D7B-E348389E521D}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Upgrading Your Windows Forms Projects

A new version of the Infragistics Windows Forms toolset is released two times a year, and public service releases are released even more frequently. These releases add important functionality and ensure you are using the most stable product available. However, this also means that you may need to upgrade your existing version to the latest release. We want to make this process as painless as possible, so we offer you quick and easy ways to upgrade your existing projects.

* link:win-upgrading-a-project-to-infragistics-windows-forms-11-1-(and-above)-using-version-utility.html[Using Version Utility] -- Outlines the process of upgrading your Windows Forms projects using the easy-to-use Infragistics Project Version Upgrade Utility for version 11.1 and above.
* link:win-using-command-line.html[Using Command-Line] -- Describes the command-line arguments that you can use to run the Infragistics Project Version Utility using a command-line program.
* link:win-upgrading-a-project-manually.html[Upgrading a Project Manually] -- Explains how to manually upgrade a project by adding/removing references to/from Infragistics assemblies.

.Note
[NOTE]
====
If you are moving your solution from one version of Microsoft™ Visual Studio™ to another, the Visual Studio upgrade should be performed before using the version utility. The supported versions of Visual Studio are 2005 and above and the utility can upgrade applications that are powered by Infragistics versions 2005 and later.
====