////

|metadata|
{
    "name": "win-wincalendarcombo-using-wincalendarcombo",
    "controlName": ["WinCalendarCombo"],
    "tags": ["Getting Started","How Do I"],
    "guid": "{A8F1CF33-56CB-4296-AF2F-96367BCE76BD}",  
    "buildFlags": [],
    "createdOn": "2007-07-11T13:57:08Z"
}
|metadata|
////

= Using WinCalendarCombo

In this section, you'll find short, task-based topics that explain how to use features that apply to two or more WinCalendarCombo™ controls.

Click the links below to find out how you can...

* link:wincalendarcombo-change-the-increments-of-spin-button-elements.html[Change the Increments of Spin Button Elements]
* link:wincalendarcombo-create-additional-date-buttons.html[Create Additional Date Buttons]
* link:wincalendarcombo-create-custom-date-buttons.html[Create Custom Date Buttons]
* link:wincalendarcombo-invoke-the-drop-down-list.html[Invoke the Drop-Down List]
* link:wincalendarcombo-set-the-text-of-wincalendarcombo-when-the-date-value-is-null.html[Set the Text of WinCalendarCombo When the Date Value is Null]