////

|metadata|
{
    "name": "win-you-can-now-select-nodes-from-different-levels-in-wintree",
    "controlName": [],
    "tags": [],
    "guid": "{A854A2D8-5F7E-4525-A390-FBC3D6E078C9}",  
    "buildFlags": [],
    "createdOn": "2008-08-01T16:25:57Z"
}
|metadata|
////

= You Can Now Select Nodes from Different Levels in WinTree

In previous releases, WinTree™ only allowed you to select nodes from the same tree level simultaneously. This release, we've broken the level barrier, allowing you to select as many nodes, in as many levels of the tree as necessary. You don't need to perform any extra work in order to turn this functionality on, it just works. However, if you want to manipulate the  pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.selectednodescollection.html[SelectedNodes]"]  collection based on nodes in different levels, you'll need to sort through the collection and identify which  pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratreenode.html[Node]"]  belongs to which  pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratreenode~level.html[Level]"] .

== Related Topics

link:wintree-select-nodes-in-different-levels-of-the-tree.html[Select Nodes in Different Levels of the Tree]