////

|metadata|
{
    "name": "win-whats-new-in-2008-volume-1",
    "controlName": [],
    "tags": [],
    "guid": "{C7E01BCA-0F69-4810-BC9B-B10B0CC85078}",  
    "buildFlags": [],
    "createdOn": "2007-12-12T08:48:38Z"
}
|metadata|
////

= What's New in 2008 Volume 1

The Infragistics Windows Forms 2008 Volume 1 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Click the links to see a list of the new features being offered.

* link:win-whats-new-2008-full-support-for-visual-studio-2008.html[Full Support for Visual Studio 2008]
* link:win-new-close-button-for-wintab-and-wintabbedmdimanager.html[New Close Button for WinTab and WinTabbedMdiManager]
* link:win-new-wintrackbar-control.html[New WinTrackBar Control]
* link:wintree-whats-new-20081.html[WinTree 2008.1]
* link:win-you-can-now-fit-all-winlistview-columns-in-the-available-space.html[You Can Now Fit All WinListView Columns in the Available Space]