////

|metadata|
{
    "name": "win-whats-new-in-2006-volume-3",
    "controlName": [],
    "tags": [],
    "guid": "{23AEE47A-BBD7-41D0-93EC-24E7D13B3488}",  
    "buildFlags": [],
    "createdOn": "2006-09-08T20:57:05Z"
}
|metadata|
////

= What's New in 2006 Volume 3

The Infragistics Windows Forms 2006 Volume 3 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Below is a list of the controls and components that we either added or enhanced for the 2006 Volume 3 release. Click the links to see a list of the features being offered.

* link:win-application-styling-whats-new-20063.html[Application Styling]
* link:win-office-2007-look-and-feel-whats-new-2006-3.html[Office 2007 Look and Feel]
* link:winchart-whats-new-2006-3.html[WinChart]
* link:wincombo-whats-new-2006-3.html[WinCombo]
* link:windockmanager-whats-new-2006-3.html[WinDockManager]
* link:wineditors-whats-new-2006-3.html[WinEditors]
* link:winformattedlinklabel-whats-new-2006-3.html[WinFormattedLinkLabel]
* link:winformattedtexteditor-whats-new-2006-3.html[WinFormattedTextEditor]
* link:wingrid-whats-new-2006-3.html[WinGrid]
* link:wintoolbarsmanager-whats-new-2006-3.html[WinToolbarsManager]
* link:wintooltipmanager-whats-new-2006-3.html[WinTooltipManager]