////

|metadata|
{
    "name": "win-windatasource-using-windatasource",
    "controlName": ["WinDataSource"],
    "tags": ["Application Scenarios","How Do I"],
    "guid": "{C804438B-42D1-4932-966D-4036A78DD681}",  
    "buildFlags": [],
    "createdOn": "2007-07-11T14:03:35Z"
}
|metadata|
////

= Using WinDataSource

In this section, you'll find short, task-based topics that explain how to perform a specific task related to the WinDataSource™ component.

Click the links below to find out how you can...

* link:windatasource-load-data-on-demand.html[Load Data On-Demand]
* link:windatasource-save-and-load-windatasource-data.html[Save and Load WinDataSource Data]
* link:windatasource-sub-classing-windatasource-to-represent-a-business-class.html[Sub-Classing WinDataSource to Represent a Business Class]
* link:windatasource-use-add-and-insert-methods-with-arrays.html[Use Add and Insert Methods with Arrays]
* link:windatasource-use-windatasource-at-run-time.html[Use WinDataSource at Run Time]