////

|metadata|
{
    "name": "win-new-infragistics-document-engine-whats-new-20072",
    "controlName": [],
    "tags": [],
    "guid": "{202F9C44-D761-4816-9107-CCC9B62E7B9F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= New Infragistics Document Engine

The Infragistics Document Engine™ is a brand new code library that delivers the capability of writing entire PDF and XML Paper Specification (XPS) documents from scratch. Complete with an intuitive document object model (DOM), the Document Engine helps you write entire reports of any design. We included several graphical elements in the code library designed to help you fashion a polished report worthy of any managerial scrutiny.

=== A Natural Flow for Your Reports

The Document Engine's DOM is a five-star object model allowing you to create reports of any layout. Because the DOM is interface-driven, adding flow elements to your report, and even embedding flow elements within other flow elements is as simple as calling a method. This unique object model allows you to loop through records in a data base, adding custom layouts and even graphics based on whatever criteria you choose. It's your report, write it however you want!

=== High-Class Reports Require a High-Class Attitude

Just because you're writing a report in Visual Studio® doesn't mean it has to be technical and boring. Use several of our graphical elements to add a dash of pizzazz to your reports. Insert images such as company logos or product shots for a more personalized touch. Add shapes and lines to give definition to your report layout. Enhance either the images or shapes with brushes and colors giving depth and body to your reports. Use any font you desire as you have the option to embed them in the report itself.

=== WinGrid™ Never Looked this Good

Also new this release, the WinGridDocumentExporter™ component. WinGridDocumentExporter uses the Document Engine's DOM, making it possible to export an entire WinGrid to a brand new report, or even a new section of an existing report. WinGridDocumentExporter makes full use of the IGrid interface which is explained in detail in the Document Engine documentation. For more information, see link:wingriddocumentexporter-new-wingriddocumentexporter-component-whats-new-20072.html[New WinGridDocumentExporter Component].

== Related Topics

link:waw-infragistics-document-engine.html[Infragistics Document Engine]

link:documentengine-report-elements.html[Report Elements]

link:documentengine-report-graphics.html[Report Graphics]

link:wingriddocumentexporter.html[WinGridDocumentExporter]