////

|metadata|
{
    "name": "win-wineditor-can-now-increment-by-values-other-than-one",
    "controlName": [],
    "tags": [],
    "guid": "{1D85C8EA-FE03-45AC-A1E7-467F50179512}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinEditor Can Now Increment by Values Other than One

Using the WinEditor™ control's spin buttons, your end users can increment and decrement the associated value by one. However, this can be a tedious task if the desired change is a large number. With the new  pick:[win-forms="link:{ApiPlatform}win.ultrawineditors{ApiVersion}~infragistics.win.ultrawineditors.ultranumericeditor~spinincrement.html[SpinIncrement]"]  property, your end user can change the value by a more logical difference, such as one thousand at a time for large orders of a product, or fractions of a unit for a more precise measurement.

== Related Topics

link:winnumericeditor-incrementing-the-spin-value.html[Increment by a Constant Value]

link:winmaskededit-incrementing-the-spin-value.html[Increment WinMaskedEdit by a Constant Value]