////

|metadata|
{
    "name": "win-developers-guide",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{36F48414-36F0-4C3E-B189-452602566C27}",  
    "buildFlags": [],
    "createdOn": "2005-02-12T00:00:00Z"
}
|metadata|
////

= Developer's Guide

The Developer's Guide is exactly what the title states – a guide for you, the developer. This integral section of the help contains a wealth of important information about Infragistics Windows Forms controls and components. This section features hundreds of topics ranging from descriptions of the key features and functionalities of the controls/components to detailed, step-by-step procedures on how to use the controls/components to accomplish common tasks. The knowledge that you'll gain from the Developer's Guide section will give you the power necessary to take full advantage of our controls in order to develop professional, feature-rich UI for your Windows-based applications.

The links below are the top-level entry points into the main sections of the Developer's Guide:

== link:win-assemblies.html[Assemblies]

Each of our Windows Forms controls/components is stored in a dynamic-link library (DLL) used by the Visual Studio® .NET development system. Some assemblies contain several controls/components while others contain only one. This section maps the assemblies to the corresponding controls/components.

== link:win-presentation-layer-framework-plf.html[Presentation Layer Framework (PLF)]

A framework is a collection of .NET objects that form the foundation of a particular toolset. In our case, all of our Infragistics Windows Forms controls and components are built upon the link:win-presentation-layer-framework-plf.html[Presentation Layer Framework™ (PLF)].

== link:win-controls.html[Controls]

This is an essential section in the help, and the one that you will most likely refer to most often. This section contains information on each and every one of our Windows Forms controls and components. In this section, you'll find information to guide you on using a particular control/component.

== link:styling-guide.html[Styling Your Application]

Our Windows Forms controls and components offer a number of ways for you to define their look feel. In this section you'll learn how to set the visual styles and behaviors of the controls and components using presets, themes, link:styling-guide-application-styling-framework-asf.html[Application Styling Framework (ASF)] and appearance objects to add polished fit and finish to your applications.

== link:win-upgrading-your-windows-forms-projects.html[Upgrading Your Windows Forms Projects]

Use this section to find information on how you can upgrade your existing Windows Forms projects to the current volume release of Infragistics Windows Forms. This section offers information on how to perform the upgrade using the Infragistics Project Version Utility, using a link:win-using-command-line.html[command-line program], or link:win-upgrading-a-project-manually.html[manually upgrading your projects].

== link:win-deploying-your-application.html[Deploying Your Application]

This section discusses the various ways you can deploy applications that use one or more of our Windows Forms controls and components. It explains the various methods of deployment (i.e., link:win-using-xcopy-deployment.html[XCOPY], link:win-using-global-assembly-cache-gac-deployment.html[Global Assembly Cache (GAC)], and link:win-using-no-touch-deployment.html[No-Touch] deployment).