////

|metadata|
{
    "name": "win-whats-new-in-2006-volume-2",
    "controlName": [],
    "tags": [],
    "guid": "{0CDED09E-9B08-4441-A3D4-ADAE120F44ED}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2006 Volume 2

The Infragistics 2006 Volume 2 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Below is a list of the controls and components that we either added or enhanced for the 2006 Volume 2 release. Click the links to see a list of the features offered by each control/component.

* link:win-valuelist-object-whats-new-2006-2.html[ValueList Object]
* link:win-application-styling-whats-new-20062.html[Application Styling]
* link:win-migrating-to-2006-2-whats-new-2006-2.html[Migrating to 2006.2]
* link:win-project-upgrade-utility-whats-new-2006-2.html[Project Upgrade Utility]
* link:winchart-whats-new-2006-2.html[WinChart]
* link:winspellchecker-whats-new-20062.html[WinSpellChecker]