////

|metadata|
{
    "name": "win-you-can-now-use-formulas-in-excel-worksheets-whats-new-20072",
    "controlName": [],
    "tags": [],
    "guid": "{C76FED12-46F9-40C0-89E1-560C3BDDF2DD}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= You Can Now Use Formulas in Excel Worksheets

Formulas are excellent spreadsheet helpers that can summarize expenditures and profits, provide the mean or medium of a set of data, or provide more advanced computations such as compound interest or depreciation. The 2007 Volume 2 release gives you the advantage of adding formulas to your Microsoft® Excel® worksheets built with our Excel object model.

A successful formula requires two main ingredients:

* the cell or range of cells used to compute the formula
* a cell or group of cells in which to place the result

The  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.formula~parse.html[Parse]"]  and  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.formula~tryparse.html[TryParse]"]  methods off the  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.formula.html[Formula]"]  object handle the first ingredient – pass in the formula and cell reference mode to this method. The formula will include the cell or range of cells that are used to compute the formula. The  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.formula~applyto.html[ApplyTo]"]  method, also found off the Formula object, handles the second ingredient. It passes in the cell or cell regions you want the result of the formula to be placed in.

Formulas can be as simple or complex as needed. That's why we included a TryParse method, so you can confirm that the formula was parsed correctly before using it. You can parse any standard Excel formula (refer to your Excel documentation for more information on supported formulas).

== Related Topic

link:excelengine-calculating-order-totals.html[Calculating Order Totals]