////

|metadata|
{
    "name": "win-whats-new-wingrid-clickcell-event",
    "controlName": [],
    "tags": [],
    "guid": "{EDDE9A3E-76F9-4E93-986E-1187463D00A5}",  
    "buildFlags": [],
    "createdOn": "2008-11-09T13:50:20Z"
}
|metadata|
////

= WinGrid ClickCell Event

WinGrid™ now has a  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragrid~clickcell_ev.html[ClickCell]"]  event. Very similar to the existing  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragrid~doubleclickcell_ev.html[DoubleClickCell]"]  event, you can implement many kinds of custom logic in order to address your various scenarios. Within the ClickCell event you can easily get access to the Cell that was clicked through the event arguments so that you can access the cell value, the row that it belongs to as well as its sibling cells and their values.

== *Related Topics*

link:wingrid-clickcell-event.html[ClickCell Event]