////

|metadata|
{
    "name": "win-whats-new-in-2005-volume-3",
    "controlName": [],
    "tags": [],
    "guid": "{8BD55BBD-2B45-4A3C-93CB-EFA52DC6BCCD}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2005 Volume 3

The Infragistics 2005 Volume 3 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Below is a list of the controls that we either added or enhanced for the 2005 Volume 3 release. Click the links to see a list of the features offered by each control.

*  pick:[win-forms="link:win-visual-studio-2005-specific-features.html[Visual Studio 2005-Specific Features]"] 
* link:winchart-whats-new-2005-3.html[WinChart]
* link:windockmanager-whats-new-2005-3.html[WinDockManager]
* link:wineditors-whats-new-2005-3.html[WinEditors]
* link:wingrid-whats-new-2005-3.html[WinGrid]
* link:winschedule-whats-new-2005-3.html[WinSchedule]
* link:wintooltip-whats-new-2005-3.html[WinToolTip]
* link:wintree-whats-new-2005-3.html[WinTree]