////

|metadata|
{
    "name": "win-whats-new-new-infragistics-word-library",
    "controlName": ["Infragistics Word Library"],
    "tags": ["Exporting"],
    "guid": "d4bdb76f-cea9-4041-9032-1b60a907954e",  
    "buildFlags": [],
    "createdOn": "2011-05-13T15:01:37.4186752Z"
}
|metadata|
////

= New Infragistics Word Library

This release of Infragistics Windows Forms 2011 Volume 1 introduces the new Infragistics Word® library. The Word library enables you to create Microsoft® Word documents. This creation functionality can be implemented through both the object-model and forward-only streamer approaches. Their advantages and disadvantages are discussed in the link:word-about-infragistics-word-library.html[About Infragistics Word Library] topic.

The Word functionalities available in this release include:

* rich character formatting such as bold, italic, underline, colors
* paragraphs
* fonts
* images
* hyperlinks
* shapes
* tables
* page layout, margins, headers, footers, page break, and page numbers

You can also export data from WinGrid™ and WinFormattedTextEditor™ to Word using this new Word library. For further details, refer to the related topics below.

== Related Topics

* link:word-understanding-infragistics-word-library.html[Understanding Infragistics Word Library]
* link:word-using-the-infragistics-word-library.html[Using the Infragistics Word Library]
* link:whats-new-new-wingridwordwriter.html[New WinGridWordWriter]
* link:whats-new-new-winformattedtextwordwriter.html[New WinFormattedTextWordWriter]