////

|metadata|
{
    "name": "win-whats-new-wincomboeditor-multiselection-support-using-checkbox",
    "controlName": [],
    "tags": [],
    "guid": "{1E857B62-6CC9-4DC3-ABB1-6A933E486F01}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinComboEditor MultiSelection Support using Checkbox

The EditorWithCombo embeddable editor has now been modified to support the display of a checkbox next to each item in the dropdown list. Checking of multiple items will be supported, thus providing the ability to select more than one item at a time. Beyond the basic multi-select capability, this feature also provides support to determine whether the checkboxes are visible, where they appear with respect to the rest of the item content, and whether clicking an item automatically toggles its CheckState. The checked items can be obtained as a generic object list (i.e. List<object>).

== Related Topics

link:wincomboeditor-selecting-multiple-values-within-wincomboeditor.html[Selecting Multiple Values within WinComboEditor]