////

|metadata|
{
    "name": "win-assemblies",
    "controlName": [],
    "tags": ["API"],
    "guid": "{B867E97F-8D22-42C3-80AF-135903A39806}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Assemblies

An assembly is the core of the common language runtime (CLR). It's a collection of the types and resources required by the CLR to execute an application, and is typically stored as a single executable (.exe) or dynamic-link library (DLL). An assembly controls important aspects of an application including deployment, version control, and security permissions.

To learn about Infragistics Product assemblies, click the links below.

== link:win-windows-forms-assemblies.html[Windows Forms Assemblies]

In this topic, you'll find a list of all the Windows Forms assemblies included in the Infragistics Windows Forms product, along with their corresponding controls and components.

== link:win-adding-an-assembly-to-a-project.html[Adding an Assembly to a Project]

This topic explains how to quickly add an Infragistics Product assembly to your Visual Studio® .NET project.

== link:win-assembly-resource-strings.html[Assembly Resource Strings Reference]

This section contains topics that list all the resource strings used by each Infragistics Windows Forms assembly, along with the string's default text value.