////

|metadata|
{
    "name": "win-you-can-now-import-an-excel-file-into-an-excel-workbook-whats-new-20072",
    "controlName": [],
    "tags": [],
    "guid": "{CA797036-8F23-4098-9D73-D98E98A4A2F5}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= You Can Now Import an Excel File into an Excel Workbook

We've given you Microsoft® Excel® exporting capabilities for quite some time, but you haven't been able to load an Excel file and create a workbook from it. This all changes in the 2007 Volume 2 release.

Using the new  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~load.html[Load]"] method, you can load an Excel file directly into a  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  object. You can then manipulate that workbook however necessary, and then use the  pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Save]"]  method to save it as an Excel file again. This is extremely useful if you need to make simple and quick modifications to an Excel file. You could even potentially create a data set from the workbook and then use that data in any number of Infragistics Professional controls or components.

== Related Topic

link:excelengine-read-an-excel-file-into-a-workbook.html[Read an Excel File into a Workbook]