////

|metadata|
{
    "name": "win-export-images-from-a-style-library-whats-new-20071",
    "controlName": [],
    "tags": [],
    "guid": "{2194DEE8-3623-4D43-B5B6-F2950FEC2DE6}",  
    "buildFlags": [],
    "createdOn": "2006-11-12T15:03:35Z"
}
|metadata|
////

= Export Images from a Style Library

Styling UI Roles and Resources is at the heart of application styling. These UI Roles and Resources can have images displayed in their background, making for a highly customizable Button, Tab, or other UI element. These images, however, are embeddable in the ISL file, and not saved out as an actual image in an images folder. Once the Style Library is saved, it is difficult to modify images in different UI Roles. This restraint was even more noticeable if you were to share your Style Libraries throughout your company or in a developer community.

This release, Infragistics is offering you a way to recover all the images from any Style Library. By clicking the new Export Images... menu item on the File menu, a dialog box opens, allowing you to browse to any folder, or create a new one, to place all the Style Library images into. Keep in mind, the image exporter will only export images in Portable Network Graphics (PNG) format. This feature will definitely be a favorite of graphic designers wishing to share their work with other colleagues.

== Related Topics

link:styling-guide-exporting-images-from-a-style-library.html[Exporting Images from a Style Library]