////

|metadata|
{
    "name": "win-whats-new-in-2006-volume-1",
    "controlName": [],
    "tags": [],
    "guid": "{A92C5FA2-5127-45E9-A3A5-7C986D6D086D}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2006 Volume 1

The Infragistics 2006 Volume 1 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Below is a list of the controls and components that we either added or enhanced for the 2006 Volume 1 release. Click the links to see a list of the features offered by each control/component.

* link:win-appearance-object-whats-new-2006-1.html[Appearance Object]


* link:win-composite-ui-application-block-cab-whats-new-2006-1.html[Composite UI Application Block (CAB)]



* link:winchart-whats-new-2006-1.html[WinChart]
* link:windockmanager-whats-new-2006-1.html[WinDockManager]
* link:winformattedlinklabel-whats-new-2006-1.html[WinFormattedLinkLabel]
* link:wingrid-whats-new-2006-1.html[WinGrid]
* link:winlistview-whats-new-2006-1.html[WinListView]
* link:wintoolbarsmanager-whats-new-2006-1.html[WinToolbarsManager]