////

|metadata|
{
    "name": "win-whats-new-in-2009-volume-1",
    "controlName": [],
    "tags": [],
    "guid": "{B6425938-75E0-4F08-B227-8809414ED123}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2009 Volume 1

The Infragistics Windows Forms 2009 Volume 1 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Click the links to see a list of the new features being offered.

* link:win-whats-new-wincomboeditor-multiselection-support-using-checkbox.html[WinComboEditor MultiSelection Support using Checkbox]
* link:win-whats-new-winlistview-lassoselection.html[WinListView LassoSelection]
* link:win-whats-new-winpanel-control.html[New WinPanel Control]
* link:win-whats-new-wingrid.html[WinGrid]
* link:win-whats-new-printing-total-number-of-pages.html[WinGridPrintDocument Printing Total Number of Pages]
* link:win-whats-new-winschedule.html[WinSchedule]