////

|metadata|
{
    "name": "win-winformattedlinklabel-using-winformattedlinklabel",
    "controlName": ["WinFormattedLinkLabel"],
    "tags": ["Application Scenarios","Getting Started"],
    "guid": "{7A3A1EE3-AE03-408C-ABED-29961F6396BF}",  
    "buildFlags": [],
    "createdOn": "2007-07-11T14:21:44Z"
}
|metadata|
////

= Using WinFormattedLinkLabel

In this section, you'll find short, task-based topics that explain how to perform a specific task related to the WinFormattedLinkLabel™ control.

Click the link below to find out how you can…

* link:winformattedlinklabel-adding-a-hyperlink-to-a-cell-in-wingrid.html[Adding a Hyperlink to a Cell in WinGrid]
* link:winformattedlinklabel-adding-a-hyperlink-as-an-item-in-winexplorerbar.html[Adding a Hyperlink as an Item in WinExplorerBar]
* link:winformattedlinklabel-create-a-link-using-winformattedlinklabel.html[Create a Link Using WinFormattedLinkLabel]
* link:winformattedlinklabel-handle-an-error-while-parsing-formatted-text.html[Handle an Error While Parsing Formatted Text]
* link:formattedtexteditor-using-subscript-and-superscript.html[Using Subscript and Superscript]