////

|metadata|
{
    "name": "win-using-embeddable-editors-in-the-datagridview-whats-new-2005-3",
    "controlName": [],
    "tags": [],
    "guid": "{36D05113-832E-46DC-A85C-034E6032EBB5}",  
    "buildFlags": ["win-forms"],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Using Embeddable Editors in the DataGridView

The DataGridView control in Visual Studio 2005 (.NET Framework 2.0) can create custom derived columns. We have created derived columns which host our embeddable editors. There is a separate column class designed for each type of editor that corresponds to their existing class (derived from  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.embeddableeditorbase.html[EmbeddableEditorBase]"] ). There will be a column for every editor, but not for every editor control (for example, CurrencyEditor and NumericEditor will not have column types since they both use EditorWithMask). Add these derived columns to the grid at run-time or design-time, bound or unbound.

== Related Topics

link:wineditors-using-wineditors-in-the-datagridview-control.html[Using WinEditors in the DataGridView Control]

link:http://msdn.microsoft.com/en-us/library/system.windows.forms.datagridview(v=vs.110).aspx[DataGridView]