////

|metadata|
{
    "name": "win-whats-new-in-2005-volume-1",
    "controlName": [],
    "tags": [],
    "guid": "{F74AA051-3578-438E-A5A1-F8CD1E398F0B}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2005 Volume 1

The Infragistics 2005 Volume 1 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Below is a list of the controls that we either added or enhanced for the 2005 Volume 1 release. Click the links to see a list of the features offered by each control.

* link:wincalcmanager-whats-new-2005-1.html[WinCalcManager]
* link:winchart-whats-new-2005-1.html[WinChart]
* link:windatasource-whats-new-2005-1.html[WinDataSource]
* link:wineditors-whats-new-2005-1.html[WinEditors]
* link:wingrid-whats-new-2005-1.html[WinGrid]
* link:winmisc-whats-new-2005-1.html[WinMisc]
* link:winschedule-whats-new-2005-1.html[WinSchedule]
* link:wintoolbars-whats-new-2005-1.html[WinToolbars]
* link:infragistics-win-plf-whats-new-2005-1.html[Infragistics.Win (PLF)]