////

|metadata|
{
    "name": "win-getting-started",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{49AA7B68-C9C7-47AA-A56A-6FB34D139C83}",  
    "buildFlags": [],
    "createdOn": "2005-07-06T00:00:00Z"
}
|metadata|
////

= Getting Started

In order to get you up and running quickly with the Infragistics Windows Forms product, we've provided you with this Getting Started section. Before you start using Infragistics Windows Forms, be sure to read through the topics in this section to ensure that you are getting the most out of the product.

== link:introduction-installing-infragistics-windows-forms.html[Installing Infragistics Windows Forms]

This section, guides you through the installation process and also provides you with some tips on installing Infragistics Windows Forms.

== link:introduction-getting-support.html[Getting Support]

This topic provides useful information such as how to get technical support, create an Infragistics member profile, and register your product key.