////

|metadata|
{
    "name": "win-you-can-now-print-wingrid-in-cardview",
    "controlName": [],
    "tags": [],
    "guid": "{6EAF48FE-BAFA-4351-A690-9F5CCE2089A8}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= You Can Now Print WinGrid in CardView

Previously, you were only able to print WinGrid™ in tabular format; meaning, WinGrid would print out rows of data despite a band being in  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridband~cardview.html[CardView]"] . However, we've now added the functionality for WinGrid to print out the grid while in CardView mode. To enable this feature, all that's required is to set the new  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridlayout~allowcardprinting.html[AllowCardPrinting]"]  property to RootBandOnly (and, of course, a band's CardView property to True).

All of the CardView Style options are honored. The  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcardsettings~maxcardareacols.html[MaxCardAreaCols]"]  and  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcardsettings~maxcardarearows.html[MaxCardAreaRows]"]  properties determine how many cards per page, while the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcardsettings~autofit.html[AutoFit]"]  property will automatically stretch each card if they don't take up the full space available on the page. We also added a new CompressedCardExpansionState value to the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.rowpropertycategories.html[RowPropertyCategories]"]  enumeration which allows you to print cards while they are collapsed.

== Related Topics

link:wingrid-printing-wingrid-in-card-view.html[Printing WinGrid in Card View]