////

|metadata|
{
    "name": "win-whats-new-in-2008-volume-3",
    "controlName": [],
    "tags": [],
    "guid": "{616A19C3-4818-4851-B988-324420BE3EB2}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2008 Volume 3

The Infragistics Windows Forms 2008 Volume 3 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Click the links to see a list of the new features being offered.

* link:win-whats-new-calcmanager-excel-style-functions.html[CalcManager Excel - Style Functions]
* link:formula-values-from-an-excel-file.html[Formula Values from an Excel File]
* link:win-whats-new-support-for-excel-workbooks-with-vba-code(xlsm-format).html[Support for Excel Workbooks with VBA code(XLSM Format)]
* link:win-whats-new-wingrid-clickcell-event.html[WinGrid ClickCell Event]
* link:win-whats-new-wingridexcelexporter-exporting-formulas-to-excel.html[WinGridExcelExporter Exporting Formulas to Excel]
* link:win-whats-new-xlsx-format.html[XLSX format]