////

|metadata|
{
    "name": "win-whats-new-in-2007-volume-3",
    "controlName": [],
    "tags": [],
    "guid": "{6DD3CFCD-722B-49DE-B569-E5A4A722A5DC}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= What's New in 2007 Volume 3

The Infragistics Windows Forms 2007 Volume 3 release includes a number of powerful new features and functionalities to allow you to take even more advantage of our Windows Forms controls and components.

Below is a list of the controls and components that we either added or enhanced for the 2007 Volume 3 release. Click the links to see a list of the features being offered.

* link:win-new-winnavigationbar-control-whats-new-20073.html[New WinNavigationBar Control]
* link:win-plf-and-wingrid-performance-improvements-whats-new-20073.html[PLF and WinGrid Performance Improvements]
* link:win-winchart-whats-new-20073.html[WinChart]
* link:win-wingauges-new-relativebounds-designer-editor.html[WinGauge's New RelativeBounds Designer Editor]
* link:win-wintoolbarsmanager-whats-new-20073.html[WinToolbarsManager]