////

|metadata|
{
    "name": "win-whats-new-winschedule",
    "controlName": [],
    "tags": [],
    "guid": "{AC62060D-CDD5-4AAC-A0AD-55A221465337}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinSchedule

===== WinSchedule Appointment Dragging and Resizing Events

With this release, four new events:  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.controlwithactivitybase~appointmentsdragging_ev.html[AppointmentsDragging]"] ,  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.controlwithactivitybase~appointmentsdragdrop_ev.html[AppointmentsDragDrop]"] ,  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.controlwithactivitybase~appointmentresizing_ev.html[AppointmentResizing]"] , and  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.controlwithactivitybase~appointmentresized_ev.html[AppointmentResized]"]  have been added for the UltraDayView, UltraWeekView, and UltraMonthViewSingle controls to implement enhanced appointment dragging and resizing support.

Also, it is now possible to prevent dragging appointment(s) from one owner to another, prevent creating copies of appointments, and also cancel these events during any phase.

===== WinSchedule DateSettings

With the new WinSchedule™  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.ownerdatesettings.html[DateSettings]"]  feature, you will now be able to define the  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.timeslotsettings~workinghours.html[working/non-working hours]"]  and its  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.owner~workinghourtimeslotappearance.html[Appearance]"]  objects for a particular Date rather than a Day of Week as displayed for each Owner object.

This new feature provides the ability to set the color for an individual TimeSlot on a per-Owner, per date basis. Also multiple non-contiguous time ranges can be assigned as working or non-working hours for a particular owner.

Additionally, all the above mentioned functionality with respect to a particular Date is also extended to the  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.dayofweeksettings.html[DayOfWeekSettings]"]  object.

== Related Topics

* link:winschedule-appointment-dragging-and-resizing-enhancements.html[Appointment Dragging and Resizing Enhancements]
* link:winschedule-setting-date-specific-non-contiguous-working-hours-for-different-owners.html[Setting Date specific non-contiguous working hours for different Owners]
* link:winschedule-order-of-precedence-for-datesettings,-recurringdatesettings,-and-dayofweeksettings.html[WinSchedule Order of precedence for DateSettings, RecurringDateSettings and DayofWeekSettings]