////

|metadata|
{
    "name": "winactivityindicator",
    "controlName": ["WinActivityIndicator"],
    "tags": [],
    "guid": "{683913E9-57CF-4199-9651-A2906F0FB274}",  
    "buildFlags": [],
    "createdOn": "2010-01-02T13:21:37Z"
}
|metadata|
////

= WinActivityIndicator

If you're looking for an area that houses all of the overview/task-based information related to the WinActivityIndicator™ control, you've come to the right place. This section contains valuable information about WinActivityIndicator, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinActivityIndicator control

== link:winactivityindicator-understanding-winactivityindicator.html[Understanding WinActivityIndicator]

In this section you'll find any information that will help you to better understand the functionalities of the WinActivityIndicator control, as well as why you would want to use it to as part of building your applications.

== link:winactivityindicator-using-winactivityindicator.html[Using WinActivityIndicator]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinActivityIndicator control.

== link:winactivityindicator-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinActivityIndicator control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.