////

|metadata|
{
    "name": "winactivityindicator-understanding-winactivityindicator",
    "controlName": ["WinActivityIndicator"],
    "tags": [],
    "guid": "{943BDB90-9848-4AE5-B9EF-307711598EB0}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Understanding WinActivityIndicator

This is a great place for you to start learning about the WinActivityIndicator™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinActivityIndicator in your applications.

Click the links below to gain an overview of the WinActivityIndicator control.

* link:winactivityindicator-about-winactivityindicator.html[About WinActivityIndicator] -- Introduces you to the WinActivityIndicator control.
* link:winactivityindicator-winactivityindicator-smart-tag.html[WinActivityIndicator Smart Tag] -- Describes the properties and settings that are displayed in the WinActivityIndicator control's Smart Tag.