////

|metadata|
{
    "name": "winactivityindicator-about-winactivityindicator",
    "controlName": ["WinActivityIndicator"],
    "tags": ["Getting Started","Performance"],
    "guid": "{A50975EC-6022-447F-84D2-45861B3DFB52}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= About WinActivityIndicator

In application development, you might occasionally require a way to inform your end users that a process is occurring behind the scenes. The WinActivityIndicator™ serves this purpose, using continuous animation to indicate that something is happening. This increases the level of interactivity that you can bring to your end users.

The WinActivityIndicator is a lightweight, standalone control that can easily be customized and styled using Appearance objects and AppStyling.

Following are the key features of WinActivityIndicator:

* Can be styled with different colors and gradients.
* Marquee-style animation.
* Can have continuous (one direction) or bounce-back animations.
* Animation speed can be modified.

== Related Topics

* link:winactivityindicator-winactivityindicator-smart-tag.html[Smart Tag]
* link:winactivityindicator-using-winactivityindicator.html[Using WinActivityIndicator]