////

|metadata|
{
    "name": "wincalcmanager-understanding-wincalcmanager",
    "controlName": ["WinCalcManager"],
    "tags": ["Getting Started"],
    "guid": "{0CEE6B57-A0E5-44E7-888D-692116FF02A7}",  
    "buildFlags": [],
    "createdOn": "2005-08-12T00:00:00Z"
}
|metadata|
////

= Understanding WinCalcManager

This is a great place for you to start learning about the WinCalcManager™ component, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinCalcManager in your applications.

Click the links below to gain an overview of the WinCalcManager component.

* link:wincalcmanager-about-wincalcmanager.html[About WinCalcManager] -- Introduces you to the WinCalcManager component.
* link:wincalcmanager-smart-tag.html[WinCalcManager Smart Tag] -- Describes the properties and settings that are displayed in the WinCalcManager component's Smart Tag.
* link:wincalcmanager-excel-style-functions.html[Excel®-Style Functions] -- Contains a list of topics listing the different types of Excel-style functions provided by the WinCalcManager component.