////

|metadata|
{
    "name": "wincheckeditor",
    "controlName": ["WinCheckEditor"],
    "tags": [],
    "guid": "{780F063B-12B0-4D7F-9F07-689FED6AC57B}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinCheckEditor

If you're looking for an area that houses all of the overview/task-based information related to the WinCheckEditor control, you've come to the right place. This section contains valuable information about WinCheckEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinCheckEditor™ control.

== link:wincheckeditor-understanding-wincheckeditor.html[Understanding WinCheckEditor]

In this section you'll find any information that will help you to better understand the functionalities of the WinCheckEditor control, as well as why you would want to use it to as part of building your applications.

== link:wincheckeditor-using-wincheckeditor.html[Using WinCheckEditor]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinCheckEditor control.

== link:wincheckeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinCheckEditor control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.