////

|metadata|
{
    "name": "wincalculatordropdown-about-wincalculatordropdown",
    "controlName": ["WinCalculatorDropDown"],
    "tags": [],
    "guid": "{73C9F0CE-B3BD-4501-8F07-AA5B7D50C7DD}",  
    "buildFlags": [],
    "createdOn": "2005-08-12T00:00:00Z"
}
|metadata|
////

= About WinCalculatorDropDown

The WinCalculatorDropDown™ control provides a drop-down customizable calculator with the following features:

* Appearance support -- Full Appearance support including alpha-blending, gradients, image, etc.
* Built-in Theming -- Supports Standard, Office 2000, Office XP, Office 2003, Visual Studio 2005, and Office 2007 themes.
* Ink-enabled -- The user can switch between freeform ink input and virtual keyboard input.
* OverflOw Indicator -- A customizable text overflow indicator image with tooltip support for the full text.
* Null Text -- Display a custom string when the control's current value is null.
* Customizable Actions -- Calculator button events and custom calculator buttons permit developer-specified calculations to fit business rules.