////

|metadata|
{
    "name": "wincombo-you-can-now-prevent-data-from-loading-until-the-dropdown-is-clicked-whats-new-20063",
    "controlName": [],
    "tags": [],
    "guid": "{A758C619-F2E5-4E91-A8A5-7C880718D4A4}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= You Can Now Prevent Data from Loading Until the Dropdown is Clicked

In previous releases, the WinCombo™ control would load its data when either its DataSource was set or when finished its initialization process. Now, you can prevent that from happening by invoking the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultracombo~setinitialvalue.html[SetInitialValue]"]  method. SetInitialValue takes in two parameters:

* dataValue -- The actual value of the WinCombo control.
* displayText -- What will be displayed in the textbox portion of WinCombo.

You can invoke the SetInitialValue method in your FormLoad event. Be sure to invoke the method before you set the DataSource, otherwise, the data will load when the DataSource is set.