////

|metadata|
{
    "name": "winchart-extended-the-swap-rows-and-columns-feature-whats-new-2006-2",
    "controlName": [],
    "tags": [],
    "guid": "{CAFC0DA3-71A5-41C2-A370-7836A801C490}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Extended the Swap Rows and Columns Feature

Until now, the ability to swap row and column data (i.e., rows of a data table becoming columns, and columns of the data table becoming rows) was available only to charts bound to a data table via the default data binding mechanism.

Starting in the 2006 Volume 2 release, you can now swap row and column data for composite and non-composite charts that are bound to series data objects. Enabling a simple property ( pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~swaprowsandcolumns.html[SwapRowsAndColumns]"] ) can save you from the manual effort of having to shape your chart data to suit your needs.

== Related Topics

link:chart-swap-rows-and-columns.html[Swap Rows and Columns]

link:chart-series-collection.html[Series Collection]

link:chart-composite-chart.html[Composite Chart]