////

|metadata|
{
    "name": "winchart-easier-to-hide-and-display-chart-series-whats-new-2006-3",
    "controlName": [],
    "tags": ["Charting"],
    "guid": "{3D26F1B2-37E5-4F01-BFF2-727BF814DF7F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Easier to Hide and Display Chart Series

In the 2006 Volume 3 release, we've improved the WinChart™ control to make it easy for you to hide or display a series in a Composite or non-composite chart. Previously, to show or hide a series, you needed to add/remove the series from the  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.compositechartappearance~series.html[Series]"]  collection. In 2006 Volume 3, we've added a new  pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data.series.seriesbase~visible.html[Visible]"]  property to the Series object.

This convenient feature is a time-saver, as it allows you to specify whether you want to hide or display the series by the simple setting of a property, rather than having to add/remove the series from the Series collection.

== Related Topic

link:chart-control-the-visibility-of-a-specific-series.html[Control the Visibility of a Specific Series]