////

|metadata|
{
    "name": "wincomboeditor-resize-drop-down-in-wincomboeditor",
    "controlName": ["WinComboEditor"],
    "tags": ["How Do I","Tips and Tricks"],
    "guid": "c279004e-45fb-4838-9e84-0c8b70428141",  
    "buildFlags": [],
    "createdOn": "2010-06-03T20:52:57.1199371Z"
}
|metadata|
////

= Resize Drop-Down in WinComboEditor

The drop-down of WinComboEditor™ control can be resized using a handle, which can be positioned at the bottom of the drop-down either vertically or diagonally. This handle enables you to resize the dropdown and view any text or item in the drop-down that has been truncated due to the size of the control. By default the DropDownResizeHandleStyle property is set to ‘None’. When set to a particular style and resized at run time, the resized height and width of the drop-down will be stored for that run of the application. You can also style the handle using the link:{ApiPlatform}win{ApiVersion}~infragistics.win.valuelist~dropdownresizehandleappearance.html[DropDownResizeHandleAppearance] property.

The following code assumes that you have an UltraComboEditor control dropped onto your form and bound to some data.

*In Visual Basic:*

----
' Set the Drop Down Resize handle style for UltraComboEditor 
Me.ultraComboEditor1.ValueList.DropDownResizeHandleStyle = Infragistics.Win.DropDownResizeHandleStyle.DiagonalResize 
' Set the back color for the handle 
Me.ultraComboEditor1.ValueList.DropDownResizeHandleAppearance.BackColor = Color.Blue
----

*In C#:*

----
// Set the Drop Down Resize handle style for UltraComboEditor
this.ultraComboEditor1.ValueList.DropDownResizeHandleStyle = Infragistics.Win.DropDownResizeHandleStyle.DiagonalResize;
// Set the back color for the handle
this.ultraComboEditor1.ValueList.DropDownResizeHandleAppearance.BackColor = Color.Blue;
----