////

|metadata|
{
    "name": "wincontrolcontainereditor-using-wincontrolcontainereditor",
    "controlName": ["WinControlContainerEditor"],
    "tags": ["Getting Started"],
    "guid": "{BF83C6AB-5855-459E-AFA1-B10AF3BABC6F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Using WinControlContainerEditor

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by the WinControlContainerEditor™ component.

* link:wincontrolcontainereditor-embed-any-control-within-wingrid-cell-using-ultracontrolcontainereditor-component.html[Embed Any Control within WinGrid cell using UltraControlContainerEditor Component]
* link:wincontrolcontainereditor-embed-any-control-within-wingrid-cell-using-controlcontainereditor-object.html[Embed Any Control within WinGrid cell using ControlContainerEditor Object]
* link:wincontrolcontainereditor-embed-different-editors-within-wingrid-cells-of-the-same-column.html[Embed Different Editors within WinGrid cells of the Same Column]