////
|metadata|
{
    "name": "wincarousel-events",
    "controlName": [],
    "tags": [],
    "guid": "175e4576-0e4f-48f4-b788-950ebf8ad2b2",
    "buildFlags": [],
    "createdOn": "2014-09-12T21:04:50.5114841Z"
}
|metadata|
////

= WinCarousel Events

This topic provides an overview of the link:{ApiPlatform}win.ultrawincarousel{ApiVersion}~infragistics.win.ultrawincarousel.ultracarousel_members.html[UltraCarousel] control’s commonly used events.

== Events Summary

[options="header", cols="a,a"]
|====
|Event Name|Description

|AnimationCompleted

|This event is triggered after the carousel items stop scrolling or rotating along the path.

.Note
[NOTE]
====
If the link:{ApiPlatform}win.ultrawincarousel{ApiVersion}~infragistics.win.ultrawincarousel.ultracarousel~animationstarting_ev.html[AnimationStarting] event is cancelled, this event will not be raised.
====

|AnimationStarting

|This event is triggered before the carousel items start scrolling or rotating along the path.

|DataItemsCollectionPopulated

|This event is triggered when the carousel items have been populated through data binding, in which the  _UltraCarousel_   is bound to a `DataSet` object.

|DataItemsCollectionPopulating

|This event is triggered while the carousel items are being populated through data binding, in which the  _UltraCarousel_   is bound to a `DataSet` object.

|InitializeDataItem

|This event is triggered when the carousel items are created through data binding of the  _UltraCarousel_   to a `DataSet` object.

.Note
[NOTE]
====
Adding items to the control will not trigger this event.
====

|ItemActivated

|This event is triggered when the active carousel item has changed. Any item at any point can be active when clicked.

.Note
[NOTE]
====
If the link:{ApiPlatform}win.ultrawincarousel{ApiVersion}~infragistics.win.ultrawincarousel.ultracarousel~itemactivating_ev.html[ItemActivating] event is cancelled, this event will not be raised.
====

|ItemActivating

|This event is triggered before the active carousel item has changed, which takes place before the items are rotated along the path.

|ItemClick

|This event is triggered when a carousel item is clicked.

.Note
[NOTE]
====
This event is only triggered when the control’s link:{ApiPlatform}win.ultrawincarousel{ApiVersion}~infragistics.win.ultrawincarousel.ultracarousel~selectiontype.html[SelectionType] is set to  _None_   (Other options are:  _Extended_   and  _Single_  ), otherwise the `ItemSelectionChanging` and `ItemSelectionChanged` events are triggered.
====

|ItemSelectionChanged

|This event is triggered when item selection has changed.

.Note
[NOTE]
====
If the link:{ApiPlatform}win.ultrawincarousel{ApiVersion}~infragistics.win.ultrawincarousel.ultracarousel~itemselectionchanging_ev.html[ItemSelectionChanging] event is cancelled, this event will not be raised.
====

|ItemSelectionChanging

|This event is triggered before item selection has changed through user interaction.

.Note
[NOTE]
====
This event is only triggered when the control’s link:{ApiPlatform}win.ultrawincarousel{ApiVersion}~infragistics.win.ultrawincarousel.ultracarousel~selectiontype.html[SelectionType] is set to  _Single_   or  _Extended_  .
====
|====


== Related Content

* link:wincarousel.html[WinCarousel] -- This section contains help topics covering the WinCarousel control.