////

|metadata|
{
    "name": "wincomboeditor",
    "controlName": ["WinComboEditor"],
    "tags": ["API","Getting Started","How Do I"],
    "guid": "{E035722E-BE2B-47A7-AAED-BEF19217AB35}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinComboEditor

If you're looking for an area that houses all of the overview/task-based information related to the WinComboEditor control, you've come to the right place. This section contains valuable information about WinComboEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinComboEditor™ control.

== link:wincomboeditor-understanding-wincomboeditor.html[Understanding WinComboEditor]

In this section you'll find any information that will help you to better understand the functionalities of the WinComboEditor control, as well as why you would want to use it to as part of building your applications.

== link:wincomboeditor-using-wincomboeditor.html[Using WinComboEditor]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinComboEditor control.

== link:wincomboeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinComboEditor control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.