////

|metadata|
{
    "name": "wincontrolcontainereditor-understanding-wincontrolcontainereditor",
    "controlName": ["WinControlContainerEditor"],
    "tags": ["Getting Started"],
    "guid": "{BE1C40A9-E1AB-43A3-B9A9-A458AB549B7E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Understanding WinControlContainerEditor

This is a great place for you to start learning about the WinControlContainerEditor™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinControlContainerEditorin your applications.

Click the links below to gain an overview of the WinControlContainerEditorcontrol.

* link:wincontrolcontainereditor-about-wincontrolcontainereditor.html[About WinControlContainerEditor] -- Introduces you to the WinControlContainerEditor control.
* link:wincontrolcontainereditor-overview-of-controlcontainereditor-object.html[Overview of ControlContainerEditor Object] -- Provides an Overview of ControlContainerEditor Object.
* link:wincontrolcontainereditor-wincontrolcontainereditor-embed-editing-or-rendering-control-within-wingrid-cell-using-controlcontainereditor-component-smart-tag.html[WinControlContainerEditor Smart Tag] -- Describes the properties and settings that are displayed in the WinControlContainerEditor control's Smart Tag.