////

|metadata|
{
    "name": "wincalcmanager",
    "controlName": ["WinCalcManager"],
    "tags": ["Extending"],
    "guid": "{DE23BAF1-90B2-4168-A62C-4302FE3FC695}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinCalcManager

If you're looking for an area that houses all of the overview/task-based information related to the WinCalcManager™ component, you've come to the right place. This section contains valuable information about WinCalcManager, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

== link:wincalcmanager-understanding-wincalcmanager.html[Understanding WinCalcManager]

In this section you'll find any information that will help you to better understand the functionalities of the WinCalcManager component, as well as why you would want to use it to as part of building your applications.

== link:win-wincalcmanager-using-wincalcmanager.html[Using WinCalcManager]

This section contains detailed, step-by-step procedures that guide you through common scenarios that you may need to perform when using the WinCalcManager component.

== link:wincalcmanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinCalcManager component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.