////

|metadata|
{
    "name": "wincontrolcontainereditor",
    "controlName": ["WinControlContainerEditor"],
    "tags": ["Getting Started"],
    "guid": "{1E9913B6-D801-4F66-BA28-269F4544D278}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinControlContainerEditor

If you're looking for an area that houses all of the overview/task-based information related to the WinControlContainerEditor control, you've come to the right place. This section contains valuable information about WinControlContainerEditor , ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinControlContainerEditor™ control.

== link:wincontrolcontainereditor-understanding-wincontrolcontainereditor.html[Understanding WinControlContainerEditor]

In this section you'll find any information that will help you to better understand the functionalities of the WinControlContainerEditor control, as well as why you would want to use it to as part of building your applications.

== link:wincontrolcontainereditor-using-wincontrolcontainereditor.html[Using WinControlContainerEditor]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinControlContainerEditor control.

== link:wincontrolcontainereditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinControlContainerEditor control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.