////

|metadata|
{
    "name": "wincombo",
    "controlName": ["WinCombo"],
    "tags": [],
    "guid": "{5E343684-AA23-4038-9D5E-8273C3589034}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinCombo

If you're looking for an area that houses all of the overview/task-based information related to the WinCombo control, you've come to the right place. This section contains valuable information about WinCombo, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinCombo™ control.

== link:wincombo-understanding-wincombo.html[Understanding WinCombo]

In this section you'll find any information that will help you to better understand the functionalities of the WinCombo control, as well as why you would want to use it to as part of building your applications.

== link:wincombo-using-wincombo.html[Using WinCombo]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinCombo control.

== link:wincombo-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinCombo control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.