////

|metadata|
{
    "name": "windockmanager",
    "controlName": ["WinDockManager"],
    "tags": [],
    "guid": "{B8FD6A58-FEE1-439A-8281-18BCE2A5E13E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinDockManager

If you're looking for an area that houses all of the overview/task-based information related to the WinDockManager™ component, you've come to the right place. This section contains valuable information about WinDockManager, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinDockManager component.

== link:windockmanager-understanding-windockmanager.html[Understanding WinDockManager]

In this section you'll find any information that will help you to better understand the functionalities of the WinDockManager component, as well as why you would want to use it to as part of building your applications.

== link:windockmanager-getting-started-with-windockmanager.html[Getting Started with WinDockManager]

In order to get you up and running as quickly as possible with the WinDockManager component, we've provided you with information on how to get started using the component (e.g., adding WinDockManager to a form).

== link:win-windockmanager-using-windockmanager.html[Using WinDockManger]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinDockManager component.

== link:windockmanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinDockManager component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.