////

|metadata|
{
    "name": "windesktopalert",
    "controlName": ["WinDesktopAlert"],
    "tags": [],
    "guid": "{86CD14B3-822F-4C19-A26F-F8E3177BB595}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinDesktopAlert

If you're looking for an area that houses all of the overview/task-based information related to the WinDesktopAlert™ component, you've come to the right place. This section contains valuable information about WinDesktopAlert, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinDesktopAlert component.

== link:windesktopalert-understanding-windesktopalert.html[Understanding WinDesktopAlert]

In this section you'll find any information that will help you to better understand the functionalities of the WinDesktopAlert component, as well as why you would want to use it to as part of building your applications.

== link:win-windesktopalert-using-windesktopalert.html[Using WinDesktopAlert]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinDesktopAlert component.

== link:windesktopalert-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinDesktopAlert component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.