////

|metadata|
{
    "name": "windockmanager-new-panedisplayed-and-panehidden-events-whats-new-20063",
    "controlName": [],
    "tags": [],
    "guid": "{26BF060B-D3F4-46CE-83B8-FD257EED4F5C}",  
    "buildFlags": [],
    "createdOn": "2006-10-10T12:39:34Z"
}
|metadata|
////

= New PaneDisplayed and PaneHidden Events

WinDockManager™ is the recipient of two very useful events this release; the  pick:[win-forms="link:{ApiPlatform}win.ultrawindock{ApiVersion}~infragistics.win.ultrawindock.ultradockmanager~panedisplayed_ev.html[PaneDisplayed]"]  and  pick:[win-forms="link:{ApiPlatform}win.ultrawindock{ApiVersion}~infragistics.win.ultrawindock.ultradockmanager~panehidden_ev.html[PaneHidden]"]  events. The PaneDisplayed event occurs whenever a pane is brought into view, whereas the PaneHidden event occurs whenever a pane is taken out of view. One notable advantage that these events bring is that if you know a pane cannot be seen by the end user, you can stop updating that pane until it is brought back into view.

Along with these two events come the OnPaneDisplayed and OnPaneHidden methods. You will find these methods off a  pick:[win-forms="link:{ApiPlatform}win.ultrawindock{ApiVersion}~infragistics.win.ultrawindock.dockablecontrolpane.html[DockableControlPane]"]  object. Once invoked, the OnPaneDisplayed and OnPaneHidden methods fire the PaneDisplayed and PaneHidden events, respectively.

One more addition is the  pick:[win-forms="link:{ApiPlatform}win.ultrawindock{ApiVersion}~infragistics.win.ultrawindock.dockablecontrolpane~isinview.html[IsInView]"]  property off the DockableControlPane object. This property identifies whether or not the end user can see the pane in question.