////

|metadata|
{
    "name": "windatasource",
    "controlName": ["WinDataSource"],
    "tags": ["Getting Started"],
    "guid": "{728D9274-99A2-457F-8AF0-0D9037B4D1A4}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinDataSource

If you're looking for an area that houses all of the overview/task-based information related to the WinDataSource™ component, you've come to the right place. This section contains valuable information about WinDataSource, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinDataSource component.

== link:windatasource-understanding-windatasource.html[Understanding WinDataSource]

In this section you'll find any information that will help you to better understand the functionalities of the WinDataSource component, as well as why you would want to use it to as part of building your applications.

== link:windatasource-getting-started-with-windatasource.html[Getting Started with WinDataSource]

In order to get you up and running as quickly as possible with the WinDataSource component, we've provided you with information on how to get started using the component (e.g., using the WinDataSource designer).

== link:win-windatasource-using-windatasource.html[Using WinDataSource]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinDataSource component.

== link:windatasource-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinDataSource component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.