////

|metadata|
{
    "name": "windesktopalert-api-overview",
    "controlName": ["WinDesktopAlert"],
    "tags": ["API"],
    "guid": "{7E0B6E02-8B12-48AD-866C-646D95DFEF3F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the component. We also give you several key classes that you will be using while programming with this control. The namespaces and classes on this page link directly into our API documentation.

=== Misc Namespace:

link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc_namespace.html[Infragistics4.Win.Misc Namespace]

=== Key Classes:

pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultradesktopalert.html[UltraDesktopAlert]"]

pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultradesktopalertbutton.html[UltraDesktopAlertButton]"]


link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultradesktopalertshowwindowinfo.html[UltraDesktopAlertShowWindowInfo]
