////

|metadata|
{
    "name": "windockmanager-show-or-hide-the-preview-in-the-navigator",
    "controlName": ["WinDockManager"],
    "tags": ["Layouts"],
    "guid": "{49125503-D685-4617-BA86-58EC78DBBBF5}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Show or Hide the Preview in the Navigator

You can display the WinDockManager™ control's Navigator in three different styles by setting the link:{ApiPlatform}win.ultrawindock{ApiVersion}~infragistics.win.ultrawindock.navigatorsettings~navigatorstyle.html[NavigatorStyle] property. Both the Visual Studio 2008 Windows® XP and Vista™ styles include a preview area of the selected window. However, by default, the Visual Studio 2005 style does not include a preview area. You can still display the preview area in the Visual Studio 2005 style by simply setting the link:{ApiPlatform}win.ultrawindock{ApiVersion}~infragistics.win.ultrawindock.navigatorsettings~ispreviewvisible.html[IsPreviewVisible] property to True. You can also hide the preview area in both the Visual Studio 2008 styles by setting the IsPreviewVisible property to False.

The following example code displays the preview area while in the Visual Studio 2005 style by setting the IsPreviewVisible property to True.

*In Visual Basic:*

----
Me.UltraDockManager1.NavigatorSettings.IsPreviewVisible = _
	Infragistics.Win.DefaultableBoolean.True
----

*In C#:*

----
this.ultraDockManager1.NavigatorSettings.IsPreviewVisible = 
	Infragistics.Win.DefaultableBoolean.True;
----