////

|metadata|
{
    "name": "winexplorerbar-change-the-size-of-the-navigation-pane-flyout",
    "controlName": ["WinExplorerBar"],
    "tags": ["How Do I","Styling"],
    "guid": "{BE1FA079-81D0-4DF6-85B1-190463376A58}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Change the Size of the Navigation Pane Flyout

When the end user clicks the collapsed group, the Navigation Pane flyout opens to a default size and position. However, this default size may be too big or too small for your application's needs. Keep in mind that there is a minimum and maximum size for the Navigation Pane flyout. If you want the flyout to be smaller than the minimum or larger than the maximum, you need to change the  pick:[win-forms="link:{ApiPlatform}win.ultrawinexplorerbar{ApiVersion}~infragistics.win.ultrawinexplorerbar.ultraexplorerbar~navigationpaneflyoutminimumsize.html[NavigationPaneFlyoutMinimumSize]"]  and  pick:[win-forms="link:{ApiPlatform}win.ultrawinexplorerbar{ApiVersion}~infragistics.win.ultrawinexplorerbar.ultraexplorerbar~navigationpaneflyoutmaximumsize.html[NavigationPaneFlyoutMaximumSize]"]  properties.

By default, the minimum width is determined by the width of the WinExplorerBar™ control and the minimum height is determined by the height of the group when it is situated on WinExplorerBar in expanded mode. The default maximum width and height are only restricted by the size available on the end user's desktop.

The following code first sets the minimum size of the Navigation Pane flyout in the form's Load event. The  pick:[win-forms="link:{ApiPlatform}win.ultrawinexplorerbar{ApiVersion}~infragistics.win.ultrawinexplorerbar.navigationpaneflyoutdisplayingeventargs~preferredsize.html[PreferredSize]"]  is then changed to 75 pixels wide by 150 pixels high in the  pick:[win-forms="link:{ApiPlatform}win.ultrawinexplorerbar{ApiVersion}~infragistics.win.ultrawinexplorerbar.ultraexplorerbar~navigationpaneflyoutdisplaying_ev.html[NavigationPaneFlyoutDisplaying]"]  event. This event fires whenever the flyout is about to be displayed, whether it is a result of the end user clicking the group area or a result of the  pick:[win-forms="link:{ApiPlatform}win.ultrawinexplorerbar{ApiVersion}~infragistics.win.ultrawinexplorerbar.ultraexplorerbar~shownavigationpaneflyout.html[ShowNavigationPaneFlyout]"]  method being invoked.

*In Visual Basic:*

----
Private Sub Change_the_Size_of_the_Navigation_Pane_Flyout_Load( _
  ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
	Me.UltraExplorerBar1.NavigationPaneFlyoutMinimumSize = _
	  New System.Drawing.Size(10, 10)
End Sub
Private Sub UltraExplorerBar1_NavigationPaneFlyoutDisplaying( _
  ByVal sender As System.Object, _
  ByVal e As Infragistics.Win.UltraWinExplorerBar.NavigationPaneFlyoutDisplayingEventArgs) _
  Handles UltraExplorerBar1.NavigationPaneFlyoutDisplaying
	e.PreferredSize = New System.Drawing.Size(75, 150)
End Sub
----

*In C#:*

----
private void Change_the_Size_of_the_Navigation_Pane_Load(object sender, EventArgs e)
{
	this.ultraExplorerBar1.NavigationPaneFlyoutMinimumSize =
	  new System.Drawing.Size(10,10);
}
private void ultraExplorerBar1_NavigationPaneFlyoutDisplaying(object sender,
  Infragistics.Win.UltraWinExplorerBar.NavigationPaneFlyoutDisplayingEventArgs e)
{
	e.PreferredSize = new System.Drawing.Size(75,150);
}
----