////

|metadata|
{
    "name": "winexplorerbar",
    "controlName": ["WinExplorerBar"],
    "tags": ["Getting Started"],
    "guid": "{B2529EC1-2336-4DA4-9E43-905698C9EA3E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinExplorerBar

If you're looking for an area that houses all of the overview/task-based information related to the WinExplorerBar™ control, you've come to the right place. This section contains valuable information about WinExplorerBar, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinExplorerBar control.

== link:winexplorerbar-understanding-winexplorerbar.html[Understanding WinExplorerBar]

In this section you'll find any information that will help you to better understand the functionalities of the WinExplorerBar control, as well as why you would want to use it to as part of building your applications.

== link:winexplorerbar-getting-started-with-winexplorerbar.html[Getting Started with WinExplorerBar]

In order to get you up and running as quickly as possible with the WinExplorerBar control, we've provided you with information on how to get started using the component (i.e., using the WinExplorerBar designer).

== link:win-winexplorerbar-using-winexplorerbar.html[Using WinExplorerBar]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinExplorerBar control.

== link:winexplorerbar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinExplorerBar control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.