////

|metadata|
{
    "name": "winexplorerbar-hide-quickcustomize-button-and-navigationoverflowbuttonarea",
    "controlName": ["WinExplorerBar"],
    "tags": ["How Do I","Styling"],
    "guid": "{146D310F-5447-4307-BD45-57A27C2175AB}",  
    "buildFlags": [],
    "createdOn": "2009-08-07T10:09:28Z"
}
|metadata|
////

= Hide QuickCustomize Button and NavigationOverflowButtonArea

The NavigationOverflowButtonArea displays buttons that do not fit in the NavigationGroupHeaderArea, through the Quick Customize or Configure buttons. The NavigationOverflowButtonArea is always visible even if there are no buttons in it.

This topic shows how you can hide the NavigationOverflowButtonArea and the Quick customize buttons of the ExplorerBar with its style set to OutlookNavigationPane. It can be done using the  pick:[win-forms="link:{ApiPlatform}win.ultrawinexplorerbar{ApiVersion}~infragistics.win.ultrawinexplorerbar.ultraexplorerbar~navigationoverflowbuttonareavisible.html[NavigationOverflowButtonAreaVisible]"]  property.

*In Visual Basic:*

----
Me.ultraExplorerBar1.NavigationOverflowButtonAreaVisible = false
----

*In C#:*

----
this.ultraExplorerBar1.NavigationOverflowButtonAreaVisible = false;
----