////

|metadata|
{
    "name": "wineditors-editor-controls-classification",
    "controlName": ["WinEditors"],
    "tags": ["Extending"],
    "guid": "5cf4cdf6-3203-4470-b752-00a0c41b4d30",  
    "buildFlags": [],
    "createdOn": "2010-09-16T20:44:36.2071799Z"
}
|metadata|
////

= Editor Controls Classification

Infragistics Editor Controls fall into a few basic categories namely TextEditorControlBase, UltraWinEditorMaskedControlBase and UltraFormattedTextEditor. The following is the list of controls that fall under each of these categories.

== TextEditorControlBase

=== UltraComboEditor

===== UltraTimeZoneEditor

===== UltraFontNameEditor

==== UltraTextEditor

===== UltraTimeSpanEditor

=== UltraColorPicker

=== UltraCalculatorDropDown

=== UltraCombo (WinGrid)

=== UltraCalendarCombo (WinSchedule)

== UltraWinEditorMaskedControlBase

=== UltraNumericEditor

=== UltraCurrencyEditor

=== UltraDateTimeEditor

=== UltraMaskedEdit

== UltraFormattedTextEditor

=== UltraFormattedTextEditor