////

|metadata|
{
    "name": "wineditors",
    "controlName": ["WinEditors"],
    "tags": [],
    "guid": "{739A7471-B710-4945-B2DF-6BB3668123CE}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinEditors

Because the WinEditor™ controls (e.g., WinCalculator™, WinCalculatorDropDown™, WinCheckEditor™) are part of the WinEditors assembly and take advantage of similar features, we have grouped topics that apply to multiple WinEditor controls together in this section.

Below are links to valuable information about the WinEditor controls ranging from what the WinEditor controls do and why you would want to use them in your application, to step-by-step procedures on how to accomplish tasks common to multiple WinEditor controls.

* link:wineditors-understanding-wineditor-controls.html[Understanding WinEditor Controls] -- In this section you'll find information that will help you to better understand the functionalities of the WinEditor controls, as well as why you would want to use the controls to develop your applications.
* link:wineditors-using-wineditors.html[Using WinEditors] -- In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinEditor controls.
* link:wineditors-api-overview.html[API Overview] -- This topic lists the namespaces and classes that you will be working with while programming with WinEditor controls. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.