////

|metadata|
{
    "name": "winformattedtexteditor",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{041274F2-D771-45AA-A6E3-78E5AC99DB98}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinFormattedTextEditor

If you're looking for an area that houses all of the overview/task-based information related to the WinFormattedTextEditor™ control, you've come to the right place. This section contains valuable information about WinFormattedTextEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinFormattedTextEditor control.

== link:winformattedtexteditor-understanding-winformattedtexteditor.html[Understanding WinFormattedTextEditor]

In this section you'll find any information that will help you to better understand the functionalities of the WinFormattedTextEditor control, as well as why you would want to use it to as part of building your applications.

== link:win-winformattedtexteditor-using-winformattedtexteditor.html[Using WinFormattedTextEditor]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinFormattedTextEditor control.

== link:winformattedtexteditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinFormattedTextEditor control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.