////
|metadata|
{
    "name": "winformattedlinklabel-api-overview",
    "controlName": ["WinFormattedLinkLabel"],
    "tags": ["API"],
    "guid": "{86D613A5-71D4-45FB-B6C5-E05A0B67B44B}",
    "buildFlags": [],
    "createdOn": "2006-11-01T00:00:00Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the control. We also give you several key classes that you will be using while programming with this control. The namespaces and classes on this page link directly into our API documentation.

[cols="a,a"]
|====
|*WinFormattedLinkLabel Namespace:* +
(Misc Assembly) 

pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.formattedlinklabel_namespace.html[Infragistics.Win.FormattedLinkLabel Namespace]"]
|*Key Classes:* 

pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.formattedlinklabel.ultraformattedlinklabel.html[UltraFormattedLinkLabel]"]

|*WinFormattedLinkLabel Namespace:* 

(Win Assembly) 

pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel_namespace.html[Infragistics.Win.FormattedLinkLabel Namespace]"]
|*Key Classes:* 

pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedlinkeditor.html[FormattedLinkEditor]"] 

pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.linkclickedeventargs.html[LinkClickedEventArgs]"] 

pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.parseerroreventargs.html[ParseErrorEventArgs]"] 

pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.visitedlinkscollection.html[VisitedLinksCollection]"]

|====