////

|metadata|
{
    "name": "winformattedtexteditor-understanding-winformattedtexteditor",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{13CF663C-36E4-427A-897D-A8A23350049D}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Understanding WinFormattedTextEditor

This is a great place for you to start learning about the WinFormattedTextEditor™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinFormattedTextEditor in your applications.

Click the links below to gain an overview of the WinFormattedTextEditor control.

* link:winformattedtexteditor-about-winformattedtexteditor.html[About WinFormattedTextEditor]
* link:winformattedlinklabel-formatting-text-and-hyperlinks.html[Formatting Text and Hyperlinks]
* link:winformattedtexteditor-default-keyactionmappings-for-winformattedtexteditor.html[Default KeyActionMappings for WinFormattedTextEditor]
* link:winformattedtexteditor-support-dialogs.html[WinFormattedTextEditor Support Dialogs]
* link:winformattedtexteditor-the-winformattedtexteditor-smart-tag.html[The WinFormattedTextEditor Smart Tag]