////

|metadata|
{
    "name": "winformattedtexteditor-smooth-formatted-text",
    "controlName": [],
    "tags": ["Styling"],
    "guid": "{80A529D1-6C94-4BBA-857D-9BCD99ADF53A}",  
    "buildFlags": [],
    "createdOn": "2006-12-09T13:24:56Z"
}
|metadata|
////

= Smooth Formatted Text

The WinFormattedTextEditor™ control can smooth over any of its text by using a technique known as anti-aliasing. This smoothing capability turns jagged edges (aliasing) of letters into smooth curves (anti-aliasing). What really happens is that pixels of gray are added to the letter to give the effect of smooth edges. This can be very helpful if the visual appeal of the content is more important than the content itself.

At design time, you can set the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.formattedlinklabel.ultraformattedtexteditorbase~textsmoothingmode.html[TextSmoothingMode]"]  property in the Properties window to AntiAlias. Doing so will render all text as anti-aliased. To achieve the same effect at run time, use the following code:

*In Visual Basic:*

----
Me.UltraFormattedTextEditor1.TextSmoothingMode =_
  Infragistics.Win.FormattedLinkLabel.TextSmoothingMode.AntiAlias
----

*In C#:*

----
this.ultraFormattedTextEditor1.TextSmoothingMode =
  Infragistics.Win.FormattedLinkLabel.TextSmoothingMode.AntiAlias;
----

You also have the option of using this smoothing technique on specific text inside the Value property by using link:winformattedtexteditor-style-attribute.html[the Style attribute]. If you want only a portion of text to be anti-aliased, encapsulate the text in the following <span> tag:

----
<span >Text to be anti-aliased</span>
----