////

|metadata|
{
    "name": "winformattedlinklabel",
    "controlName": ["WinFormattedLinkLabel"],
    "tags": [],
    "guid": "{700317AC-5AEB-48A2-9F58-E966861815CE}",  
    "buildFlags": [],
    "createdOn": "2006-11-01T00:00:00Z"
}
|metadata|
////

= WinFormattedLinkLabel

If you're looking for an area that houses all of the overview/task-based information related to the WinFormattedLinkLabel™ control, you've come to the right place. This section contains valuable information about WinFormattedLinkLabel, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinFormattedLinkLabel control.

== link:winformattedlinklabel-understanding-winformattedlinklabel.html[Understanding WinFormattedLinkLabel]

In this section you'll find any information that will help you to better understand the functionalities of the WinFormattedLinkLabel control, as well as why you would want to use it to as part of building your applications.

== link:win-winformattedlinklabel-using-winformattedlinklabel.html[Using WinFormattedLinkLabel]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinFormattedLinkLabel control.

== link:winformattedlinklabel-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinFormattedLinkLabel control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.