////

|metadata|
{
    "name": "winformattedtexteditor-display-winformattedtexteditors-support-dialog-boxes",
    "controlName": [],
    "tags": ["How Do I"],
    "guid": "{360C71EB-7C04-4AAA-B599-A14AD3589BC0}",  
    "buildFlags": [],
    "createdOn": "2006-12-09T13:29:33Z"
}
|metadata|
////

= Display WinFormattedTextEditor's Support Dialog Boxes

WinFormattedTextEditor™ has three support dialog boxes which assist the end user in formatting their document. These dialog boxes help the end user format  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedtexteditinfo~showfontdialog.html[Fonts]"] ,  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedtexteditinfo~showimagedialog.html[Images]"] , and  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedtexteditinfo~showlinkdialog.html[Hyperlinks]"] . Although WinFormattedTextEditor has a unique context menu which the end user can launch these dialog boxes from, you may also need to launch these dialog boxes from a button, perhaps in a toolbar.

The following code demonstrates how to open the Font dialog box. You can place this code in a click event or a particular method that suits your application's logic.

*In Visual Basic:*

----
Me.UltraFormattedTextEditor1.EditInfo.ShowFontDialog()
----

*In C#:*

----
this.ultraFormattedTextEditor1.EditInfo.ShowFontDialog();
----