////

|metadata|
{
    "name": "winformattedlinklabel-understanding-winformattedlinklabel",
    "controlName": ["WinFormattedLinkLabel"],
    "tags": ["Getting Started"],
    "guid": "{BC0A6DA5-2106-4442-B35A-85F6EC251C4D}",  
    "buildFlags": [],
    "createdOn": "2006-11-01T00:00:00Z"
}
|metadata|
////

= Understanding WinFormattedLinkLabel

This is a great place for you to start learning about the WinFormattedLinkLabel™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinFormattedLinkLabel in your applications.

Click the links below to gain an overview of the WinFormattedLinkLabel control.

* link:winformattedlinklabel-about-winformattedlinklabel.html[About WinFormattedLinkLabel] -- Introduces you to the WinFormattedLinkLabel control.
* link:winformattedlinklabel-formatting-text-and-hyperlinks.html[Formatting Text and Hyperlinks] -- Gives an in-depth look into how to format text using XML tags.
* link:winformattedtexteditor-style-attribute.html[Style Attribute] -- Much like the above topic, but focuses on the Style attribute and Span tag.
* link:winformattedlinklabel-smart-tag.html[WinFormattedLinkLabel Smart Tag] -- Describes the properties and settings that are displayed in the WinFormattedLinkLabel control's Smart Tag.