////

|metadata|
{
    "name": "winformattedtexteditor-prevent-text-from-being-edited",
    "controlName": [],
    "tags": ["How Do I","Tips and Tricks"],
    "guid": "{B732D14E-BF8A-4255-AC55-E91962DC698A}",  
    "buildFlags": [],
    "createdOn": "2006-12-09T13:01:10Z"
}
|metadata|
////

= Prevent Text from Being Edited

WinFormattedTextEditor™ is a formatted text editor with great editing capabilities. But what if you don't want the end user editing its contents? What if you also want the end user to be able to select the contents and copy it to the clipboard. There are several situations where this could become a reality, for example, a document being bound to Microsoft® Visual SourceSafe, or a product key in an application's About dialog box. Setting WinFormattedTextEditor to read-only mode is accomplished by setting the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.formattedlinklabel.ultraformattedtexteditor~readonly.html[ReadOnly]"]  property to True. Set the property at design time in the Properties window or at run time with the following code:

*In Visual Basic:*

----
Me.ultraFormattedTextEditor1.ReadOnly = True
----

*In C#:*

----
this.ultraFormattedTextEditor1.ReadOnly = true;
----