////

|metadata|
{
    "name": "winformattedtexteditor-clear-all-style-attributes",
    "controlName": [],
    "tags": ["Styling"],
    "guid": "{4F144E39-5086-4775-99EF-ACF04915C799}",  
    "buildFlags": [],
    "createdOn": "2006-12-09T13:02:39Z"
}
|metadata|
////

= Clear All Style Attributes

Adding styles to text can make all the difference in the world. However, mistakes can be made when styling text. What if the end user needs to remove styles from formatted text? What if the formatted text needs to become unformatted? The  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedtexteditinfo~clearallstyleattributes.html[ClearAllStyleAttributes]"]  method does just this. No arguments in this method; it simply removes any style attributes currently applied to the selected text. Use this method as a type of "eraser" for the end user, or use it if you need to parse through and remove formatting before saving the underlying XML document as a plain text document.

The following code demonstrates how to clear every style attribute from the currently selected text. Execute this code from a button click or context menu item.

*In Visual Basic:*

----
Me.UltraFormattedTextEditor1.EditInfo.ClearAllStyleAttributes()
----

*In C#:*

----
this.ultraFormattedTextEditor1.EditInfo.ClearAllStyleAttributes();
----