////

|metadata|
{
    "name": "winformmanager",
    "controlName": ["WinFormManager"],
    "tags": [],
    "guid": "0740f945-ba26-4818-819e-c31f8720242e",  
    "buildFlags": [],
    "createdOn": "2010-06-03T22:00:35.2375105Z"
}
|metadata|
////

= WinFormManager

If you're looking for an area that houses all of the overview/task-based information related to the WinFormManager™ component, you've come to the right place. This section contains valuable information about WinFormManager, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinFormManager component.

== link:winformmanager-understanding-winformmanager.html[Understanding WinFormManager]

In this section you'll find any information that will help you to better understand the functionalities of the WinFormManager component, as well as why you would want to use it to as part of building your applications.

== link:winformmanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTimeSpanEditor component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.