////

|metadata|
{
    "name": "wingauge",
    "controlName": ["WinGauge"],
    "tags": [],
    "guid": "{F2CD8B08-CFFC-4330-85F2-3672470860D5}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinGauge

If you're looking for an area that houses all of the overview/task-based information related to the WinGauge™ control, you've come to the right place. This section contains valuable information about WinGauge, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinGauge control.

== link:wingauge-understanding-wingauge.html[Understanding WinGauge]

In this section you'll find any information that will help you to better understand the functionalities of the WinGauge control, as well as why you would want to use it to as part of building your applications.

== link:wingauge-gauge-types.html[Gauge Types]

This key section contains a comprehensive listing of all the gauge types, along with a brief overview of the gauge type, information on the type of data that is required to generate the gauge type, and a list of properties specific to the gauge type.

== link:wingauge-designer.html[Gauge Designer]

This section contains information on the key features and functionalities provided by the Gauge Designer.

== link:wingauge-getting-started-with-wingauge.html[Getting Started with WinGauge]

In order to get you up and running as quickly as possible with the WinGauge control, we've provided you with information on how to get started using the control (e.g., adding WinGauge to your form).

== link:wingauge-using-gauge.html[Using Gauge]

This section contains information on the key features and functionalities provided by the WinGauge control.

== link:wingauge-deploying-wingauge.html[Deploying WinGauge]

If your application uses the WinGauge control, refer to this topic for a list of the Infragistics product assemblies that you need to redistribute as part of your application.

== link:wingauge-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinGauge control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.