////

|metadata|
{
    "name": "wingrid-changing-the-height-of-a-single-row",
    "controlName": ["WinGrid"],
    "tags": ["Grids","How Do I"],
    "guid": "{9226192F-881E-4D71-9EA0-AEFE6475040E}",  
    "buildFlags": [],
    "createdOn": "2005-11-07T00:00:00Z"
}
|metadata|
////

= Changing the Height of a Single Row

You can allow your users to change the height of a single row without affecting the rest of the rows in the band by using the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride~rowsizing.html[RowSizing]"]  property of the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride.html[Override]"]  object.

Enter the following code in the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragrid~initializelayout_ev.html[InitializeLayout]"]  event:

*In Visual Basic:*

----
Imports Infragistics.Win.UltraWinGrid
...
Private Sub UltraGrid1_InitializeLayout(ByVal sender As Object, _
  ByVal e As Infragistics.Win.UltraWinGrid.InitializeLayoutEventArgs) _
  Handles UltraGrid1.InitializeLayout
	e.Layout.Override.RowSizing = RowSizing.Free
End Sub
----

*In C#:*

----
using Infragistics.Win.UltraWinGrid;
...
private void ultraGrid1_InitializeLayout(object sender, 
  Infragistics.Win.UltraWinGrid.InitializeLayoutEventArgs e)
{
	e.Layout.Override.RowSizing = RowSizing.Free;
}
----