////

|metadata|
{
    "name": "wingridbaglayoutpanel",
    "controlName": ["WinGridBagLayoutPanel"],
    "tags": [],
    "guid": "{A19814EF-BB10-4EDD-9720-F11F655EF67D}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinGridBagLayoutPanel

If you're looking for an area that houses all of the overview/task-based information related to the WinGridBagLayoutPanel™ control, you've come to the right place. This section contains valuable information about WinGridBagLayoutPanel, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinGridBagLayoutPanel control.

== link:wingridbaglayoutpanel-understanding-wingridbaglayoutpanel.html[Understanding WinGridBagLayoutPanel]

In this section you'll find any information that will help you to better understand the functionalities of the WinGridBagLayoutPanel control, as well as why you would want to use it to as part of building your applications.

== link:wingridbaglayoutpanel-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinGridBagLayoutPanel control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.