////

|metadata|
{
    "name": "wingridrowedittemplate-using-wingridrowedittemplate",
    "controlName": [],
    "tags": ["Getting Started","How Do I","Templating"],
    "guid": "{2303588F-3A67-436C-B8E4-E61E7203C0EB}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Using WinGridRowEditTemplate

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by the WinGridRowEditTemplate™ control.

* link:wingridrowedittemplate-adding-a-wingridrowedittemplate-dialog-box-to-wingrid.html[Adding a WinGridRowEditTemplate Dialog Box to WinGrid]
* link:wingridrowedittemplate-adding-buttons-to-wingridrowedittemplates-dialog-box.html[Adding Buttons to WinGridRowEditTemplate's Dialog Box]
* link:wingridrowedittemplate-creating-a-wingridrowedittemplate-programmatically.html[Creating a WinGridRowEditTemplate Programmatically]
* link:wingridcellproxy-add-a-wingridcellproxy-to-a-wingridrowedittemplate.html[Add a WinGridCellProxy to a WinGridRowEditTemplate]