////

|metadata|
{
    "name": "wingriddocumentexporter-about-wingriddocumentexporter",
    "controlName": ["WinGridDocumentExporter"],
    "tags": [],
    "guid": "{D77C97D8-00A1-4C88-B6A7-FB23DAFDE019}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= About WinGridDocumentExporter

WinGridDocumentExporter™, like WinGridExcelExporter™, is a component with exporting functionality that enables you to export your entire WinGrid™ to either a PDF or XML Paper Specification (XPS) document.

A simple method, the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~export.html[Export]"]  method, is all you need for basic exporting functionality. There are also several events that you can take advantage of to tweak the export to your liking. Most of these events fire when a certain object, such as a row, header, or cell is about to be exported and after the object is exported. There are also events that fire at the beginning and end of the entire export. An important event, the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~initializerow_ev.html[InitializeRow]"]  event, allows you to change the layout of the grid before it is exported, giving you the power to customize the look of individual rows of the grid before they are exported.