////

|metadata|
{
    "name": "winganttview",
    "controlName": ["WinGanttView"],
    "tags": [],
    "guid": "{E5CC4E82-9AC5-4AD8-B98B-1505EEE5E575}",  
    "buildFlags": [],
    "createdOn": "2010-05-01T10:55:54Z"
}
|metadata|
////

= WinGanttView

If you're looking for an area that houses all of the overview/task-based information related to the WinGanttView™ control, you've come to the right place. This section contains valuable information about WinGanttView, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinGanttView control.

== link:winganttview-understanding-winganttview.html[Understanding WinGanttView]

In this section you'll find any information that will help you to better understand the functionalities of the WinGanttView control, as well as why you would want to use it to as part of building your applications.

== link:winganttview-using-winganttview.html[Using WinGanttView]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinGanttView control.

== link:winganttview-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinGanttView control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.