////

|metadata|
{
    "name": "wingrid-disabling-the-splitting-of-wingrid-into-regions",
    "controlName": ["WinGrid"],
    "tags": ["Grids","How Do I","Layouts"],
    "guid": "{FE771681-693C-4499-9F9C-A37213D0EBD4}",  
    "buildFlags": [],
    "createdOn": "2005-11-07T00:00:00Z"
}
|metadata|
////

= Disabling the Splitting of WinGrid into Regions

By default, the WinGrid™ can be split into multiple scroll regions, either by  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridrow.html[Row]"]  or  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcolumn.html[Column]"] .

To prevent the user from splitting the grid via regions, you can set the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridlayout~maxcolscrollregions.html[MaxColScrollRegions]"]  or  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridlayout~maxrowscrollregions.html[MaxRowScrollRegions]"]  properties to 1.

*In Visual Basic:*

----
Private Sub Disable_the_Splitting_of_WinGrid_into_Regions_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Me.UltraGrid1.DisplayLayout.MaxColScrollRegions = 1
	Me.UltraGrid1.DisplayLayout.MaxRowScrollRegions = 1
End Sub
----

*In C#:*

----
private void Disable_the_Splitting_of_WinGrid_into_Regions_Load(object sender, EventArgs e)
{
	this.ultraGrid1.DisplayLayout.MaxColScrollRegions = 1;
	this.ultraGrid1.DisplayLayout.MaxRowScrollRegions = 1;
}
----