////

|metadata|
{
    "name": "wingrid-displaying-multi-line-cells",
    "controlName": ["WinGrid"],
    "tags": ["Grids","How Do I","Layouts"],
    "guid": "{7427BE13-3E61-435B-8E33-83F938BB96E8}",  
    "buildFlags": [],
    "createdOn": "2005-11-07T00:00:00Z"
}
|metadata|
////

= Displaying Multi-Line Cells

[start=1]
. Before you start writing any code, you should place using/imports directives in your code-behind so you don't need to always type out a member's fully qualified name.

*In Visual Basic:*

----
Imports Infragistics.Win
----

*In C#:*

----
using Infragistics.Win;
----

[start=2]
. You must set the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcolumn~cellmultiline.html[CellMultiLine]"]  property of the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcolumn.html[Column]"]  object to True.

*In Visual Basic:*

----
Me.UltraGrid1.DisplayLayout.Bands(0).Columns(1).CellMultiLine = DefaultableBoolean.True
----

*In C#:*

----
this.ultraGrid1.DisplayLayout.Bands[0].Columns[1].CellMultiLine = DefaultableBoolean.True;
----

[start=3]
. A natural implementation of the CellMultiLine property could be as follows by also setting the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcolumn~vertscrollbar.html[VertScrollBar]"]  property of the column to True.

*In Visual Basic:*

----
Me.UltraGrid1.DisplayLayout.Bands(0).Columns(1).VertScrollBar = True
----

*In C#:*

----
this.ultraGrid1.DisplayLayout.Bands[0].Columns[1].VertScrollBar = true;
----

[start=4]
. You may want to increase the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride~defaultrowheight.html[DefaultRowHeight]"]  of the grid to better illustrate this sample.

*In Visual Basic:*

----
Me.UltraGrid1.DisplayLayout.Override.DefaultRowHeight = 100
----

*In C#:*

----
this.ultraGrid1.DisplayLayout.Override.DefaultRowHeight = 100;
----

[start=5]
. Place the above snippets into the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragrid~initializelayout_ev.html[InitializeLayout]"]  event of the WinGrid™.

Run the project and type into a cell on column 1.

Press the enter key for a new line.

If the contents of the cell exceed the height of the row, you can use the vertical scroll bar to view the cell contents.