////

|metadata|
{
    "name": "winganttview-about-winganttview",
    "controlName": ["WinGanttView"],
    "tags": [],
    "guid": "{CCD8F08A-7899-4B67-9AC3-360E7D470373}",  
    "buildFlags": [],
    "createdOn": "2010-05-01T11:01:45Z"
}
|metadata|
////

= About WinGanttView

The WinGanttView™ control is designed for project management. Projects can be managed effectively and efficiently by adding several project related details such as  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.task.html[Task]"] ,  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.task~milestone.html[Milestone]"] ,  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.task~deadline.html[Deadline]"] ,  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.task~dependencies.html[Dependencies]"] , etc., to the GanttView control. This control is comprised of constituent parts namely: Grid section, Gantt chart section, vertical splitter and horizontal and vertical scrollbars. The Grid section of the control provides a tree structure, displaying details of each task. The Gantt chart section of the control gives an interactive representation of the complete project. It displays time intervals along a horizontal timeline similar to the WinTimelineView™ control. The splitter splits the grid and the chart section of the control.

The WinGanttView control is added to Infragistics.Win.UltraWinGanttView assembly and gets its functionality through the UltraCalendarInfo and UltraCalendarLook components that are also used by other WinSchedule™ controls.

Some of the features of WinGanttView control are:

* Add/Update/Delete tasks.
* Tasks with child tasks (or "sub-tasks") called summary tasks are represented as a summary bar in the Gantt chart section of the control.
* Synchronizing task details in the Grid and Gantt chart sections of the control.
* Sorting Column headers (Multi column sorting) in Grid section of the control.
* Rich tooltip support for tasks, milestones, summary bars, etc.
* Can be bound to any data source that WinSchedule supports.
* Support for working and non-working hours.
* Set tasks disabled or inactive.
* Styling WinGanttView with Appearance object as well as Infragistics AppStyling.
* Supports Infragistics very own creation and draw filters.

== Related Topics

* link:winganttview-terms-and-concepts.html[Terms and Concepts]
* link:winganttview-using-winganttview.html[Using WinGanttView]