////

|metadata|
{
    "name": "wingrid-using-wingrid",
    "controlName": ["WinGrid"],
    "tags": ["Getting Started","Grids"],
    "guid": "{1D1DFC8F-A843-4C81-940E-E5F1FCD9EE72}",  
    "buildFlags": [],
    "createdOn": "2007-07-11T14:29:19Z"
}
|metadata|
////

= Using WinGrid

Below is a list of sections that contain short, task-based topics that explain how to perform specific tasks related to the WinGrid™ control.

== link:wingrid-accessing-data.html[Accessing Data]

The main purpose of the™ control is to input or display data. This section describes the ways by which the WinGrid control accesses data.

== link:wingrid-application-scenarios.html[Application Scenarios]

In this section, you'll find topics that relate perfectly to the real time scenarios.

== link:wingrid-defining-layouts.html[Defining Layouts]

This section contains topics that list the various layouts by which the WinGrid can be defined.

== link:wingrid-dataerrorinfo-support.html[DataErrorInfo Support]

This topic presents DataErrorInfo feature with ability to handle data validations independent from IDataErrorInfo interface.

== link:wingrid-editing-data.html[Editing Data]

This section contains topics that show you how data can be edited and configured in WinGrid. For example, it contains topics that explain how to add rows, embed editors etc.,

== link:wingrid-filtering.html[Filtering]

WinGrid™ allows for data filtering to reduce data to a smaller, viewable subset. Click the link above to find out more information about WinGrid Filtering.

== link:wingrid-grouping.html[Grouping (WinGrid)]

Data in WinGrid can be grouped. Follow this section for more information on this.

== link:wingrid-hottracking.html[HotTracking (WinGrid)]

WinGrid™ supports hot-tracking appearance on Rows, Row selectors, Cells, Column headers and GroupBy rows.

== link:wingrid-navigation-and-selection.html[Navigation and Selection]

This section contains topics that will show you how to set up the WinGrid control for navigation and Selection.

== link:wingrid-performance-guide.html[Performance Guide]

This section provides useful information on performance improvement while working with WinGrid.

== link:wingrid-presenting-data.html[Presenting Data]

This section contains topics that explain how data is presented and also how formatting of data is done.

== link:wingrid-printing.html[Printing]

This section contains tasks related to printing of data in WinGrid.

== link:wingrid-sorting-overview.html[Sorting (WinGrid)]

Data in WinGrid can be sorted. Follow this section for more information on this.

== link:wingrid-styling-wingrid.html[Styling WinGrid]

This section contains various topics related to styling of the WinGrid control.

== link:wingrid-summaries.html[Summaries]

This section contains topics that explain how summaries which are displayed while performing calculations on columns, are positioned.