////

|metadata|
{
    "name": "wingrid-new-cell-appearances-whats-new-20063",
    "controlName": [],
    "tags": [],
    "guid": "{20422B33-0C4D-478F-A691-AD1BE7A72599}",  
    "buildFlags": [],
    "createdOn": "2006-10-10T13:39:02Z"
}
|metadata|
////

= New Cell Appearances

Two new appearances were added to WinGrid™. The  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride~readonlycellappearance.html[ReadOnlyCellAppearance]"]  on the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride.html[Override]"]  defines the appearance of cells when they are read-only, or not editable. The  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcell~selectedappearance.html[SelectedAppearance]"]  on the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcell.html[UltraGridCell]"]  defines the appearance of cells when they are selected. You can modify these appearances just as you would any other  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.appearance.html[Appearance]"]  object. For more information, see link:win-appearance-objects.html[Appearance Objects].