////

|metadata|
{
    "name": "wingrid-conditional-formatting",
    "controlName": ["WinGrid"],
    "tags": [],
    "guid": "{A2FEF6A7-283E-4122-8696-10074DA24D4F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Conditional Formatting

If you're looking for an area that houses all of the overview/task-based information related to Conditional Formatting, you've come to the right place. This section contains valuable information about Conditional Formatting, ranging from what the feature does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the feature.

Click the links below to access important information about Conditional Formatting.

== link:win-understanding-conditional-formatting.html[Understanding Conditional Formatting]

In this section you'll find any information that will help you to better understand the functionalities of Conditional Formatting, as well as why you would want to use it as part of building your applications.

== link:wingrid-using-conditional-formatting.html[Using Conditional Formatting]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks using Conditional Formatting.