////

|metadata|
{
    "name": "wingridrowedittemplate-understanding-wingridrowedittemplate",
    "controlName": [],
    "tags": ["Getting Started","Templating"],
    "guid": "{94642161-FF03-4294-BC1B-3CEC74C528BA}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Understanding WinGridRowEditTemplate

This is a great place for you to start learning about the WinGridRowEditTemplate™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinGridRowEditTemplate in your applications.

Click the links below to gain an overview of the WinGridRowEditTemplate control.

* link:wingridrowedittemplate-about-wingridrowedittemplate.html[About WinGridRowEditTemplate] -- Introduces you to the WinGridRowEditTemplate control.
* link:wingridrowedittemplate-smart-tag.html[WinGridRowEditTemplate Smart Tag] -- Describes the properties and settings that are displayed in the WinGridRowEditTemplate control's Smart Tag.