////

|metadata|
{
    "name": "wingauge-designer",
    "controlName": ["WinGauge"],
    "tags": ["Charting","Getting Started"],
    "guid": "{F26A9FBB-2DC0-4B90-8881-A2E0C20E4F45}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Gauge Designer

The Gauge Designer consists of a gallery of Linear, Digital and Radial gauges, ranging from basic to complex designs. It allows you to choose a predefined gauge, and add it to the Gauge control. For example if you wanted to create a complex radial gauge such as a speedometer you can simply select it from the designer and it will be automatically added to your Gauge control. With the designer's user-friendly interface, you can quickly and easily manipulate the properties of the Gauge control.

Click the following links to get started with the Gauge Designer:

* link:wingauge-layout-of-the-gauge-designer.html[Layout of the Gauge Designer]
* link:wingauge-working-with-gauge-presets.html[Working with Gauge Presets]
* link:wingauge-using-the-gauge-designer.html[Using the Gauge Designer]