////

|metadata|
{
    "name": "wingauge-marker-movement",
    "controlName": ["WinGauge"],
    "tags": ["Charting"],
    "guid": "{AA6EB372-042F-40F6-BBBE-6E244775CAF3}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Marker Movement

You can configure a marker's Value to point to different values on the scale.

This allows the end user to interact with your gauge. The end user can drag the needle on your Radial gauge to point to a different value on the scale. The needle marker on your Radial gauge can be moved in the following ways:

* Manually -- You can configure the needle on your gauge to be moved manually by the end user. This allows the end user to change the value to which the needle is pointing on the scale.
* Automatically -- You can configure the needle on your gauge to move automatically at specific time intervals and distances on the scale.

With Linear gauges, the marker can only move automatically.

== Related Topics

link:wingauge-allow-manual-movement-of-the-needle.html[Allow Manual Movement of the Needle]

link:wingauge-move-the-needle-marker-automatically.html[Move the Needle Automatically]

link:wingauge-move-the-bar-marker-automatically.html[Move the Bar Marker Automatically]