////

|metadata|
{
    "name": "wingauge-properties-panel",
    "controlName": ["WinGauge"],
    "tags": ["Charting","Design Environment"],
    "guid": "{C978732F-609A-4791-9A7B-F6FEA71D208E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Properties Panel

The Properties panel of the Gauge Designer displays the properties of the currently selected gauge. For more information about the Properties panel, see link:wingauge-about-properties-panel.html[About Properties Panel].

The Properties panel is designed using tabs. These tabs allow you to edit the properties of the gauge. The tabs are divided into the following categories:

* link:wingauge-changing-the-layout-of-your-gauge.html[Changing the Layout of Your Gauge]
* link:wingauge-changing-the-appearance-of-your-gauge.html[Changing the Appearance of Your Gauge]
* link:wingauge-changing-the-annotations-on-your-gauge.html[Changing the Annotations on Your Gauge]
* link:wingauge-applying-effects-to-your-gauge.html[Applying Effects to Your Gauge]