////

|metadata|
{
    "name": "wingauge-changing-the-layout-of-your-gauge",
    "controlName": ["WinGauge"],
    "tags": ["Charting","Design Environment"],
    "guid": "{AE7AF015-D7DF-4808-A1AC-134D48F8A7B3}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Changing the Layout of Your Gauge

The Properties panel offers a number of different layout tabs that you can use to modify how components of your gauge are laid out. For example, you can specify how much space there is between tick marks in your Radial gauge using the Tickmarks Layout tab.

Click the following links for a description of each of the Layout tabs available in the Properties panel:

* link:wingauge-anchor-layout-tab.html[Anchor Layout Tab]
* link:wingauge-back-anchor-layout-tab.html[Back Anchor Layout Tab]
* link:wingauge-bar-marker-layout-tab.html[Bar Marker Layout Tab]
* link:wingauge-dial-layout-tab.html[Dial Layout Tab]
* link:wingauge-gauge-layout-tab.html[Gauge Layout Tab]
* link:wingauge-labels-layout-tab.html[Labels Layout Tab]
* link:wingauge-needle-marker-layout-tab.html[Needle Marker Layout Tab]
* link:wingauge-range-layout-tab.html[Range Layout Tab]
* link:wingauge-scale-layout-tab.html[Scale Layout Tab]
* link:wingauge-tickmark-layout-tab.html[Tickmark Layout Tab]