////

|metadata|
{
    "name": "wingriddocumentexporter-new-wingriddocumentexporter-component-whats-new-20072",
    "controlName": [],
    "tags": [],
    "guid": "{4E495CBC-0483-4C29-B811-97A8ED22DBEC}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= New WinGridDocumentExporter Component

The 2007 Volume 2 release marks the inception of the Infragistics Document Engine™. This unique code library allows you to create entire, custom-made reports in PDF or XML Paper Specification (XPS) format using its intuitive document object model. Borrowing this functionality, the WinGridDocumentExporter™ component can export your entire WinGrid™ (or any part of it) to a PDF or XPS file.

WinGridDocumentExporter is very similar to the WinGridExcelExporter™ component in that all that is necessary to export the grid is to call the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~export.html[Export]"]  method off the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter.html[WinGridDocumentExporter]"]  object. Of course, we didn't just leave it at that. Included in the component is an extensive event model giving you absolute control over what is exported and how.

== Related Topics

link:wingriddocumentexporter-export-wingrid-to-a-new-pdf-document.html[Export WinGrid to a New PDF Document]

link:wingriddocumentexporter-export-wingrid-to-an-existing-report.html[Export WinGrid to an Existing Report]

link:wingriddocumentexporter-use-a-file-buffer-when-exporting.html[Use a File Buffer When Exporting]

link:wingriddocumentexporter-change-the-paper-orientation-and-size.html[Change the Paper Orientation and Size]

link:wingriddocumentexporter-modifying-wingrids-layout-before-exporting-to-a-pdf-document.html[Modifying WinGrid's Layout Before Exporting to a PDF Document]