////

|metadata|
{
    "name": "wingrid-using-the-or-logical-operator-to-filter-across-columns",
    "controlName": ["WinGrid"],
    "tags": ["Application Scenarios","Grids"],
    "guid": "{2AEB200E-38BC-4196-8BE9-7B291B3F4002}",  
    "buildFlags": [],
    "createdOn": "2005-11-07T00:00:00Z"
}
|metadata|
////

= Using the "OR" Logical Operator to Filter Across Columns

By default, the WinGrid™ uses the "AND" logical operator to combine filters across columns. Therefore, if a row fails column filters of at least one column, then the row is considered to be filtered out. You can alter this behavior and use the "OR" logical operator to combine filters across columns by setting the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.columnfilter~logicaloperator.html[LogicalOperator]"]  property of the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.columnfilterscollection.html[ColumnFiltersCollection]"]  object. This way a row has to fail all the column filters in order for it to be considered filtered out. If it passes at least one column filter then it will be considered to be not filtered out.

.Note
[NOTE]
====
that for the child bands depending on the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride.html[Override's]"]  RowFilterMode property setting you will have to use the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.rowscollection~columnfilters.html[ColumnFilters]"]  of either the band or the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.rowscollection.html[RowsCollection]"] . See  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride~rowfiltermode.html[RowFilterMode]"]  for more information.
====