////

|metadata|
{
    "name": "wingauge-apply-brush-elements-using-the-gauge-designer",
    "controlName": ["WinGauge"],
    "tags": ["Charting","Design Environment"],
    "guid": "{6EDC79B1-32C2-4DC7-872D-905853B63E7B}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Apply Brush Elements Using the Gauge Designer

In the Appearance tab of the Gauge Designer, the left drop-down list is populated with the available brush types. Depending on which brush type you select, the adjacent drop-down list will populate with the color properties available for the selected brush type.

There are various brush elements available through the Gauge Designer. Specifying the brush type and its color allows you to dramatically change the look and feel of your property. Using the Appearance Tab, you can easily change the brush type and color of the property that is currently selected.

Click the following links for information on how to apply each brush element to your property using the Gauge Designer:

* link:wingauge-apply-the-hatch-brush-element-using-the-gauge-designer.html[Apply the Hatch Brush Element Using the Gauge Designer]
* link:wingauge-apply-the-multi-stop-linear-gradient-brush-element-using-the-gauge-designer.html[Apply the Multi-Stop Linear Gradient Brush Element Using the Gauge Designer]
* link:wingauge-apply-the-multi-stop-radial-gradient-brush-element-using-the-gauge-designer.html[Apply the Multi-Stop Radial Gradient Brush Element Using the Gauge Designer]
* link:wingauge-apply-the-radial-gradient-brush-element-using-the-gauge-designer.html[Apply the Radial Gradient Brush Element Using the Gauge Designer]
* link:wingauge-apply-the-simple-gradient-brush-element-using-the-gauge-designer.html[Apply the Simple Gradient Brush Element Using the Gauge Designer]
* link:wingauge-apply-the-solid-brush-element-using-the-gauge-designer.html[Apply the Solid Brush Element Using the Gauge Designer]
* link:wingauge-apply-the-texture-brush-element-using-the-gauge-designer.html[Apply the Texture Brush Element Using the Gauge Designer]