////

|metadata|
{
    "name": "wingroupbox",
    "controlName": ["WinGroupBox"],
    "tags": [],
    "guid": "{A4D15B16-367E-4B72-871A-E4A2249DBB33}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinGroupBox

Click the links below to find information specific to the WinGroupBox™ control.

* link:wingroupbox-about-wingroupbox.html[About WinGroupBox] -- Provides information on what the WinGroupBox control does, and why you would want to use it in your application.
* link:wingroupbox-smart-tag.html[WinGroupBox Smart Tag] -- Describes the properties and settings that are displayed in the WinGroupBox control's Smart Tag.
* link:wingroupbox-using-wingroupbox.html[Using WinGroupBox] -- In this section, you'll find short, task-based topics that explain how to perform a specific task related to the WinGroupBox control.
* link:wingroupbox-api-overview.html[API Overview] -- Lists the namespaces and classes that you will be working with while programming with the WinGroupBox control.

The WinGroupBox controls is often used in conjunction with the WinExpandableGroupBox™ control, which extends the functionality of WinGroupBox. See link:winexpandablegroupbox.html[WinExpandableGroupBox] for links to valuable information about the WinExpandableGroupBox control.