////

|metadata|
{
    "name": "winganttviewprintdocument-using-winganttviewprintdocument",
    "controlName": ["WinGanttView"],
    "tags": ["Printing"],
    "guid": "855e7602-0b95-4459-b8cf-d5421040c48a",  
    "buildFlags": [],
    "createdOn": "2012-02-09T15:23:46.0903016Z"
}
|metadata|
////

= Using WinGanttViewPrintDocument

In this section, you'll find short, task-based topics that explain how to perform a specific task related to the WinGanttViewPrintDocument™ control.

Click the links below to find out how you can…

* link:winganttviewprintdocument-configuring-the-legend.html[Configuring the Legend]
* link:winganttviewprintdocument-customizing-the-print-version-of-the-winganttview-control.html[Customizing the Print Version of the WinGanttView Control]
* link:winganttviewprintdocument-print-preview-with-winganttviewprintdocument.html[Print Preview with WinGanttViewPrintDocument]
* link:winganttviewprintdocument-winganttviewprintdocument-features.html[WinGanttViewPrintDocument Features]