////

|metadata|
{
    "name": "wingriddocumentexporter-use-a-file-buffer-when-exporting",
    "controlName": ["WinGridDocumentExporter"],
    "tags": ["Exporting"],
    "guid": "{3B69C319-29B0-4579-9F30-E9E794BBE9C9}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Use a File Buffer When Exporting

When exporting WinGrid™ to a PDF or XML Paper Specification (XPS) document, WinGridDocumentExporter™ stores images in a file buffer rather than in main memory. This alternate method of storage is useful if your system has limited RAM or requires the full use of its RAM on a regular basis. The file buffer is created in the system's Temp folder; however, it is possible your application may not have access to this folder. If you are unsure of the security rights your application may have, you can use the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~filebuffer.html[FileBuffer]"]  property to specify a file name and path for the file buffer. This allows you to place the file buffer in a folder that you're sure your application has access to. Additionally, you can disable the file buffer altogether by setting the  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~usefilebuffer.html[UseFileBuffer]"]  property to False.

Use the following code to set the path of the file buffer to the application's startup path:

*In Visual Basic:*

----
Me.UltraGridDocumentExporter1.FileBuffer = Application.StartupPath + "\Temp.tmp"
----

*In C#:*

----
this.ultraGridDocumentExporter1.FileBuffer = Application.StartupPath + "\\Temp.tmp";
----