////

|metadata|
{
    "name": "wingridcellproxy-about-wingridcellproxy",
    "controlName": [],
    "tags": ["Getting Started","Grids"],
    "guid": "{4A6ED1C3-AFCB-45C1-AA8C-97C645E0A9AA}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= About WinGridCellProxy

WinGridCellProxy™ is a unique control that acts as an editor in the WinGridRowEditTemplate™ control. Because of the unique design of the two controls, WinGridCellProxy can only function inside a WinGridRowEditTemplate control. By setting WinGridCellProxy's link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridcellproxy~columnkey.html[ColumnKey] property to a corresponding column key in the underlying data, WinGridCellProxy will display that column's data for whichever row the edit template is displaying. WinGridCellProxy will act as a multi-purpose embeddable editor, taking on the role of the particular embeddable editor that is displaying a column's data; hence the term "cell proxy".

== Related Topics

link:wingridrowedittemplate-about-wingridrowedittemplate.html[About WinGridRowEditTemplate]

link:wingridcellproxy-add-a-wingridcellproxy-to-a-wingridrowedittemplate.html[Add a WinGridCellProxy to a Row's Edit Template]