////

|metadata|
{
    "name": "wingrid-embeddable-editors",
    "controlName": ["WinGrid"],
    "tags": ["Extending","Grids"],
    "guid": "{649A480B-8839-4AB3-87E3-F96EA49855B6}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Embeddable Editors

Embeddable editors represent a major structural enhancement to WinGrid™ as well as other Infragistics Window Forms controls. Simply put, Embeddable editors embody all of the features and functionality that will allow you to provide a solid data entry point without having to write code. You can use these editors as stand-alone form controls or you can seamlessly integrate them into WinGrid.

Within the context of WinGrid, the embeddable editors are associated with the UltraGridColumn object. Whenever you assign an embeddable editor to a WinGrid Column, an instance of that editor is used whenever data is being edited.

Click the following links to learn more about using embeddable editors in WinGrid.

* link:wingrid-embeddable-column-editors.html[Embeddable Column Editors]
* link:wingrid-using-different-editors-in-individual-cells.html[Using Different Editors in Individual Cells]
* link:wingrid-using-windropdown-inside-wingrid.html[Using WinDropDown inside WinGrid]
* link:wingrid-using-wincomboeditor-inside-wingrid.html[Using WinComboEditor inside WinGrid]
* link:wingrid-using-winprogressbar-inside-wingrid.html[Use WinProgressBar inside WinGrid]
* link:wingrid-using-any-windows-forms-control-as-a-drop-down-inside-wingrid.html[Using Any Windows Forms Control as a Drop Down inside WinGrid]