////

|metadata|
{
    "name": "wingauge-api-overview",
    "controlName": ["WinGauge"],
    "tags": ["API","Charting"],
    "guid": "{C19C6765-5CBA-4CCE-9302-F20346A4B2BE}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the WinGauge™ control. We also give you several key classes that you will be using while programming with this control. The namespaces and classes on this page link directly into the "API Reference Guide" section of the help.

[cols="a,a"]
|====
|*WinGauge Namespace:* 

 

link:{ApiPlatform}win.ultrawingauge{ApiVersion}~infragistics.win.ultrawingauge_namespace.html[Infragistics.Win.UltraWinGauge] 


|*Key Classes:* 

 

link:{ApiPlatform}win.ultrawingauge{ApiVersion}~infragistics.win.ultrawingauge.ultragauge.html[UltraGauge] 



|*Resources Namespace:* 

 

link:{ApiPlatform}win.ultrawingauge{ApiVersion}~infragistics.ultragauge.resources_namespace.html[Infragistics.UltraGauge.Resources] 


|*Key Classes and Interface:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawingauge{ApiVersion}~infragistics.ultragauge.resources.igaugecomponent.html[IGaugeComponent]"] 

pick:[win-forms="link:{ApiPlatform}win.ultrawingauge{ApiVersion}~infragistics.ultragauge.resources.digitalgauge.html[DigitalGauge]"] 

pick:[win-forms="link:{ApiPlatform}win.ultrawingauge{ApiVersion}~infragistics.ultragauge.resources.lineargauge.html[LinearGauge]"] 

pick:[win-forms="link:{ApiPlatform}win.ultrawingauge{ApiVersion}~infragistics.ultragauge.resources.radialgauge.html[RadialGauge]"]

|====