////
|metadata|
{
    "name": "winganttview-api-overview",
    "controlName": ["WinGanttView"],
    "tags": ["API"],
    "guid": "{1FDB87C4-CE60-4449-808D-08D04BE262DF}",
    "buildFlags": [],
    "createdOn": "2010-05-01T11:14:17Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the control. We also give you several key classes that you will be using while programming with the WinGanttView controls. The namespaces and classes on this page link directly into our API documentation.

[cols="a,a"]
|====
|*WinGanttView Namespace:* +
pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinganttview_namespace.html[Infragistics.Win.UltraWinGanttView Namespace]"]
|*Key Classes:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinganttview.ultraganttview.html[UltraGanttView]"]

|*Infragistics.Win.UltraWinGanttView.UIElements Namespace:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinganttview.uielements_namespace.html[Infragistics.Win.UltraWinGanttView.UIElements Namespace]"]
|*Key Classes:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinganttview.uielements.taskareauielement.html[TaskAreaUIElement]"] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinganttview.uielements.gridareauielement.html[GridAreaUIElement]"] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinganttview.uielements.timelineareauielement.html[TimelineAreaUIElement]"] 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinganttview.uielements.ultraganttviewuielement.html[UltraGanttViewUIElement]"]

|*Infragistics.Win.UltraWinSchedule.TaskUI Namespace:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinschedule.taskui_namespace.html[Infragistics.Win.UltraWinSchedule.TaskUI Namespace]"]
|*Key Classes:* 

pick:[win-forms="link:{ApiPlatform}win.ultrawinganttview{ApiVersion}~infragistics.win.ultrawinschedule.taskui.taskdialog.html[TaskDialog]"]

|====