////

|metadata|
{
    "name": "wingrid-new-formattedtexteditor-option-added-to-columnstyle-enumeration-whats-new-20063",
    "controlName": [],
    "tags": [],
    "guid": "{AB67B3C7-E25C-499A-88AE-930CE76B3834}",  
    "buildFlags": [],
    "createdOn": "2006-10-10T13:46:59Z"
}
|metadata|
////

= New FormattedTextEditor Option Added to the ColumnStyle Enumeration

The  pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.columnstyle.html[ColumnStyle]"]  enumeration defines how a certain column will behave. In 2006 Volume 1, we added a FormattedText option to this enumeration to support the WinFormattedLinkLabel™ control as an embeddable editor. Now, we added the FormattedTextEditor option to the same enumeration to support the WinFormattedTextEditor™ control as an embeddable editor. The only difference between the two is that the later, FormattedTextEditor, supports editing, FormattedText does not. Essentially, this will allow you to edit formatted text in a WinGrid™ column. For more information on embedding the WinFormattedTextEditor control in a WinGrid column, see link:winformattedtexteditor-embedding-winformattedtexteditor-in-a-wingrid-column.html[Embedding WinFormattedTextEditor in a WinGrid Column].