////

|metadata|
{
    "name": "wingrid",
    "controlName": ["WinGrid"],
    "tags": [],
    "guid": "{658EC698-B2DB-402A-8B13-C46ED8980D48}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinGrid

If you're looking for an area that houses all of the overview/task-based information related to the WinGrid™ control, you've come to the right place. This section contains valuable information about WinGrid, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinGrid control.

== link:wingrid-understanding-wingrid.html[Understanding WinGrid]

In this section you'll find any information that will help you to better understand the functionalities of the WinGrid control, as well as why you would want to use it to as part of building your applications.

== link:wingrid-getting-started-with-wingrid.html[Getting Started with WinGrid]

In order to get you up and running as quickly as possible with the WinGrid control, we've provided you with information on how to get started using the control (i.e., adding WinGrid to a form).

== link:wingrid-using-wingrid.html[Using WinGrid]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinGrid control.

== link:wingrid-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinGrid control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.