////

|metadata|
{
    "name": "wingrid-creating-an-embeddable-editor-with-richtexteditor",
    "controlName": ["WinGrid"],
    "tags": ["Application Scenarios","Data Presentation","Grids"],
    "guid": "{E03D3D86-F606-469A-A5FF-F6679B5BA794}",  
    "buildFlags": [],
    "createdOn": "2005-11-07T00:00:00Z"
}
|metadata|
////

= Creating an Embeddable Editor with RichTextEditor

The following is information on using the EmbeddableEditorBase Class to create a RichTextEditor. The RichTextEditor is an  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.embeddableeditorbase.html[EmbeddableEditorBase]"] -derived editor that is able to render and edit RTF (Rich Text Format) content from within an  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.embeddableeditorownerbase.html[EmbeddableEditorOwnerBase]"]  implementer such as the WinGrid™. The RichTextEditor sample is available as part of the Infragistics Professional SDK install. By default, the sample is located in the following install folder, depending on your operating system:

* XP -- {InstallPathXP}{ProductNameVersion}\Samples\Win\WinGrid\CS\RICHTEXTEMBEDDABLEEDITOR
* Vista -- {InstallPathVista}{ProductNameVersion}\Samples\Win\WinGrid\CS\RICHTEXTEMBEDDABLEEDITOR

== Features

* Displays and edits RTF (Rich Text Format) content.
* Built-in open and save file functionality.
* Implements all required EmbeddableEditorBase properties and methods and can be embedded in any consumer that provides an EmbeddableEditorOwnerBase implementation.
* Can be easily embedded into the WinGrid control.
* Uses Infragistics' flexible 'Key-Action Mappings' keyboard model so that advanced keyboard functionality can be easily used within an Infragistics control.