////

|metadata|
{
    "name": "winlistview",
    "controlName": ["WinListView"],
    "tags": ["Getting Started"],
    "guid": "{D92B5486-61B4-4CC3-9F2A-6D3C75E5E230}",  
    "buildFlags": [],
    "createdOn": "2006-11-01T00:00:00Z"
}
|metadata|
////

= WinListView

If you're looking for an area that houses all of the overview/task-based information related to the WinListView control, you've come to the right place. This section contains valuable information about WinListView, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinListView™ control.

== link:winlistview-understanding-winlistview.html[Understanding WinListView]

In this section you'll find any information that will help you to better understand the functionalities of the WinListView control, as well as why you would want to use it to as part of building your applications.

== link:win-winlistview-using-winlistview.html[Using WinListView]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinListView control.

== link:winlistview-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinListView control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.