////

|metadata|
{
    "name": "winlistview-understanding-winlistview",
    "controlName": ["WinListView"],
    "tags": ["Getting Started"],
    "guid": "{750015C0-DE49-4C2D-8166-32F9B5E75678}",  
    "buildFlags": [],
    "createdOn": "2006-11-01T00:00:00Z"
}
|metadata|
////

= Understanding WinListView

This is a great place for you to start learning about the WinListView™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinListView in your applications.

Click the links below to gain an overview of the WinListView control.

* link:winlistview-about-winlistview.html[About WinListView] -- Introduces you to the WinListView control.
* link:winlistview-object-model.html[WinListView Object Model] -- A high-level overview of how the WinListView control works.
* link:winlistview-view-property.html[View Property] -- The most important property of the control, determines the look and feel.
* link:winlistview-smart-tag.html[WinListView Smart Tag] -- Describes the properties and settings that are displayed in the WinListView control's Smart Tag.