////

|metadata|
{
    "name": "winmessageboxmanager",
    "controlName": ["WinMessageBoxManager"],
    "tags": ["Getting Started"],
    "guid": "{B0AD766D-919A-4D89-90C7-90285A8074EE}",  
    "buildFlags": [],
    "createdOn": "2010-06-01T16:10:09Z"
}
|metadata|
////

= WinMessageBoxManager

If you're looking for an area that houses all of the overview/task-based information related to the WinMessageBoxManager™ component, you've come to the right place. This section contains valuable information about WinMessageBoxManager, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinMessageBoxManager component

== link:winmessageboxmanager-understanding-winmessageboxmanager.html[Understanding WinMessageBoxManager]

In this section you'll find any information that will help you to better understand the functionalities of the WinMessageBoxManager control, as well as why you would want to use it to as part of building your applications.

== link:winmessageboxmanager-using-winmessageboxmanager.html[Using WinMessageBoxManager]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinMessageBoxManager component.

== link:winmessageboxmanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinMessageBoxManager component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.