////

|metadata|
{
    "name": "winmessageboxmanager-about-winmessageboxmanager",
    "controlName": ["WinMessageBoxManager"],
    "tags": ["Getting Started"],
    "guid": "{E9DB34F3-9A4D-4F48-B1DB-A4D0F977C2D4}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= About WinMessageBoxManager

The WinMessageBoxManager™ component enables you to provide information to end users through a message box that can be styled and customized. Information to be displayed in the message box can be defined through an instance of the  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.ultramessagebox.ultramessageboxinfo.html[UltraMessageBoxInfo]"]  object. The key features of the WinMessageBoxManager component are:

* Styling using Appearance objects and AppStylist so as to match your application.
* The text within the message dialog window can be formatted by applying different colors and fonts, adding images, setting Url, etc.
* Separate Header, Content and Footer sections can be formatted individually for customizable display of your information.

== Related Topic

* link:winmessageboxmanager-working-with-winmessageboxmanager.html[Working with WinMessageBoxManager]