////
|metadata|
{
    "name": "winmaskededit-resource-strings",
    "controlName": [],
    "tags": ["Editing","Localization","Resource Strings"],
    "guid": "{246AEA9E-EC7C-4C71-B6FC-5A691F7E5EBA}",
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinMaskedEdit Resource Strings Reference

You can quickly and easily modify any resource string value that is displayed to a user by a control/component. Resource strings include items such as dialog box captions, warning messages, alerts, etc.

The following table lists the names of the resource strings that are used by this assembly, along with the string's default text value.

[options="header", cols="a,a"]
|====
|Resource String Name|Default Value

|LDR_InvalidTextForMask
|Specified text does not match the input mask.

|LDR_MaxValue
|Maximum value the user can enter in the control.

|LDR_MinValue
|Minimum value the user can enter in the control.

|LDR_Nullable
|Indicates whether empty text is allowed in the masked edit.

|LDR_NullText
|Text displayed when the value is null and the control doesn't have focus.

|LDR_UltraMaskedEdit_E_ValueChanged
|Occurs when the value changes.

|LDR_UltraMaskedEdit_P_AllowShiftingAcrossSections
|Specifies whether to shift characters across section boundaries when deleting characters.

|LDR_UltraMaskedEdit_P_DisplayStyle
|Specifies the overall look of the control.

|====