////

|metadata|
{
    "name": "winnavigationbar-understanding-winnavigationbar",
    "controlName": ["WinNavigationBar"],
    "tags": ["Getting Started","Navigation"],
    "guid": "{469C4C1A-C37E-44FD-B24D-DF2F8CE22870}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Understanding WinNavigationBar

This is a great place for you to start learning about the WinNavigationBar™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinNavigationBar in your applications.

Click the links below to gain an overview of the WinNavigationBar control.

* link:winnavigationbar-about-winnavigationbar.html[About WinNavigationBar] -- Introduces you to the WinNavigationBar control.
* link:winnavigationbar-comparing-winnavigationbar-to-wintree-and-winlistview.html[Comparing WinNavigationBar to WinTree and WinListView] -- Identifies the pros and cons of the WinTree™ and WinListView™ controls when navigating hierarchical structures and how the WinNavigationBar control can replace or augment them.
* link:winnavigationbar-smart-tag.html[WinNavigationBar Smart Tag] -- Describes the properties and settings that are displayed in the WinNavigationBar control's Smart Tag.