////

|metadata|
{
    "name": "winnumericeditor",
    "controlName": ["WinNumericEditor"],
    "tags": ["Getting Started"],
    "guid": "{25B906FF-2309-459F-AE0F-AE465E90B23A}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinNumericEditor

If you're looking for an area that houses all of the overview/task-based information related to the WinNumericEditor™ control, you've come to the right place. This section contains valuable information about WinNumericEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinNumericEditor control.

== link:winnumericeditor-understanding-winnumericeditor.html[Understanding WinNumericEditor]

In this section you'll find any information that will help you to better understand the functionalities of the WinNumericEditor control, as well as why you would want to use it to as part of building your applications.

== link:winnumericeditor-using-winnumericeditor.html[Using WinNumericEditor]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinNumericEditor control.

== link:winnumericeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinNumericEditor control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.