////

|metadata|
{
    "name": "winnavigationbar",
    "controlName": ["WinNavigationBar"],
    "tags": ["Getting Started","Navigation"],
    "guid": "{33E83186-9D78-41F8-A7C3-458BE3299B68}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinNavigationBar

If you're looking for an area that houses all of the overview/task-based information related to the WinNavigationBar™ control, you've come to the right place. This section contains valuable information about WinNavigationBar, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinNavigationBar control.

== link:winnavigationbar-understanding-winnavigationbar.html[Understanding WinNavigationBar]

In this section you'll find any information that will help you to better understand the functionalities of the WinNavigationBar control, as well as why you would want to use it to as part of building your applications.

== link:win-winnavigationbar-using-winnavigationbar.html[Using WinNavigationBar]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinNavigationBar control.

== link:winnavigationbar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinNavigationBar control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.