////

|metadata|
{
    "name": "winnumericeditor-incrementing-the-spin-value",
    "controlName": ["WinNumericEditor"],
    "tags": ["How Do I"],
    "guid": "{1518E55B-6F4A-4BE0-AB6A-D4E89221391E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Incrementing the Spin Value (WinNumericEditor)

This topic applies to the following WinEditor™ controls:

* WinCurrencyEditor™
* WinDateTimeEditor™
* WinMaskedEdit™
* WinNumericEditor™

The WinEditor™ control allows a user to change a value incrementally with the arrow keys and the spin buttons. In order to increment by values other than one you will need to set the  pick:[win-forms="link:{ApiPlatform}win.ultrawineditors{ApiVersion}~infragistics.win.ultrawineditors.ultranumericeditor~spinincrement.html[SpinIncrement]"]  property to a non-negative, rational value.

.Note
[NOTE]
====
For more information on additional tasks required to set the SpinIncrement for WinMaskedEdit, see link:winmaskededit-incrementing-the-spin-value.html[Incrementing the Spin Value (WinMaskedEdit)].
====

The following example code demonstrates how to increment WinNumericEditor’s  pick:[win-forms="link:{ApiPlatform}win.ultrawineditors{ApiVersion}~infragistics.win.ultrawineditors.ultranumericeditor~value.html[Value]"]  by 11.

*In Visual Basic:*

----
Me.UltraNumericEditor1.SpinIncrement = 11
----

*In C#:*

----
this.UltraNumericEditor1.SpinIncrement = 11;
----