////

|metadata|
{
    "name": "winoptionset",
    "controlName": ["WinOptionSet"],
    "tags": [],
    "guid": "{EAB38313-225F-440F-BCF8-955F9D817B74}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinOptionSet

If you're looking for an area that houses all of the overview/task-based information related to the WinOptionSet control, you've come to the right place. This section contains valuable information about WinOptionSet, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinOptionSet™ control.

== link:winoptionset-understanding-winoptionset.html[Understanding WinOptionSet]

In this section you'll find any information that will help you to better understand the functionalities of the WinOptionSet control, as well as why you would want to use it to as part of building your applications.

== link:winoptionset-using-winoptionset.html[Using WinOptionSet]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinOptionSet control.

== link:winoptionset-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinOptionSet control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.