////

|metadata|
{
    "name": "winribbboncustomizationprovider-understanding-winribbboncustomizationprovider",
    "controlName": ["WinRibbonCustomizationProvider"],
    "tags": ["Editing","Extending"],
    "guid": "f0152308-1507-4ff1-ba17-148834d971c9",  
    "buildFlags": [],
    "createdOn": "2011-04-26T19:14:16.5883946Z"
}
|metadata|
////

= Understanding WinRibbbonCustomizationProvider

This is a great place for you to start learning about the WinRibbonCustomizationProvider™ component, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinRibbonCustomizationProvider in your applications.

Click the links below to gain an overview of the WinRibbonCustomizationProvider component.

* link:winribboncustomizationprovider-about-winribboncustomizationprovider.html[About WinRibbonCustomizationProvider] -- Provides information on what the WinRibbonCustomizationProvider component does, and why you would want to use it in your application.
* link:winribboncustomizationprovider-smart-tag.html[WinRibbonCustomizationProvider Smart Tag]-- Describes the properties and settings that are displayed in the WinRibbonCustomizationProvider component's Smart Tag.