////

|metadata|
{
    "name": "winribboncustomizationprovider-api-overview",
    "controlName": ["WinRibbonCustomizationProvider"],
    "tags": ["API"],
    "guid": "fee02737-9477-4976-ad00-a12c37fd50e6",  
    "buildFlags": [],
    "createdOn": "2011-04-26T19:22:27.7855094Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the component. We also give you several key classes that you will be using while programming with this component. The namespaces and classes on this page link directly into our API documentation.

=== WinRibbonCustomizationProvider Namespace:

pick:[win-forms="link:{ApiPlatform}win.supportdialogs{ApiVersion}~infragistics.win.supportdialogs.ribboncustomizationprovider_namespace.html[Infragistics.Win.SupportDialogs.RibbonCustomizationProvider Namespace]"]

=== Key Classes:

pick:[win-forms="link:{ApiPlatform}win.supportdialogs{ApiVersion}~infragistics.win.supportdialogs.ribboncustomizationprovider.ultraribboncustomizationprovider.html[UltraRibbonCustomizationProvider]"]

pick:[win-forms="link:{ApiPlatform}win.supportdialogs{ApiVersion}~infragistics.win.supportdialogs.ribboncustomizationprovider.ribboncustomizationdialog.html[RibbonCustomizationDialog]"]

pick:[win-forms="link:{ApiPlatform}win.supportdialogs{ApiVersion}~infragistics.win.supportdialogs.ribboncustomizationprovider.ribboncustomizationcontrol.html[RibbonCustomizationControl]"]

pick:[win-forms="link:{ApiPlatform}win.supportdialogs{ApiVersion}~infragistics.win.supportdialogs.ribboncustomizationprovider.qatcustomizationcontrol.html[QATCustomizationControl]"]