////

|metadata|
{
    "name": "winstatusbar-understanding-winstatusbar",
    "controlName": ["WinStatusBar"],
    "tags": [],
    "guid": "{FEB8E5DF-F3E8-4C7A-9114-9B6B45BC4EE2}",  
    "buildFlags": [],
    "createdOn": "2005-08-12T00:00:00Z"
}
|metadata|
////

= Understanding WinStatusBar

This is a great place for you to start learning about the WinStatusBar™ control, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinStatusBar in your applications.

Click the links below to gain an overview of the WinStatusBar control.

* link:winstatusbar-about-winstatusbar.html[About WinStatusBar] -- Introduces you to the WinStatusBar control.
* link:winstatusbar-panel-styles.html[Panel Styles] -- Describes the different panel styles available with the WinStatusBar control.
* link:winstatusbar-panel-sizing-modes.html[Panel Sizing Modes] -- Describes the different panel sizing modes available with the WinStatusBar control.
* link:winstatusbar-smart-tag.html[WinStatusBar Smart Tag] -- Describes the properties and settings that are displayed in the WinStatusBar control's Smart Tag.