////

|metadata|
{
    "name": "winspellchecker",
    "controlName": ["WinSpellChecker"],
    "tags": [],
    "guid": "{0730ECD4-D120-4B46-96FA-A688CC2E597B}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinSpellChecker

If you're looking for an area that houses all of the overview/task-based information related to the WinSpellChecker™ component, you've come to the right place. This section contains valuable information about WinSpellChecker, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinSpellChecker component.

== link:winspellchecker-understanding-winspellchecker.html[Understanding WinSpellChecker]

In this section you'll find any information that will help you to better understand the functionalities of the WinSpellChecker component, as well as why you would want to use it to as part of building your applications.

== link:winspellchecker-getting-started-with-winspellchecker.html[Getting Started with WinSpellChecker]

In order to get you up and running as quickly as possible with the WinSpellChecker component, we've provided you with information on how to get started using the control (i.e., adding WinSpellChecker to a form).

== link:win-winspellchecker-using-winspellchecker.html[Using WinSpellChecker]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinSpellChecker component.

== link:winspellchecker-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinSpellChecker component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.