////

|metadata|
{
    "name": "winstatusbar-set-the-panel-style-to-text",
    "controlName": ["WinStatusBar"],
    "tags": ["How Do I","Styling"],
    "guid": "{5CC5CE5D-1418-400E-9AE3-AA0FDE315493}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= Set the Panel Style to Text

The Text panel is simply a panel on the WinStatusBar™ that acts as a standard label or static text area.

== Setting up Text Style Panel at Design-Time

[start=1]
. Add a UltraStatusBar to your Windows Form
[start=2]
. In the Property Pages scroll down to the Panels Property. Click the ellipsis to bring up the  pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanelscollection.html[Panels]"]  Collection.
[start=3]
. Click the "Add" button. This will add a new panel.
[start=4]
. Scroll the properties until you come to the  pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel~style.html[Style]"]  property. Set the Style property equal to Text.
[start=5]
. Set the  pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel~text.html[Text]"]  property equal to the value you want to display in this status bar panel.
[start=6]
. Click OK to close the window and you will see your panel added to the status bar.

== Setting up Text Style Panel at Run-Time

*In Visual Basic:*

----
Imports Infragistics.Win.UltraWinStatusBar
...
Private Sub Set_the_Panel_Style_to_Text_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	' Create new panel
	Dim myPanel As New UltraStatusPanel()
	' Set the style for the panel
	myPanel.Style = PanelStyle.Text
	' Set the default text
	myPanel.Text = "This is My UltraStatusBar Text Panel"
	' Add the panel to the element
	Me.UltraStatusBar1.Panels.Add(myPanel)
End Sub
----

*In C#:*

----
using Infragistics.Win.UltraWinStatusBar;
...
private void Set_the_Panel_Style_to_Text_Load(object sender, EventArgs e)
{
	// Create new panel
	UltraStatusPanel myPanel = new UltraStatusPanel();
	// Set the style for the panel
	myPanel.Style = PanelStyle.Text;
	// Set the default text
	myPanel.Text = "This is My UltraStatusBar Text Panel";
	// Add the panel to the element
	this.ultraStatusBar1.Panels.Add(myPanel);
}
----