////

|metadata|
{
    "name": "winstatusbar-resource-strings",
    "controlName": [],
    "tags": ["Localization","Resource Strings"],
    "guid": "{A951F479-9063-4B0A-999B-B0205140DA6A}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= WinStatusBar Resource Strings Reference

You can quickly and easily modify any resource string value that is displayed to a user by a control/component. Resource strings include items such as dialog box captions, warning messages, alerts, etc.

The following table lists the names of the resource strings that are used by this assembly, along with the string's default text value.

[options="header", cols="a,a"]
|====
|Resource String Name|Default Value

|AccessibleActionCheck
|Check

|AccessibleActionPush
|Push

|AccessibleActionShowCaretPosDialog
|Show caret position dialog

|AccessibleActionUncheck
|Uncheck

|AccessibleDesc_SizeGrip
|Can be used to resize a window's width and height

|AccessibleName_SizeGrip
|Size box

|CaretPositionDialogLineNumberCaption
|&Line number ({0} - {1})

|CaretPositionDialogMustEnterNumeric
|You must enter a numeric value.

|CaretPositionDialogUnableToNavigate
|Unable to navigate text control to the specified line.

|CharacterPositionFormatDefault
|Ln [Line] Ch [Char]

|====