////

|metadata|
{
    "name": "winschedule-about-winschedule-controls-and-components",
    "controlName": ["WinSchedule"],
    "tags": [],
    "guid": "{33C22B68-3F2E-4EF0-944D-6CD942AA235F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= About WinSchedule Controls and Components

The WinSchedule™ controls and components are comprised of five controls and three components. The following is a list of the five WinSchedule controls. The first control is an editor, the last four controls represent different scheduling views, which you can use to show scheduling/scheduled information to your end user. The scheduling views have a similar look and feel to the calendar in Microsoft® Outlook®.

* link:wincalendarcombo.html[WinCalendarCombo]™ -- Drop-down editor showing a one-month calendar.
* link:windayview.html[WinDayView]™ -- Used for viewing, adding, updating, and removing activities spanning one or more days.
* link:winmonthviewmulti.html[WinMonthViewMulti]™ -- Used for viewing appointments over a one-month time span.
* link:winmonthviewsingle.html[WinMonthViewSingle]™ -- Used for viewing, adding, updating, and removing activities over a one-calendar-month span of time.
* link:winweekview.html[WinWeekView]™ -- Used for viewing, adding, updating, and removing activities over a one-week span of time.

The following three components are used to control, manipulate, and synchronize the different views that you use on a Windows form.

* link:wincalendarinfo.html[WinCalendarInfo]™ -- Manages and exposes all scheduling information and control state synchronized across one or more WinSchedule views.
* link:wincalendarlook.html[WinCalendarLook]™ -- Manages the look and feel of the WinSchedule views.
* link:winscheduleprintdocument.html[WinSchedulePrintDocument]™ -- Allows for the printing of any of the WinSchedule views.