////

|metadata|
{
    "name": "winstatusbar-about-winstatusbar",
    "controlName": ["WinStatusBar"],
    "tags": ["Getting Started"],
    "guid": "{8EC7FF58-087C-44BD-AC23-79D42B1D90D5}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= About WinStatusBar

The following is a list of the key features of WinStatusBar™:

* *Thirteen Panel Styles --* UltraStatusBar provides 13 different panel styles to simply the most common StatusBar uses.
* *Multiple Panel Size Modes --* The  pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel.html[UltraStatusPanel]"]  provides a  pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel~sizingmode.html[SizingMode]"]  property to determine how the panel is sized. The panel may have a fixed width, be sized based on its contents, expand to fill the available area or allow resizing.
* *Panel resizing* -- Supported at both run time and design time.
* *SizeGrip --* Add sizing functionality to any container
* *XP Theme Support --* Automatically add an Windows XP Theme appearance to the StatusBar and its panels without the need for a manifest.
* *ViewStyle* -- A single property (ViewStyle) on the component that can be used to change the default appearance to either a Visual Studio 2005, Office 2003, Office 2007 or standard style display.