////

|metadata|
{
    "name": "winstatusbar-set-the-panel-style-to-mdilist",
    "controlName": ["WinStatusBar"],
    "tags": ["How Do I","Styling"],
    "guid": "{92CFB5AE-4802-4890-B5B9-FCB95DA565F0}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= Set the Panel Style to MDIList

The MDIList panel lists all of the open MDI child windows in an MDI application.

Setting up MDIList style Panel at Design-Time

[start=1]
. Add a UltraStatusBar to your Windows Form.
[start=2]
. In the Property window scroll down to the Panels Property. Click the ellipsis to bring up the  pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanelscollection.html[Panels]"]  Collection.
[start=3]
. Click the "Add" button. This will add a new panel.
[start=4]
. Set the  pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel~style.html[Style]"]  property of the panel to "MDIList". Click OK.
[start=5]
. In the Solution Explorer, add another form called "MDIForm." Add a button, with the following code behind it:

*In Visual Basic:*

----
Me.IsMdiContainer = True
Dim frm2 As New MDIForm()
frm2.MdiParent = Me
frm2.Show()
----

*In C#:*

----
this.IsMdiContainer = true;
MDIForm frm2 = new MDIForm();
frm2.MdiParent = this;
frm2.Show();
----

[start=6]
. Run your project. Each time you click the button a new window is added. For each child window in your application there will be an icon in the your status bar panel. If you click on that icon, it will bring the corresponding MDI child window to the front and make it active. In this simple example, all the windows have the same name, and same image; In a real-world application, you would vary these details.

Setting up MDIList style Panel at Run-Time

You can also create an MDIList panel at run time. The following example code below shows how to do this.

.Note
[NOTE]
====
This code assumes you have completed step 5 from the above steps.
====

*In Visual Basic:*

----
Imports Infragistics.Win.UltraWinStatusBar
...
Me.UltraStatusBar1.Panels.Add("MDIList", PanelStyle.MDIList)
----

*In C#:*

----
using Infragistics.Win.UltraWinStatusBar;
...
this.ultraStatusBar1.Panels.Add("MDIList", PanelStyle.MDIList);
----