////

|metadata|
{
    "name": "winstatusbar",
    "controlName": ["WinStatusBar"],
    "tags": [],
    "guid": "{B3D7AE35-EB47-4BC4-B971-78A844CCD279}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinStatusBar

If you're looking for an area that houses all of the overview/task-based information related to the WinStatusBar™ control, you've come to the right place. This section contains valuable information about WinStatusBar, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinStatusBar control.

== link:winstatusbar-understanding-winstatusbar.html[Understanding WinStatusBar]

In this section you'll find any information that will help you to better understand the functionalities of the WinStatusBar control, as well as why you would want to use it to as part of building your applications.

== link:win-winstatusbar-using-winstatusbar.html[Using WinStatusBar]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinStatusBar control.

== link:winstatusbar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinStatusBar control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.