////

|metadata|
{
    "name": "winspellchecker-understanding-winspellchecker",
    "controlName": ["WinSpellChecker"],
    "tags": [],
    "guid": "{F1F47E0D-93E4-4554-ACB6-EB24497FE21E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Understanding WinSpellChecker

This is a great place for you to start learning about the WinSpellChecker™ component, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinSpellChecker in your applications.

Click the links below to gain an overview of the WinSpellChecker component.

* link:winspellchecker-about-winspellchecker.html[About WinSpellChecker]
* link:winspellchecker-customizing-how-winspellchecker-spell-checks-documents.html[Customizing How WinSpellChecker Spell Checks Documents]
* link:winspellchecker-dictionaries.html[Dictionaries]
* link:winspellchecker-using-the-spell-checker-dialog.html[Using the Spell Checker Dialog]
* link:winspellchecker-smart-tag.html[WinSpellChecker Smart Tag]