////

|metadata|
{
    "name": "winsplitter-about-winsplitter",
    "controlName": ["WinSplitter"],
    "tags": [],
    "guid": "{B3C3492A-7651-4EEF-B5F3-D59EC392040D}",  
    "buildFlags": [],
    "createdOn": "2009-10-12T16:22:12Z"
}
|metadata|
////

= About WinSplitter

The WinSplitter™ control enables end users to resize controls that are docked to the edges of it at run time. When the end user mouse hovers over WinSplitter, the cursor changes to indicate that the controls docked to WinSplitter can be resized. You can dock WinSplitter either Top/Bottom or Left/Right in a form so that the contents can be resized horizontally or vertically.

Some of WinSplitter control's features include:

* *Collapse/Restore Content:* A Collapse/Restore button is available on the WinSplitter control to collapse or restore content on the form.
* *Styling:* WinSplitter can be styled through Appearance settings and AppStyling. The Collapse/Restore button can also be styled through various styling properties.

== Related Topics

* link:winsplitter-getting-started-with-winsplitter.html[Getting Started with WinSplitter] link:winsplitter-using-winsplitter.html[]
* link:winsplitter-using-winsplitter.html[Using WinSplitter]