////

|metadata|
{
    "name": "winschedule",
    "controlName": ["WinSchedule"],
    "tags": [],
    "guid": "{A66FC5AA-913D-4EE9-845C-A7EE5E8BCB84}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinSchedule

Because the WinSchedule™ controls (e.g., WinCalendarCombo™, WinMonthViewMulti™, WinCalendarLook™) are part of the WinSchedule assembly and take advantage of similar features, we've grouped topics that apply to multiple WinSchedule controls together in this section.

Below are links to valuable information about the WinSchedule controls ranging from what the WinSchedule controls do and why you would want to use them in your application, to step-by-step procedures on how to accomplish tasks common to multiple WinSchedule controls.

* link:winschedule-understanding-winschedule-controls-and-components.html[Understanding WinSchedule Controls and Components] -- In this section you'll find information that will help you to better understand the functionalities of the WinSchedule controls and components, as well as why you would want to use the controls and components to develop your applications.
* link:win-winschedule-using-winschedule.html[Using WinSchedule] -- In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinSchedule controls and components.
* link:winschedule-api-overview.html[API Overview] -- This topic lists the namespaces and classes that you will be working with while programming with WinSchedule controls and components. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.