////

|metadata|
{
    "name": "winsplitter",
    "controlName": ["WinSplitter"],
    "tags": [],
    "guid": "{AE35E220-F0E9-4D2C-BB4C-E97C667201C5}",  
    "buildFlags": [],
    "createdOn": "2009-10-12T16:15:34Z"
}
|metadata|
////

= WinSplitter

If you're looking for an area that houses all of the overview/task-based information related to the WinSplitter™ control, you've come to the right place. This section contains valuable information about WinSplitter, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinSplitter control.

== link:winsplitter-understanding-winsplitter.html[Understanding WinSplitter]

In this section you'll find any information that will help you to better understand the functionalities of the WinSplitter control, as well as why you would want to use it to as part of building your applications.

== link:winsplitter-getting-started-with-winsplitter.html[Getting Started with WinSplitter]

In order to get you up and running as quickly as possible with the WinSplitter control, we've provided you with information on how to get started using the control (i.e., adding WinSplitter to a form).

== link:winsplitter-using-winsplitter.html[Using WinSplitter]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinSplitter control.

== link:winsplitter-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinSplitter control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.