////

|metadata|
{
    "name": "wintrackbar",
    "controlName": ["WinTrackBar"],
    "tags": [],
    "guid": "{1B570F46-B858-4849-9A7F-C7DCF3EDF532}",  
    "buildFlags": [],
    "createdOn": "2008-10-01T15:45:10Z"
}
|metadata|
////

= WinTrackBar

If you're looking for an area that houses all of the overview/task-based information related to the WinTrackBar™ control, you've come to the right place. This section contains valuable information about WinTrackBar, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinTrackBar control.

== link:wintrackbar-understanding-wintrackbar.html[Understanding WinTrackBar]

In this section you'll find any information that will help you to better understand the functionalities of the WinTrackBar control, as well as why you would want to use it to as part of building your applications.

== link:wintrackbar-using-wintrackbar.html[Using WinTrackBar]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinTrackBar control.

== link:wintrackbar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTrackBar control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.