////

|metadata|
{
    "name": "wintoolbarsmanager-change-the-placement-of-tool-text",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{5777D896-1541-4880-942C-6C448D20F0A3}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= Change the Placement of Tool Text

pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbar.html[Toolbar]"]  buttons can be displayed with images, text or both. When both are displayed the text by default is to the right of the image. You have the option of changing that at design-time or run-time. The text can be displayed to the right, left, above or below the image by setting the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.toolbarsettings~captionplacement.html[CaptionPlacement]"]  property of the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.toolbarsettings.html[Settings]"]  object on the Toolbar.

== At Design-Time

[start=1]
. To configure the WinToolbarsManager™ component, open the design-time customizer by right-clicking on the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbarsmanager.html[UltraToolbarsManager]"]  element and selecting "Customize."
[start=2]
. Click the "Toolbars" tab in the customizer and select a toolbar.
[start=3]
. For the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbar~settings.html[Settings]"]  property, select the CaptionPlacement property and set it to where you want the text displayed.

== At Run-Time

*In Visual Basic:*

----
Imports Infragistics.Win
Imports Infragistics.Win.UltraWinToolbars
...
Private Sub ChangethePlacementofToolText_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Me.UltraToolbarsManager1.Tools("NewFile").SharedProps.DisplayStyle = _
	  ToolDisplayStyle.ImageAndText
	Me.UltraToolbarsManager1.Toolbars(1).Settings.CaptionPlacement = _
	  TextPlacement.BelowImage
End Sub
----

*In C#:*

----
using Infragistics.Win;
using Infragistics.Win.UltraWinToolbars;
...
private void ChangethePlacementofToolText_Load(object sender, System.EventArgs e)
{
	this.ultraToolbarsManager1.Tools["NewFile"].SharedProps.DisplayStyle = 
	  ToolDisplayStyle.ImageAndText;
	this.ultraToolbarsManager1.Toolbars[1].Settings.CaptionPlacement = 
	  TextPlacement.BelowImage;
}
----