////

|metadata|
{
    "name": "wintoolbarsmanager-ribbon-about-the-ribbon",
    "controlName": ["WinToolbarsManager"],
    "tags": ["Getting Started"],
    "guid": "{FEC2706A-49D4-45A7-BFEA-EA4097D62614}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= About the Ribbon

The Ribbon is a unique user interface component that is so intuitive it can take as little as two mouse clicks to perform any task associated with the Ribbon. The first click involves a  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ribbontab.html[RibbonTab]"] . These tabs contain  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ribbongroup.html[RibbonGroups]"] , which in turn contain tools. You may already be familiar with these tools as they are the same tools used in WinToolbarsManager™. Once the end-user clicks the proper tab, they only need to click the tool that they want to use in any of the groups in the tab. The Ribbon is different from a standard toolbar in that all toolbars and tools are readily available by clicking a tab. In order to meet this standard of readiness in a standard toolbar, you would need to have all toolbars with all tools viewable at the same time. This leads to a very cluttered user interface. The Ribbon cleans this disorganization by categorizing tools into groups, and groups into tabs.

Click a link below for a detailed explanation of the different components that come together to form the Ribbon.

* link:wintoolbarsmanager-office-2013-ribbon-look-and-feel.html[Office 2013 Ribbon Look and Feel]
* link:wintoolbarsmanager-office-2010-ribbon-look-and-feel.html[Office 2010 Ribbon Look and Feel]
* link:wintoolbarsmanager-office-2010-style-application-menu.html[Office 2010 Style Application Menu]
* link:wintoolbarsmanager-quick-access-toolbar.html[Quick Access Toolbar]
* link:wintoolbarsmanager-ribbon-tabs.html[Ribbon Tabs]
* link:wintoolbarsmanager-ribbon-groups.html[Ribbon Groups]
* link:wintoolbarsmanager-scenic-ribbon-look-and-feel.html[Scenic Ribbon Look and Feel]
* link:wintoolbarsmanager-the-ribbon-application-menu.html[The Ribbon Application Menu]