////

|metadata|
{
    "name": "wintree",
    "controlName": ["WinTree"],
    "tags": ["Getting Started"],
    "guid": "{1AB9256C-91F9-4AAA-9C4F-8F9DA07B0B9C}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinTree

If you're looking for an area that houses all of the overview/task-based information related to the WinTree™ control, you've come to the right place. This section contains valuable information about WinTree, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinTree control

== link:wintree-understanding-wintree.html[Understanding WinTree]

In this section you'll find any information that will help you to better understand the functionalities of the WinTree control, as well as why you would want to use it to as part of building your applications.

== link:wintree-using-wintree.html[Using WinTree]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinTree control.

== link:wintree-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTree control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.