////

|metadata|
{
    "name": "wintoolbarsmanager-add-toolbars-at-run-time",
    "controlName": ["WinToolbarsManager"],
    "tags": ["Layouts"],
    "guid": "{BC398B5D-2016-4844-8558-4C24B351843A}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= Add Toolbars at Run Time

pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbar.html[Toolbars]"]  can be added to the WinToolbarsManager™ component at run time as well as at design time. This is done by passing the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbar~key.html[Key]"]  of a toolbar to the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.toolbarscollection~addtoolbar.html[AddToolbar]"]  method. Once the toolbar has been added to the UltraToolBarsManager element, it can be configured by setting the appropriate properties of the toolbar.