////

|metadata|
{
    "name": "wintooltipmanager-understanding-wintooltipmanager",
    "controlName": ["WinToolTipManager"],
    "tags": [],
    "guid": "{C06E4AD8-569B-4C72-B7C5-4AEACE753B8F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Understanding WinToolTipManager

This is a great place for you to start learning about the WinToolTipManager™ component, and its key features and functionalities. The topics in this section will give you a better idea of why you would want to use WinToolTipManager in your applications.

Click the links below to gain an overview of the WinToolTipManager component.

* link:wintooltipmanager-about-wintooltipmanager.html[About WinToolTipManager] -- Introduces you to the WinToolTipManager component.
* link:winformattedlinklabel-formatting-text-and-hyperlinks.html[Formatted Text and Hyperlinks] -- Lists out the tags that can be used when the ToolTipTextStyle is set to Formatted.
* link:wintooltipmanager-tooltip-styles.html[Tooltip Styles] -- Describes the various tooltip styles available with the WinToolTipManager component.