////

|metadata|
{
    "name": "wintoolbarsmanager-gallerytoolitemclick-event",
    "controlName": ["WinToolbarsManager"],
    "tags": ["Events"],
    "guid": "{BB01FC53-71D8-4680-A008-85C225BCCD2F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= GalleryToolItemClick Event

This topic demonstrates how to process the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.popupgallerytool~gallerytoolitemclick_ev.html[GalleryToolItemClick]"]  event for GalleryToolItems in a  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.popupgallerytool.html[PopupGalleryTool]"] . When an end-user clicks any of the regular Tools, the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbarsmanager~toolclick_ev.html[ToolClick]"]  Event can be used to handle the Click. On the other hand, if any of the GalleryToolItems that are specific to the PopupGalleryTool are being clicked, the GalleryToolItemClick event needs to be handled.

*In Visual Basic:*

----
Private Sub ultraToolbarsManager1_GalleryToolItemClick (ByVal sender As Object, _
              ByVal e As GalleryToolItemEventArgs) Handles UltraToolbarsManager1. GalleryToolItemClick
                        'Specifies the GalleryToolItem that is clicked
                       System.Diagnostics.Debug.WriteLine (e.Item.Key)
    End Sub
----

*In C#:*

----
private void ultraToolbarsManager1_GalleryToolItemClick (object sender, GalleryToolItemEventArgs e)
        {
            // Specifies the GalleryToolItem that is clicked
            System.Diagnostics.Debug.WriteLine (e.Item.Key);
        }
----