////

|metadata|
{
    "name": "wintabbedmdimanager",
    "controlName": ["WinTabbedMdiManager"],
    "tags": [],
    "guid": "{15A7F48C-3B13-46C3-9616-0D84BBA222FF}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinTabbedMdiManager

If you're looking for an area that houses all of the overview/task-based information related to the WinTabbedMdiManager™ component, you've come to the right place. This section contains valuable information about WinTabbedMdiManager, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinTabbedMdiManager component.

== link:wintabbedmdimanager-understanding-wintabbedmdimanager.html[Understanding WinTabbedMdiManager]

In this section you'll find any information that will help you to better understand the functionalities of the WinTabbedMdiManager component, as well as why you would want to use it to as part of building your applications.

== link:win-wintabbedmanager-using-wintabbedmdimanager.html[Using WinTabbedMdiManager]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinTabbedMdiManager component.

== link:wintabbedmdimanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTabbedMdiManager component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.