////

|metadata|
{
    "name": "wintimespaneditor",
    "controlName": ["WinTimeSpanEditor"],
    "tags": [],
    "guid": "5a73999a-f6af-4f34-ba67-1bba1c025c05",  
    "buildFlags": [],
    "createdOn": "2010-06-03T20:19:04.501785Z"
}
|metadata|
////

= WinTimeSpanEditor

If you're looking for an area that houses all of the overview/task-based information related to the WinTimeSpanEditor™ control, you've come to the right place. This section contains valuable information about WinTimeSpanEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinTimeSpanEditor control.

== link:wintimespaneditor-understanding-wintimespaneditor.html[Understanding WinTimeSpanEditor]

In this section you'll find any information that will help you to better understand the functionalities of the WinTimeSpanEditor control, as well as why you would want to use it to as part of building your applications.

== link:wintimespaneditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTimeSpanEditor control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.