////

|metadata|
{
    "name": "wintabbedmdimanager-about-wintabbedmdimanager",
    "controlName": ["WinTabbedMdiManager"],
    "tags": [],
    "guid": "{46F60497-7415-4D7E-88BE-8103A5E21687}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= About WinTabbedMdiManager

The following is a list of the key features of WinTabbedMdiManager™:

* *Tabbed MultiDocument Interface (MDI)* - As seen in Microsoft Visual Studio.NET. Each MDI child form is represented by a tab item.
* *Multiple TabGroups* - Tab items can be organized into multiple vertical or horizontal tab groups.
* *Tab Styles* - Multiple tab styles are available including VisualStudio, Excel and Property Page.
* *Tab Sizing Modes* - Multiple tab sizing modes are available including fixed width, auto-sized and justified.
* *Tab and Text Orientation* - The orientation of the tab items and text can be completely customized. The tabs may be positioned above, below, left or right of the MDI child. The text may be oriented absolutely or relative to the orientation of the tabs.
* *Drag & Drop functionality* - Tabs can be repositioned within their tab groups, dragged to other tab groups or dragged to create new tab groups.
* *Save and load MDI layouts* - The positions and settings of the MdiTab objects and MdiTabGroups can be serialized. A custom event is invoked during the load process to allow the associated form to be loaded.
* *Hierarchical control settings* - Tab item settings can be set at the tab, tab group or element level. Tab group settings can be set for a specific tab group or for all tab groups.
* *Resizable Tab Groups* - A splitter bar is displayed between tab groups to allow the end user to resize the tab groups.
* *Custom Context Menus* - A default context menu is displayed for the tab items. Items may be added or removed.
* *ViewStyle* - A single property (ViewStyle) on the component that can be used to change the default appearance of the tab items and buttons to either a Visual Studio 2005, Office 2003, Office 2007, or standard style display.
* *Presentation Layer Framework* - Since the UltraTabbedMdiManager makes use of the Presentation Layer Framework, it includes the same functionality available in the other Infragistics windows elements including the ability to owner draw items (DrawFilter), modify their positions (CreationFilter), modify the cursor (CursorFilter) and enable and disable events dynamically (EventManager).