////

|metadata|
{
    "name": "wintoolbarsmanager-navigation-toolbar-show-the-navigation-toolbar",
    "controlName": ["WinToolbarsManager"],
    "tags": ["Navigation"],
    "guid": "{82402EA5-86E8-4C98-A4F5-CA9BAF7821FA}",  
    "buildFlags": [],
    "createdOn": "2007-12-09T12:13:01Z"
}
|metadata|
////

= Show the Navigation Toolbar

By default, the Navigation toolbar's  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.navigationtoolbar~visible.html[Visible]"]  property is set to False, which means the toolbar is hidden. Unlike the link:wintoolbarsmanager-working-with-the-ribbon.html[Ribbon] or the link:wintoolbarsmanager-creating-a-minitoolbar.html[Mini toolbar], the Navigation toolbar does not have a button on the link:wintoolbarsmanager-in-place-designer.html[WinToolbarsManager in-place designer] allowing you to quickly show the toolbar. While the ultraToolbarsManager1 component is selected, find the Visible property off the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.navigationtoolbar.html[NavigationToolbar]"]  object in the properties window and set it to True. You can also set the Navigation toolbar’s visibility at run time in the form’s Load event or a method call that suits your application’s logic.

The following code will cause the Navigation toolbar to be visible.

.Note
[NOTE]
====
The Navigation toolbar will not display if the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbarsmanager~office2007uicompatibility.html[Office2007UICompatibility]"]  property is set to True and the Ribbon is visible.
====

*In Visual Basic:*

----
Me.UltraToolbarsManager1.NavigationToolbar.Visible = True
----

*In C#:*

----
this.ultraToolbarsManager1.NavigationToolbar.Visible = true;
----