////

|metadata|
{
    "name": "wintab",
    "controlName": ["WinTab"],
    "tags": ["Getting Started"],
    "guid": "{1B0207D9-0A10-4A90-9881-E2842B871479}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinTab and WinTabStrip

If you're looking for an area that houses all of the overview/task-based information related to the WinTab™ and WinTabStrip™ controls, you've come to the right place. This section contains valuable information about WinTab and WinTabStrip, ranging from what the controls do and why you would want to use them in your application, to step-by-step procedures on how to accomplish a common task using the controls.

Click the links below to access important information about the WinTab and WinTabStrip controls.

== link:wintab-understanding-wintab-and-wintabstrip.html[Understanding WinTab and WinTabStrip]

In this section, you'll find information that will help you learn more about the WinTab and WinTabStrip controls; you'll also learn why you'd use these controls to build your applications.

== link:wintab-using-wintab-and-wintabstrip.html[Using WinTab and WinTabStrip]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinTab and WinTabStrip controls.

== link:wintab-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTab and WinTabStrip controls. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.