////

|metadata|
{
    "name": "wintilepanel-set-tiles-to-large-state",
    "controlName": ["WinTilePanel"],
    "tags": ["How Do I"],
    "guid": "{230E2444-D731-4D16-9A34-49B781D7D461}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Set Tiles to Large State

The WinTilePanel™ control allows one or more tiles to be put into large state. By default only one tile can be set to large state. In order to set multiple tiles to large state, the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultratilepanel~maximumvisiblelargetiles.html[MaximumVisibleLargeTiles]"]  property of the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultratilepanel.html[ultraTilePanel]"]  object must be set to an integer value.

The end-user can maximize a tile by clicking the StateChangeButton. When a tile is maximized all other Normal state tiles shrink and move to the side of the Panel.

It is also possible to maximize a tile through code using the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultratile~setstate(tilestate,boolean).html[SetState]"]  method or the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultratile~state.html[State]"]  property of the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultratile.html[UltraTile]"]  object. The SetState method accepts two parameters: the new state of the tile and a Boolean value whether to animate the tile’s state change.

The following code assumes that you have an UltraTilePanel dropped onto your form. For information on how to add tiles to WinTilePanel please see the link:wintilepanel-add-and-remove-tiles-through-code.html[Add and Remove Tiles through Code] topic.

*In Visual Basic:*

----
' Set the state of the Tile 
tile1.SetState(Infragistics.Win.Misc.TileState.Large, True)
tile3.State = TileState.Large
----

*In C#:*

----
// Set the state of the Tile
tile1.SetState(Infragistics.Win.Misc.TileState.Large,true);
tile3.State = TileState.Large;
----

You can also set the position and orientation of the large tiles using the  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultratilepanel~largetileposition.html[LargeTilePosition]"]  and  pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultratilepanel~largetileorientation.html[LargeTileOrientation]"]  properties.

*In Visual Basic:*

----
' Positons the Large tile to the right. Default positions left. 
Me.ultraTilePanel1.LargeTilePosition = LargeTilePosition.Right 
' Sets the Orientation of Large Tiles Horizontally. Default Orientation is Vertical. 
Me.ultraTilePanel1.LargeTileOrientation = Infragistics.Win.Misc.TileOrientation.Horizontal
----

*In C#:*

----
// Positons the Large tile to the right. Default positions left.
this.ultraTilePanel1.LargeTilePosition = LargeTilePosition.Right;
// Sets the Orientation of Large Tiles Horizontally. Default Orientation is Vertical.
this.ultraTilePanel1.LargeTileOrientation = Infragistics.Win.Misc.TileOrientation.Horizontal;
----