////

|metadata|
{
    "name": "wintooltipmanager",
    "controlName": ["WinToolTipManager"],
    "tags": [],
    "guid": "{07B86D6B-2E00-40A1-8BCA-6A53E96407BD}",  
    "buildFlags": [],
    "createdOn": "2005-08-12T00:00:00Z"
}
|metadata|
////

= WinToolTipManager

If you're looking for an area that houses all of the overview/task-based information related to the WinToolTipManager™ component, you've come to the right place. This section contains valuable information about WinToolTipManager, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinToolTipManager component.

== link:wintooltipmanager-understanding-wintooltipmanager.html[Understanding WinToolTipManager]

In this section you'll find any information that will help you to better understand the functionalities of the WinToolTipManager component, as well as why you would want to use it to as part of building your applications.

== link:win-wintooltipmanager-using-wintooltipmanager.html[Using WinToolTipManager]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinToolTipManager component.

== link:wintooltipmanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinToolTipManager component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.