////

|metadata|
{
    "name": "wintoolbarsmanager-installing-microsoft-office-2007-ui-capabilities",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{F7B1EFBF-D262-433B-92FE-E18B3ED60882}",  
    "buildFlags": [],
    "createdOn": "2006-09-10T16:04:03Z"
}
|metadata|
////

= Installing Microsoft Office 2007 UI Capabilities

Microsoft® Office 2007 adds new UI capabilities for organizing and navigating applications. These innovations represent a new wave for usability in application development.

.Note
[NOTE]
====
*Note:* When using the Microsoft Office 2007 UI capabilities provided as part of Infragistics Windows Forms, be aware that the Infragistics license grants you no rights to the Microsoft Office 2007 UI. For more information, please visit link:http://msdn.microsoft.com/en-us/library/bf08984t.aspx[http://msdn.microsoft.com/en-us/library/bf08984t.aspx].
====

Infragistics can install the following UI capabilities as part of its UltraToolbarsManager component:

* The Ribbon
* Application Menu
* Contextual Tabs
* KeyTips
* Galleries