////

|metadata|
{
    "name": "wintoolbarsmanager-you-can-now-merge-ribbons-in-a-multiple-document-interface-whats-new-20071",
    "controlName": [],
    "tags": [],
    "guid": "{67318585-924A-494C-9945-BCA48F28EA92}",  
    "buildFlags": [],
    "createdOn": "2006-11-12T15:22:52Z"
}
|metadata|
////

= You Can Now Merge Ribbons in a Multiple Document Interface

In 2006 Volume 3, we released the Ribbon. But one thing that the Ribbon couldn't handle was Multiple Document Interface (MDI) merging. Our standard toolbars have supported MDI merging for several releases now. Ribbon MDI merging is very similar to the previously existing MDI merging.

MDI merging allows your standard toolbars, and now your Ribbon, to merge with a parent toolbar or Ribbon. In the Ribbon's case, the parent form adds the Ribbon tabs and groups of the child forms to its own. This allows end users to maximize their work surface while keeping all tools from all child forms together in one logical place.

== Related Topics

link:wintoolbarsmanager-mdi-ribbon-merging.html[MDI Ribbon Merging]