////

|metadata|
{
    "name": "wintoolbarsmanager-initializechecked-whats-new-2006-1",
    "controlName": [],
    "tags": [],
    "guid": "{09657979-760E-43CE-B78B-3FAE1E226919}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= InitializeChecked

An  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.statebuttontool~initializechecked.html[InitializeChecked]"]  method has been added to both the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.statebuttontool.html[StateButtonTool]"]  class and  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.popuptoolbase.html[PopupToolBase]"]  class. This method allows you to set the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.statebuttontool~checked.html[Checked]"]  property without invoking the  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.toolclickeventargs.html[ToolClick]"]  event.