////

|metadata|
{
    "name": "wintimelineview",
    "controlName": ["WinTimelineView"],
    "tags": ["Getting Started"],
    "guid": "{C963A6FC-B2EE-46F9-B02B-134EA1E91D12}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinTimelineView

If you're looking for an area that houses all of the overview/task-based information related to the WinTimelineView™ control, you've come to the right place. This section contains valuable information about WinTimelineView, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinTimelineView control.

== link:wintimelineview-understanding-wintimelineview.html[Understanding WinTimelineView]

Provides information on what the WinTimelineView control does, and why you would want to use it in your application.

== link:wintimelineview-using-wintimelineview.html[Using WinTimelineView]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinTimelineView control.

== link:wintimelineview-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTimelineView control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.