////

|metadata|
{
    "name": "wintoolbarsmanager-add-a-textbox-to-a-toolbar",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{F3CEF828-B9CD-4B8A-B5F4-69B7CA134FF4}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= Add a TextBox to a Toolbar

The WinToolbarsManager™ component has 15 different tool types that you can add to a  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbar.html[ToolBar]"] . This demonstrates how to add a  pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.textboxtool.html[TextBoxTool]"]  design-time and run-time.

== At Design Time

[start=1]
. To configure the UltraWinToolbar element, open the design-time customizer by right-clicking on the UltraToolbarManager element and selecting "Customize".
[start=2]
. To create a new Tool, click the "Tools" tab in the customizer, and then the "New..." button.
[start=3]
. Select TextBox as your Tool Type and click on the Add button.
[start=4]
. Click the "ToolBars" tab in the customizer, and then the "New..." button.
[start=5]
. click the "Tools" tab and drag the TextBox tool to the ToolBar residing on the form.

== At Run Time

*In Visual Basic:*

----
Imports Infragistics.Win.UltraWinToolbars
...
Private Sub Add_a_TextBox_to_a_Toolbar_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Dim TextTool As New TextBoxTool("ttool")
	Me.UltraToolbarsManager1.Tools.Add(TextTool)
	Me.UltraToolbarsManager1.Toolbars(0).Tools.Add(TextTool)
End Sub
----

*In C#:*

----
using Infragistics.Win.UltraWinToolbars;
...
private void Add_a_TextBox_to_a_Toolbar_Load(object sender, EventArgs e)
{
	TextBoxTool TextTool = new TextBoxTool("ttool");
	this.ultraToolbarsManager1.Tools.Add(TextTool);
	this.ultraToolbarsManager1.Toolbars[0].Tools.Add(TextTool);
}
----