////

|metadata|
{
    "name": "wintoolbarsmanager",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{43F29760-83B0-41C3-82BD-9A5C28DFDBD0}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinToolbarsManager

If you're looking for an area that houses all of the overview/task-based information related to the WinToolbarsManager™ component, you've come to the right place. This section contains valuable information about WinToolbarsManager, ranging from what the component does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the component.

Click the links below to access important information about the WinToolbarsManager component.

== link:wintoolbarsmanager-understanding-wintoolbarsmanager.html[Understanding WinToolbarsManager]

In this section you'll find any information that will help you to better understand the functionalities of the WinToolbarsManager component, as well as why you would want to use it to as part of building your applications.

== link:wintoolbarsmanager-getting-started-with-wintoolbarsmanager.html[Getting Started with WinToolbarsManager]

In order to get you up and running as quickly as possible with the WinToolbarsManager component, we've provided you with information on how to get started using the component (e.g., adding WinToolbarsManager to a form).

== link:wintoolbarsmanager-working-with-the-ribbon.html[Working with the Ribbon]

The Ribbon is an incredibly unique user interface which uses a collection of Tabs and Groups to keep tools visible as much as possible. The Ribbon was designed to give your end users the Office 2007 look and feel.

== link:wintoolbarsmanager-working-with-toolbar-types.html[Working with Toolbar Types]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to manage the different toolbar types (i.e., Standard, MainMenu, TaskPane).

== link:wintoolbarsmanager-working-with-tool-types.html[Working with Tool Types]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to manage the different tool types (e.g., Button, ComboBox, and TextBox).

== link:wintoolbarsmanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinToolbarsManager component. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.