////

|metadata|
{
    "name": "wintabbedmdi-resource-strings",
    "controlName": [],
    "tags": ["Localization","Resource Strings"],
    "guid": "{BA064794-7310-4124-A77D-D07005AF5220}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= WinTabbedMdi Resource Strings Reference

You can quickly and easily modify any resource string value that is displayed to a user by a control/component. Resource strings include items such as dialog box captions, warning messages, alerts, etc.

The following table lists the names of the resource strings that are used by this assembly, along with the string's default text value.

[options="header", cols="a,a"]
|====
|Resource String Name|Default Value

|MenuItemCancel
|C&ancel

|MenuItemClose
|&Close

|MenuItemMaximize
|&Maximize

|MenuItemMoveToNextGroup
|Move to Ne&xt Tab Group

|MenuItemMoveToPreviousGroup
|Move to P&revious Tab Group

|MenuItemNewHorizontalGroup
|New Hori&zontal Tab Group

|MenuItemNewVerticalGroup
|New &Vertical Tab Group

|====