////

|metadata|
{
    "name": "wintilepanel",
    "controlName": ["WinTilePanel"],
    "tags": [],
    "guid": "{6291639F-8485-45E6-9434-A9AFE67C6232}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinTilePanel

If you're looking for an area that houses all of the overview/task-based information related to the WinTilePanel™ control, you've come to the right place. This section contains valuable information about WinTilePanel, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WinTilePanel control.

== link:wintilepanel-understanding-wintilepanel.html[Understanding WinTilePanel]

Provides information on what the WinTilePanel control does, and why you would want to use it in your application.

== link:wintilepanel-using-wintilepanel.html[Using WinTilePanel]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the WinTilePanel control.

== link:wintilepanel-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WinTilePanel control. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics Windows Forms help.   