////

|metadata|
{
    "name": "winweekview-api-overview",
    "controlName": ["WinWeekView"],
    "tags": ["API"],
    "guid": "{2FA1AEB5-7A8B-4E82-B9E2-F948F0D092AB}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the control. We also give you several key classes that you will be using while programming with this control. The namespaces and classes on this page link directly into our API documentation.

=== WinWeekView Namespace:

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview_namespace.html[Infragistics.Win.UltraWinSchedule.WeekView Namespace]"]

=== Key Classes:


link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview.currentdaynumberselectionareauielement.html[CurrentDayNumberSelectionAreaUIElement]


pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview.daynumberuielement.html[DayNumberUIElement]"]

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview.weekareauielement.html[WeekAreaUIElement]"]