////

|metadata|
{
    "name": "winweekview-display-the-background-image-behind-the-days-of-winweekview",
    "controlName": ["WinWeekView"],
    "tags": ["Styling"],
    "guid": "{D8E0FA69-FD8D-47A0-838F-ABF5D97578A4}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= Display the Background Image Behind the Days of WinWeekView

The following example demonstrates how to use the WinWeekView's™  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.ultracalendarlook.html[CalendarLook]"]  Object to display the  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.ultraweekview.html[UltraWeekView's]"]   pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.appearance~imagebackground.html[ImageBackground]"]  "behind" the days using the element's rich alpha-blending capabilities. This can be used to, for example, display a corporate logo in the element without distracting the end user.

[start=1]
. Set the property of the WinWeekView's  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.appearance.html[Appearance]"] .

*In Visual Basic:*

----
Me.UltraWeekView1.Appearance.ImageBackground = _
  Image.FromFile("Program Dependent Files\Sunset.jpg")
----

*In C#:*

----
this.ultraWeekView1.Appearance.ImageBackground =  
  Image.FromFile(@"Program Dependent Files\Sunset.jpg");
----

[start=2]
. Set the of the CalendarLook  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.ultracalendarlook~dayappearance.html[DayAppearance]"]  to half transparency.

*In Visual Basic:*

----
Me.UltraWeekView1.CalendarLook.DayAppearance.AlphaLevel = 128
----

*In C#:*

----
this.ultraWeekView1.CalendarLook.DayAppearance.AlphaLevel = 128;
----

[start=3]
. Set the CalendarLook DayAppearance  pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.appearance~backcoloralpha.html[BackColorAlpha]"]  to use the previously set AlphaLevel.

*In Visual Basic:*

----
Me.UltraWeekView1.CalendarLook.DayAppearance.BackColorAlpha = _
  Infragistics.Win.Alpha.UseAlphaLevel
----

*In C#:*

----
this.ultraWeekView1.CalendarLook.DayAppearance.BackColorAlpha = 
  Infragistics.Win.Alpha.UseAlphaLevel;
----

[start=4]
. Because the WinWeekView's DayAppearance is layered above it's WeekAppearance, set the  pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.ultracalendarlook~weekappearance.html[WeekAppearance]"]  BackColorAlpha to be transparent so that the ImageBackground will be displayed.

*In Visual Basic:*

----
Me.UltraWeekView1.CalendarLook.WeekAppearance.BackColorAlpha = _
  Infragistics.Win.Alpha.Transparent
----

*In C#:*

----
this.ultraWeekView1.CalendarLook.WeekAppearance.BackColorAlpha = 
  Infragistics.Win.Alpha.Transparent;
----