////
|metadata|
{
    "controlName": ["UltraCheckEditor","UltraComboEditor","UltraCurrencyEditor","UltraDateTimeEditor","UltraFontNameEditor","UltraMaskedEdit","UltraNumericEditor","UltraTextEditor","UltraTimeSpanEditor","UltraTimeZoneEditor","UltraGrid","UltraTree","UltraCombo","UltraSchedule","UltraCalendarCombo","UltraDayView","UltraGanttView","UltraMonthViewMulti","UltraMonthViewSingle","UltraTimelineView","UltraWeekView","UltraButton","UltraCalculator","UltraCalculatorDropdown","UltraDropDownButton","UltraLabel","UltraOptionSet","UltraPictureBox","UltraProgressBar","UltraStatusBar","UltraTrackbar"],
    "tags": []
}
|metadata|
////

= Zoom Supported Controls

The following controls currently have zooming support and will function properly within the UltraZoomPanel:

*  Editors
** UltraCheckEditor
** UltraComboEditor
** UltraCurrencyEditor
** UltraDateTimeEditor
** UltraFontNameEditor
** UltraMaskedEdit
** UltraNumericEditor
** UltraTextEditor
** UltraTimeSpanEditor
** UltraTimeZoneEditor

* UltraGrid
* UltraTree
* UltraCombo

* UltraSchedule
** UltraCalendarCombo
** UltraDayView
** UltraGanttView
** UltraMonthViewMulti
** UltraMonthViewSingle
** UltraTimelineView
** UltraWeekView

* UltraButton
* UltraCalculator
* UltraCalculatorDropdown
* UltraDropDownButton
* UltraLabel
* UltraOptionSet
* UltraPictureBox
* UltraProgressBar
* UltraStatusBar
* UltraTrackbar

Other controls may have zooming implemented for them, but have not yet met our testing requirements in their current state. They are therefore not officially supported, and are considered CTP.

More controls will be added to this list in future releases. To show interest in which control to add next, please visit link:http://ideas.infragistics.com[Ideas.Infragistics.com] and submit an idea or vote for current ones.