////

|metadata|
{
    "name": "word-using-the-infragistics-word-library",
    "controlName": ["Infragistics Word Library"],
    "tags": ["Exporting","How Do I"],
    "guid": "9f99d92b-ee57-4ff4-9765-d21cac62c3eb",  
    "buildFlags": [],
    "createdOn": "2011-03-18T14:00:31.085061Z"
}
|metadata|
////

= Using the Infragistics Word Library

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by the Word Library.

* link:word-create-a-word-document.html[Creating a Word Document]
* link:word-apply-formatting-to-word-document.html[Applying Formatting to Word Document]
* link:word-add-table-to-word-document.html[Adding Table to Word Document]
* link:word-add-images-to-word-document.html[Adding Images to Word Document]
* link:word-headers-footers-and-page-numbers.html[Headers Footers and Page Numbers]
* link:word-creating-word-document-using-object-model-approach.html[Creating Word Document Using OBject Model Approach]